### ISSUE TITLE
FarmOS Core: Add documents to the taxonomy terms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#135]
A second request to be able to add documents to Farm taxonomy assets – possibly FarmOS core.

This request comes from user feedback in February 2022 - see https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/70#issuecomment-1067184864

Duplicates:
- #23

**Comment by paul121** [comment]
We chatted about this today... lets try and figure out a good core solution. It might take a few more weeks. Relevant core issue: https://github.com/farmOS/farmOS/pull/536

**Comment by mstenta** [comment]
Update: I've opened a new farmOS core pull request to implement this. Might be able to get this into the next farmOS release!

https://github.com/farmOS/farmOS/pull/807

**Comment by aislinnpearson** [comment]
Amazing! Thanks Mike. I've added it to the next milestone so we can keep in touch about it.

**Comment by paul121** [comment]
@aislinnpearson this should be live in your instances now
