### ISSUE TITLE
Experiment Module: Determine minimum information criteria for experiments

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#143]
Following on from discussion in #25 we need to define what the minimum information criteria are for factor levels. Specifically we need to look at creating a factor level id, when and how this can be linked to ontology terms as well as how we deal with units. Initial thoughts attached in this excel document, which we could possibly expand using @richardostler's experience from [GLTEN](https://glten.org/)

[Minimum information for factor levels.xlsx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/8255171/Minimum.information.for.factor.levels.xlsx)

**Comment by paul121** [comment]
I believe this can be closed via #223
