### ISSUE TITLE
Add 'sensor' and 'water' assets to Rothamsted FarmOS instances

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#159]
I noticed the [demo site]([https://farmos-demo.rootedsolutions.io/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffarmos-demo.rootedsolutions.io%2F&data=04%7C01%7Caislinn.pearson%40rothamsted.ac.uk%7C275b9e02253c4adfaeac08da11a5548a%7Cb688362589414342b0e37b8cc8392f64%7C1%7C0%7C637841699022899099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7twlGXb%2FPzipDmkOdwZX5UKaAMCY7Fk6ECGSQxybO%2Fg%3D&reserved=0)) built by @paul121 and realised they would actually be extremely useful for our own farms - especially as we are in the process of creating a sensor network.

As an aside, I also wondered if the 'Seed' and 'material' assets might be the solution to our multiple harvest logs: we could continue to use the Harvest (Combine) quick form to create the harvest log but use the Harvest (Trailer/ Bale weights) quick form to create a seed/ material asset for the grain and straw? Links to #43 and #145

**Comment by paul121** [comment]
@mstenta does Aislinn have permission to enable these on the Rothamsted sites? Do we just need to show her how?

**Comment by mstenta** [comment]
She does! @aislinnpearson if you log in, click the Settings link in the top right, then the Modules tab, you'll see a list of modules you can enable. The Sensor and Water asset ones are in there.

Note: it's possible to enable modules via that form but it is NOT possible to disable them. So choose wisely. Feel free to spin up a demo farmOS instance if you're ever curious about one and want to try it out somewhere else first! Or just ask us. :-)

**Comment by aislinnpearson** [comment]
Done! Thanks both for picking up on it, I hadn't realised it was that simple!
