### ISSUE TITLE
Quick Forms: Add log category question to all experiment quick forms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#160]
Currently the 'Task' field on the task tab of the field operations quick form is a hard coded list which saves to the log notes in a standardised format (task: [selected field]). However, the farm team have asked if we could please convert this to a field which pulls from the Log Categories taxonomy. This has two benefits: (1) we can search and filter activity logs based on their task and (2) the different farms could amend this list so it only contains tasks relevant to that location. Had thinks this would also be preferable in terms of structuring the data for the NWFP database.

From the perspective of the NWFP database the list would look as follows:

![image](https://user-images.githubusercontent.com/16349781/161774684-fe6e814c-7348-43f3-8b5b-58f16233532e.png)

However, I am not sure if the secondary groupings ('Grass harvest', 'Grassland maintenance', 'Cultivations', 'Other') are strictly necessary, especially as different tasks may fit into different categories; for example 'topping' does not always relate to grassland maintenance under arable land management. I was also wondering if having three levels that might affect several aspects of the visualisation. Feedback welcome on this point.

In addition, the farm have made the point that the task list is usually based on the equipment, so ideally you'd have a reduced task list appearing deepening on which piece of equipment you choose (or vice versa a reduced list of equipment appearing depending on the task you choose). I've added that here so we can discuss options.

**Comment by paul121** [comment]
Hey my apologies @aislinnpearson I wasn't able to finish this over the weekend. I'll try to get it done this week but I'm going to be attending DrupalCon and will have limited hours. I think we might need to wait until next week to deploy this. Is that OK?

> Something else I thought of after we hung up is could we use this same field to replace the 'Group' allocation on the equipment assets? It seems to me like we might be introducing a bit of duplication there...

Good question, I'm glad you asked this. This issue would filter equipment by the their configured operation/task, but right now each quick form specifies which equipment group(s) to allow. I'm not very familiar with the list of equipment and task operations, but do you think we could use this across all quick forms? It might be nice to remove the concept of "Equipment groups" if each quick form could instead specify the relevant tasks/operations to filter equipment by.

Other than this everything seems pretty straightforward here so I think I have a clear path forward. let me know!

**Comment by aislinnpearson** [comment]
Hey @paul121,

To answer your question:

> I'm not very familiar with the list of equipment and task operations, but do you think we could use this across all quick forms? It might be nice to remove the concept of "Equipment groups" if each quick form could instead specify the relevant tasks/operations to filter equipment by.

In theory yes. This is what that list would look like this in the log categories:

![image](https://user-images.githubusercontent.com/16349781/166487981-8b91ba23-ad7a-4bda-8556-79f661d8d6e5.png)

Theoretically yes but it would get very complicated. For example, with drilling, there are different types of drilling methods which use different pieces of equipment but I don't think there is a word for the opposite of direct drilling, and even if there was people would argue about which bits of machinery go where. I have a similar problem for harvesting. Also, I don't think you can assign a category to an equipment asset? I feel a bit confused about this - something I'd like to talk through with @mstenta if we could.

**Comment by aislinnpearson** [comment]
Hi @paul121 

Following our weekly call today with the team at North Wyke they asked if we could please prioritise this issue as it is limiting their ability to extract data (several backlogged requests from some scientists). 

I've attached a list here of the log categories that would ideally appear on each quick form, as well as set up the structure on the North Wyke Instance:

https://northwyke.farmos.net/admin/structure/taxonomy/manage/log_category/overview

A couple quirks associated with this issue:

1. My suggestion is that we make a default 'Log Category' question on all of the quick form which allows you to **select multiple**. My suggestion is that we put it on the setup tab above the tractor, and then we can come back to filtering equipment based on the log category at a later date (this is a nice to have, rather than need to do and I'll create a separate issue for it: #273) 
2. On the trailer quick form this replaces the "Type of Harvest" question (terms should be identical)
3. For the field operations quick form this replaces the Task field, which we also use to generate the log name. Again, I have tried to keep the list of terms identical. This is also the only quick form where there are grandchildren terms, and I am not sure if that is a problem.
4. On the fertiliser and spraying quick forms this is in some ways a duplicate of the "product type" field but I can't see a simple way of replacing one with the other so again I suggest we raise a separate issue to look at this later. For now, I think we will just have to ask the farm team to select both.

Hopefully that covers everything. One for us to discuss on Friday. 

[List of FarmOS log categories.xlsx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9354517/List.of.FarmOS.log.categories.xlsx)

**Comment by paul121** [comment]
> Hopefully that covers everything. One for us to discuss on Friday.

Wow! Thanks for thinking of all the places we use log category, that is a big help. This all sounds good and makes sense. 

> 4. On the fertiliser and spraying quick forms this is in some ways a duplicate of the "product type" field but I can't see a simple way of replacing one with the other so again I suggest we raise a separate issue to look at this later. For now, I think we will just have to ask the farm team to select both.

Yeah, selecting both will be the easiest. This isn't a technical problem, we'll set the log category to be a combination of both of those questions.

**Comment by paul121** [comment]
@aislinnpearson I'm starting to work on this, it should be fairly easy. Two questions:

> On the trailer quick form this replaces the "Type of Harvest" question (terms should be identical)

Would you like the field's name to be "Log category" on all of the quick forms, or would be it be nice if it remained a bit more friendly like: "Type of harvest", "Task", etc...

I wonder, could we make this friendlier name be the name of the parent term in the hierarchy? For example, all of the harvest types would be under "Type of harvest" parent term. The main reason I ask is because right now these parent terms will be displayed as options elsewhere in farmOS, but I'd like to change farmOS core so that it always renders these options in the same hierarchy. If it did, I think "Type of harvest" or maybe simply "Harvest types" would make more sens than "Harvest log categories". See how this looks as a filter on the logs page:
 
![Screenshot from 2022-08-22 15-48-19](https://user-images.githubusercontent.com/3116995/186032113-d970c505-6f2a-4883-98b6-b057f904c9f6.png)

**Comment by aislinnpearson** [comment]
Hey Paul, 

So I think that "Log Category" on the quick forms works because it creates a definite link between what is on the quick form and the taxonomy we are using (through trial and error I've come to realise that this is the most user friendly option, especially when it comes to filling in a quick form but not knowing where to go to add a term to the taxonomy if it is missing from a quick form - a primary cause of delays and frustration!).

For the parent name in the parent hierarchy though I agree with you. If they are going into core (where it's always nice to contribute) let's stick with the conventions you are using there. Just let me know what terms you decide on so I can put them in our own documentation and also change the existing user accounts.

On which note, I have added you to the NW instance and will add you to the BB one now as well (sorry - I promised this on Friday and forgot)

**Comment by paul121** [comment]
> So I think that "Log Category" on the quick forms works because it creates a definite link between what is on the quick form and the taxonomy we are using (through trial and error I've come to realise that this is the most user friendly option, especially when it comes to filling in a quick form but not knowing where to go to fill in a form).

Great!

> For the parent name in the parent hierarchy though I agree with you. If they are going into core (where it's always nice to contribute) let's stick with the conventions you are using there.

Oh, just want to note, this hierarchy won't be going into farmOS core. The taxonomy hierarchies are always unique to each instance, so in essence we're developing a "convention" of the log category hierarchy that your instances will be following. What I was referring to about farmOS core is that the we display the taxonomy terms in various places but right now it doesn't show the terms *in the hierarchy*. Notice in that screenshot above you can see the hierarchy, but this is different than standard farmOS core right now.

Re: the actual parent term names, how about we change & shorten the names to be just "Drilling categories", "Spraying categories", "Operation categories", "Harvest categories", etc. I was thinking "Harvest types", "Spraying types", etc but given your comment above that "log category" is a useful descriptor, maybe we should go with that, however shortening it to remove "log" from each name.

**Comment by aislinnpearson** [comment]
> Oh, just want to note, this hierarchy won't be going into farmOS core. 

Ah. Yes. If I'd paused to think that would have been obvious!

Those parent term names sound good to me. I'll make sure I update the instances before we make it live.

**Comment by paul121** [comment]
Haha great! I'll try and wrap this up soon.

**Comment by paul121** [comment]
> On the fertiliser and spraying quick forms this is in some ways a duplicate of the "product type" field but I can't see a simple way of replacing one with the other so again I suggest we raise a separate issue to look at this later. For now, I think we will just have to ask the farm team to select both.

Ah an important distinction here is that the product types come from the `material_type` taxonomy. This is a special taxonomy because these terms are actually saved in a reference on `material` quantity types. So yes, we'll need to keep both of these questions for now. I see how you want the "parent" material_type terms to also be used at the log_category term.... but yes, for now these will need to be separate.

**Comment by paul121** [comment]
Okay here are changes I have made (just to double check we are on same page):

1. Added "Log category" field to all quick forms, they each look for a parent term of the format "Harvest categories", "Spraying categories", etc. This is required and allows multiple values to be selected. Saved to the `log.category` field.

> On the trailer quick form this replaces the "Type of Harvest" question (terms should be identical)
2. Done - I removed the "Type of harvest" question from trailer harvest quick form. This will pull from "Harvest categories" category.

> For the field operations quick form this replaces the Task field, which we also use to generate the log name. Again, I have tried to keep the list of terms identical.
3. I removed the "Task" field from the operations quick form. I updated code to generate the log name from the log category(s) that are selected (log name will be comma separated if multiple categories are selected)

>  This is also the only quick form where there are grandchildren terms, and I am not sure if that is a problem.
4. I slightly changed our select fields so that they display a hyphen(s) before child terms eg: `-Child 1`, `--Grand child`

**Comment by aislinnpearson** [comment]
Hi @paul121,

This all looks good to me. That point about the material type is important and something I had overlooked - thanks for pointing it out! 

A couple questions:

1. Can we add an update hook (is that what it's called?) converting all the previous log notes to log categories? I completely forgot about this, but I guess it is something we could do via the API afterwards. Might even be a nice excuse for me to get my head around the API...

2. 

> I slightly changed our select fields so that they display a hyphen(s) before child terms eg: -Child 1, --Grand child

Very happy with this, just wondering what the reason behind it is? In case I am missing something important...

Thanks so much again

**Comment by aislinnpearson** [comment]
Hey @paul121 

I'm just adding this to the Harpenden instance and the documentation. Could you send me an exact list of the parent terms? E.g. "Types of harvest", etc

Also, if you could send me a screen shot of what it looks like in the taxonomy I'd be grateful. Want to make sure I get the hyphens right. :)

**Comment by paul121** [comment]
> Can we add an update hook (is that what it's called?) converting all the previous log notes to log categories? I completely forgot about this, but I guess it is something we could do via the API afterwards. Might even be a nice excuse for me to get my head around the API...

Oh yes, good question. Yes we can. We'll need to wait until you have created the term hierarchies though. But we could deploy the update hook at anytime. Typically we do it the same time we make a change, but for this it might make sense to wait one release cycle for you to have the hierarchies ready. I think we may need to make sure we have a direct "mapping" of the old "operations" -> log category terms as well.

> Want to make sure I get the hyphens right. :)

Oh you don't need to add hyphens! The hyphens will just be added into the `select` field to make them more readable. Here is an example. The parent terms in this list are the exact terms I'm looking for. I create this hierarchy for my development environment:
![Screenshot from 2022-08-30 07-54-24](https://user-images.githubusercontent.com/3116995/187470188-5c0c995a-ba26-4461-8d78-4ef8d7287a1a.png)
