### ISSUE TITLE
Field formatter for the Plan treatment_factors field

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#162]
This would make it possible to read the treatment factors and factor level "metadata" on the Plan page (description, URI)

**Comment by paul121** [comment]
This would be pretty simple to add. I would propose we create a new collapsible fieldset  on the Plan page that contains all of the treatment factors, each on its own line (ohh perhaps we could even render a table with this information?? that could be easy as well!)

**Comment by paul121** [comment]
Some treatment factors have many levels, tables are working great to display this.

![Screenshot from 2022-05-27 12-49-26](https://user-images.githubusercontent.com/3116995/170780343-1e268aa7-66ab-46e9-8a4e-d2f8a371b9e5.png)
![Screenshot from 2022-05-27 12-49-07](https://user-images.githubusercontent.com/3116995/170780347-a0dce1db-8066-4740-acb8-399f344684fd.png)

**Comment by aislinnpearson** [comment]
Thanks @paul121. Looking at it makes me think how great it will be to have semantic annotation for the factor levels, but that is proving harder than expected and will have to come later. For now, this looks great. Thank you.
