### ISSUE TITLE
Make 'products applied' optional in Drilling and Harvest Quick Forms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#165]
Our two farm managers have asked if the 'Product Type', 'Product' and 'Product Rate' under the 'Products Applied' tab could be made optional on the **Drilling** and **Harvest (Trailer/ Bale Weights)** quick forms only (they should remain required fields on the Fertiliser and Spraying Quick Forms).

**Comment by paul121** [comment]
> To create a short term work around solution I have added "Product Type = None" and "Product = na" to the taxonomy. There are a couple logs that will have this. I am happy to change this manually once the amendment is live on FarmOS.

This is done but still needs to be deployed and have the old logs manually updated.

**Comment by paul121** [comment]
@aislinnpearson this has been deployed to rothamsted.farmos.net. I see the .dev site does not have this though (@mstenta maybe we can update that soon too?)

**Comment by aislinnpearson** [comment]
Thanks @paul121  - I've just double checked this on the Harpenden and North Wyke sites and it looks good. Happy for you to close the issue @mstenta once it is also on the .dev site. :)

**Comment by mstenta** [comment]
Based on our conversation today, I think we can close this. We are going to start using Platform.sh for the dev site, instead of rothamstedfarm.farmos.dev.
