### ISSUE TITLE
Add plot fields and update experiment plots view

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#166]
Following extensive discussion with our Statistics team, we realised we need to make some changes to the CSV uploader.

**Columns to be removed:**

Please can the following two columns be removed from the 'Plots' view on the experiment module, as well as the search terms: 

1. Crop
2. Block

NB. I think these are currently specified as required fields in the GeoJSON uploader, but in reality they are not required data fields in most experiments. Instead they should be added when necessary to either explain the statistical design or treatment structure. I will also remove them from the list of required fields in the CSV templates.

**Columns to be added:**

Please can we add the following columns to the CSV uploader:

1. serial: a numeric integer which is unique to each plot. This is pre-fixed with an underscore to ensure the leading zeros aren't removed when opening the CSV files in Excel
2. type: this is a category which describes the type of plot. We will probably expand this list but currently it includes guard_plot (plots which are drilled to prevent cross pollination), discard_plot (plots which are discarded at harvest), treated_plot (plots where a treatment is applied), and blank (previously called dummy plots, these plots don't actually exist on the ground but are used by Grassroots for drawing layouts)

Of these two, only 'type' needs to be visualised as a column name and should also be added to the list of search terms.

**Comment by paul121** [comment]
**Re: Crop and Block fields..**

> NB. I think these are currently specified as required fields in the GeoJSON uploader, but in reality they are not required data fields in most experiments. Instead they should be added when necessary to either explain the statistical design or treatment structure. I will also remove them from the list of required fields in the CSV templates.

Yep, the `block` field is already optional. And we actually don't support uploading the `crop` in the CSV importer right now. This worked in the previous geojson uploader but we did not carry the feature over to the CSV uploader. I've removed both of these from the Experiment plots tab view.

**Re: Serial and type fields...**

Can I request that we name the `type` field `plot_type` ? The `type` field is already being used in farmOS for the asset `type` (plot). For consistency it would be good if the CSV used the same.

> We agreed that for the sake of consistency the serial for every experiment would start at 1 and also that the serial, row and column numbers must be an integer. 

The example geojson serial starts at `0`. Is this OK? Would you like us to add some validation to the uploader to enforce that it always starts at 1? Also, the geojson file has a `Serial` property; could we make this lowercase for consistency: `serial` ?

> I have attached a new set of sample files here:

@aislinnpearson this is missing the plot assignments csv. I've modified the existing LSRE plot assignments I had with some mock `serial` and `plot_type` columns to use for testing as I described above. Attaching for reference, but please test with your full datasets!

[plot_assignments.csv](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/8605684/plot_assignments.csv)

**Comment by paul121** [comment]
> By contrast the stats_row and stats_column which describe the statistical design can be decimals (as is the case in Broadbalk) or alphanumeric if required.

@aislinnpearson I believe we decided to not include these `stats_row` and `stats_column` fields yet. So right now we only have `row` and `column` which must be integers. Is that correct?

**Comment by aislinnpearson** [comment]
HI @paul121 

To answer your questions:

> Can I request that we name the type field plot_type ? The type field is already being used in farmOS for the asset type (plot). For consistency it would be good if the CSV used the same.

Yup. Absolutely fine

> The example geojson serial starts at 0. Is this OK? Would you like us to add some validation to the uploader to enforce that it always starts at 1? Also, the geojson file has a Serial property; could we make this lowercase for consistency: serial ?

Yes, please add validation to start at 1. Apologies about my typo for serial - it should definitely be a lowercase s. 

> @aislinnpearson this is missing the plot assignments csv. I've modified the existing LSRE plot assignments I had with some mock serial and plot_type columns to use for testing as I described above. Attaching for reference, but please test with your full datasets!

Apologies. For future a test dataset here with the changes you requested: 
[example_v2.0.3.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/8611466/example_v2.0.3.zip)

> @aislinnpearson I believe we decided to not include these stats_row and stats_column fields yet. So right now we only have row and column which must be integers. Is that correct?

Yes, that is correct. The stats_row and stats_column are features of the statistical design and so a part of the analysis structure in some experiments (not all). For this reason we will add them as treatment factors in the short term, and find a more long term solution over the next 6 months - a year.

**Comment by aislinnpearson** [comment]
HI @paul121,

I just double checked the new version of the experiment upload into the platformsh site and got the following error message (I think it repeats for each plot):

![image](https://user-images.githubusercontent.com/16349781/166651633-9d56f9aa-318d-4d28-ac86-3b0329163429.png)

The plots did upload, but the first plot (H01) is replicated several times over. I noticed that there are two 'plan' tabs on the right hand side and in each one the plans are labelled differently. I tried uploading to both but got the same error message and the same outcome for each:

https://1-x-experiment-zghz3wa-2mu45anerqtvq.uk-1.platformsh.site/plan/3/plots
https://1-x-experiment-zghz3wa-2mu45anerqtvq.uk-1.platformsh.site/plan/2/plots

Here are the files I tried to upload:
[example_v2.1.0.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/8618996/example_v2.1.0.zip)

**Comment by paul121** [comment]
> The plots did upload, but the first plot (H01) is replicated several times over.

Oops, okay just fixed this. I was still depending on the `plot_id` being in the geojson file but I see your latest data set does not include this, which makes sense.

> I noticed that there are two 'plan' tabs on the right hand side and in each one the plans are labelled differently. 

I noticed this as well.. It should be fixed now :+1:

**Comment by paul121** [comment]
I'll leave this open until it has been reviewed!

**Comment by aislinnpearson** [comment]
Hi @paul121,

This looks amazing - especially as you can filter by plot_type. The only comment I'd have is that the list of plot types would be limited to those in the document rather than hard coded, just to give us a bit more flexibility. Happy to sign that off on this though and create a new issue for that change (see #180)
