### ISSUE TITLE
Bug: plots not displaying correctly on page 2

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#167]
While uploading a few trials to the .dev site I noticed that if there is more than one page of experimental plots, you cannot click on the icon for page two, it produces the error 'an illegal choice has been detected' (see below). However, if you ask to view all items per page then all the uploaded plots are present in the list.

![image](https://user-images.githubusercontent.com/16349781/164053192-9aa21aa4-272e-4f68-9346-f8fe1b8fea89.png)

**Comment by paul121** [comment]
I believe I found the bug causing this. Will be included with the updated plot fields in the next release.
