### ISSUE TITLE
Searching for all logs associated with an experiment

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#170]
Hi @mstenta, @paul121,

I noticed when submitting the test experiments on the .dev site that I can easily search for logs associated with a single plot using logs-> search [asset name] but this doesn't apply if you are trying to find _all_ the logs associated with an experiment. I also tried searching by experiment name but got no results (it wasn't recognised). 

Two thoughts on this:

1. Is there a way to search and display all logs associated with a plan and perhaps I just haven't noticed it?
2. Ideally we would have a tab on each plan that can be used to quickly access the logs associated with a specific plan (sort of like the below)

![image](https://user-images.githubusercontent.com/16349781/164247342-cbcf1abc-7db2-420a-9adc-5f2b072c7fd8.png)

Not sure what is/ isn't possible so one to discuss next week when triaging the issues.

**Comment by aislinnpearson** [comment]
In the meeting on the 10 May 2022 we agreed that the solution for this would be to add a 'Logs' tab to the individual experiment.

**Comment by paul121** [comment]
@aislinnpearson this would be pretty quick to add, I might start working on it if I have time in the next few days.
