### ISSUE TITLE
Spraying Quick form: update wind direction description

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#171]
On the spraying quick form I noticed I specified the choice of directions as:

North
South
East 
West
...

With the description: "The dominant wind direction during spraying."

However, I realised what isn't clear is that, unless you know otherwise, wind direction is given in terms of where it is coming from rather than where it is going to. Perhaps I am being pedantic here but could we please change the list of options so they read:

From the North
From the South
From the East
From the West
From the North East
From the South East
From the North West
From the South West

And also update the description so it reads "The dominant wind direction during spraying. Please select the general direction the wind is coming from."

**Comment by aislinnpearson** [comment]
Following discussion on 03 May 2022: Changing the options for wind direction has knock on effects for previous data (i.e. existing records would be 'North' when new records would be 'from the North'). For this reason we agreed that we would leave the options the same and just clarify the question description, and also make sure the users of the quick form are all aware that it is the direction that the wind is coming from.

**Comment by paul121** [comment]
>  For this reason we agreed that we would leave the options the same and just clarify the question description, and also make sure the users of the quick form are all aware that it is the direction that the wind is coming from.

If we are indeed only changing the question description, this is quite trivial!
