### ISSUE TITLE
Support creating commercial assets with multiple locations

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#179]
Currently the quick form lets you specify multiple locations into the Field/location `entity_autocomplete` form field. But upon submission only the last auto-completed asset is used.

Notably we currently have this field configured to only accept one value (`#tags => FALSE`, the default value). I believe that was the functionality in v1 but we can change this to true and accept multiple locations!

The fact that we have `#tags => FALSE` and the UI lets you enter multiple assets is weird. I think it is actually this Drupal core issue: https://www.drupal.org/project/drupal/issues/2692289

**Comment by aislinnpearson** [comment]
HI @paul121,

Again, not one I could double check on the platformish site but happy to chat it through this evening, and assume all is working as it should be. Maybe just double check I understood everything correctly this evening in the call, before I move to @mstenta.
