### ISSUE TITLE
Experiment Module: Filter plot_type based on levels within the CSV 

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#180]
Following on from #166, the plot type filter on the plots tab of the experiment module would ideally filter based on the list of values within the CSV (currently I think it is hard coded?)

The reason for this is two-fold:
1. I don't think we have formally agreed on the final list of terms to come under plot type. For example, I think 'treated_plot' should actually be 'whole_plot' or 'sub_plot' based on the experiment design.
2. We might want to add levels to this in future, and that gives us the flexibility without having to hard code it in.

**Comment by paul121** [comment]
The simplest implementation may be to use a views alter hook to modify the available options.

Could also create a custom views filter plugin that contains this logic itself. This might be a bit more work but perhaps more maintainable & isolated code than the views hook.

**Comment by paul121** [comment]
Hey @aislinnpearson I apologize I missed an important aspect of your request: the distinction between hard-coding plot_type levels and also reading the values from CSV.

These values are indeed hard-coded right now to the original ones in #166 When these are hard-coded we can define a mapping of the machine name to the labels:

```
         'allowed_values' => [
          'guard_plot' => $this->t('Guard plot'),
          'discard_plot' => $this->t('Discard plot'),
          'treated_plot' => $this->t('Treated plot'),
          'blank_plot' => $this->t('Blank plot'),
        ],
 ```
 
The complication with allowing *any* plot_type value is that both the machine name and label need to be provided. A good example of how we already do this is the treatment_factor and treatment_factor_levels: the experiment plan defines the mapping between machine name to label, description, URL, etc, and the plots simply specify a machine name. To allow *any* plot_type value we would need to do something similar.

Maybe another thing for us both to learn from this: "expanding the (hard-coded) list" and "allowing any value" don't mean the same thing!

**Comment by paul121** [comment]
> the plot type filter on the plots tab of the experiment module would ideally filter based on the list of values within the CSV (currently I think it is hard coded?)

Filtering the values shown within the Plots filter is another aspect of this. As I commented to above this should be fairly easy, and would be needed for both use-cases: expanding the list & allowing any values.

I'm going to continue on with adjusting the filter values but for now I would recommend that we stick to the hard-coded list of plot_type values. These are easy to change on our end, but I do understand that the human process is harder on your end. It's also worth noting that we can change & update these later on in a programmatic way if you. For example, if you wanted to change `Treated plot` to `Whole plot` after an experiment is created we can help with this.

**Comment by aislinnpearson** [comment]
Hi @paul121,

> I'm going to continue on with adjusting the filter values but for now I would recommend that we stick to the hard-coded list of plot_type values.

That's fine. The one additional plot_type that we will need to the list in that case is an observtation_plot (this is a plot included in a experiment to simply see what would happen - it can't be used in the analysis as it is not part of the statistical design) and we might also want to expand that list again in future.

For context, we are having quite a long internal discussion about what that list of plot_types needs to be and how to implement them. Below is the full list from my colleague Andrew Riche but he and I disagree on the implementation to some extent. I think some of the plot_types listed below should actually be flags:

Andrew Riche's list of plot types:
-	**normal** (or what we currently call a treated_plot)
-	**guard_plot**
-	**observation_plot**
-	**blank**
-	**discard** (a plot where an error occurred so all the data should be discarded. I think this should be a flag attached to the plot, not a plot type)
-	**partial_discard** (a plot where an error occurred. Data from before this error can be used, but data after this error cannot be used. For this reason you’d also need to capture the date after which the plot was discarded. Again I think this is a flag type)
-	**missing** (I think this is a flag type)
-	**substituted** (including a record of what the substitution is, I think this is a flag type)
-	**swapped** (including a record applied to all the plots involved in that swap)
