### ISSUE TITLE
Visualisation: Hide quantities from Logs view

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#184]
When looking at the logs assigned to an asset, one of the farm team asked if we could please hide the quantities field from the list of displayed fields. The rationale behind this is that, because there are lots of quantities associated with the logs (especially for the logs created via the Spraying quick forms, see below) you can only see 1-2 logs on the screen at a time. Bruce thinks it would be preferable to see a longer list of 10-15 logs, which you can then click on to see the details of what was applied and in what quantities

![image](https://user-images.githubusercontent.com/16349781/167622571-a99a63ad-b347-4e41-a12b-c7bf4fec4718.png)

**Comment by aislinnpearson** [comment]
In the call on 10 May 2022 we agreed that this is easy to fix but, because it is part of the core module, would be a Rothamsted specific fix which makes it difficult to manage.

Instead, we agreed we would look into a "click to view more" option in the Rothamsted instance which, if it works, can be moved into the core module.

**Comment by mstenta** [comment]
Oh forgot this issue was here! We changed the way this works in farmOS core so that only the first quantity is displayed in the log lists. Clicking through to the log shows all the quantities.

https://github.com/farmOS/farmOS/pull/619

**Comment by aislinnpearson** [comment]
Awesome! Thank you @mstenta - I will let Josh at North Wyke know. He will be thrilled. :)
