### ISSUE TITLE
Assign commercial plant asset location via drilling logs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#185]
Commercial crop assets aren't an inherent location in and of themselves, but they have locations at multiple time points:

Planning: assigned a theoretical location
Drilling: the crop is drilled in a specific location (maybe on more than one occasion if it needs reseeding or is a mix of more than one crop species)
Harvest: Moved to the grain store

In addition to the asset having a location, there needs to be a record of where the activity occurred (for example the spraying occurred field x). This is important because in addition to keeping a history of how the activities relate to a specific asset which only spans (for example) one season, you also need a field history which spans multiple years.

Currently we get around this issue by assigning a movement log when the asset is created but this means you can't search assets by location as per issue #172 

An additional level of complexity here is that the quick forms are used for the experiments _and_ commercial assets, and although the commercial assets don't have a fixed geometry/ location, the plot assets do. For this reason the solution differs for the plot and plant assets.

@paul121 and @mstenta I'm going to leave you to describe the technical solution we came up with if that is okay - I had it when we were talking, but I don't have it clear enough in head now to write it down. It got very complicated. But the issue is now created as promised :)

**Comment by mstenta** [comment]
Summary of technical solution:

- Do not create an Activity log when the Commercial quick form is submitted.
- Add a "Location" field to the Drilling quick form, which is only required for Plant assets.
    - Add a description to this field explaining that it is not necessary for Plot assets.
    - Add form validation logic to ensure that this is filled in when Plant assets are referenced. Do not allow BOTH plant and plot assets to be referenced (I think?)
    - Add the location to the drilling log and mark it as a movement ONLY when plant assets are referenced.

**Comment by paul121** [comment]
@aislinnpearson I'll have a preview link for you later today. Attached is a screenshot of the description - does this look okay? I have added validation to ensure that this is provided when drilling plant assets, but not plot assets.

![Screenshot from 2022-05-19 12-19-59](https://user-images.githubusercontent.com/3116995/169385887-b309152a-0915-4d3b-bf68-32327bcae246.png)

**Comment by paul121** [comment]
We discussed this more today and decided to not implement what was planned with this issue.

A large reason is that a commercial plant asset may need to having inputs (spraying, ferilizer) or activities (operations, cultivation, etc) before the field is drilled. It is important that these input & activity logs reference both the plant and the location that they are happening in. For this reason we *should* continue assigning the plant asset's location via the commercial asset quick form.

As a follow up we would like to add a button or field that makes it easier to change an assets location without needing to create a movement log from scratch (this is what the farm team was used to in v1)

**Comment by paul121** [comment]
To preserve this history & work done I have reverted the merge commit that added this functionality: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/pull/191/commits/9573bac6269f0e25e544f79a266161c2a10653fa

There is some validation logic in particular that may be valuable in the future.

**Comment by mstenta** [comment]
This still feels weird to me (because the plant does NOT exist in the location, and I worry that it might cause confusion in other contexts to show that it IS there), but I understand the confusion, so I won't push back on it. :-)

Thinking more broadly (perhaps longer term), it makes me wonder if the "right" solution would be to have better visibility of "future plants in a location". The root issue seems to be one of visibility - needing to find a future asset before it's been drilled so it can be referenced. If a plant is "planned" (eg: it has a *FUTURE* log to drill it), then that plant could be made visible in a way that makes it easier to reference.

That's perhaps a bigger task, but just wanted to get these ideas out somewhere. :-)
