### ISSUE TITLE
Change product application rate units to use Volume per unit area units

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#189]
Hi @mstenta, @paul121,

Bruce would like to add 'litres per tonne' (l/t) to 'Volume per unit area' in the Units taxonomy so it appears in the quick forms under 'Products applied' (Spraying, Drilling and Harvest quick forms). It can be added to the taxonomy easily enough, but then doesn't appear in the quick forms.

I have double checked this in the platformish site, and the term names match exactly with what you have there @paul121. Of course I may be missing something but I wondered if this might be a similar issue to the one we were having with the units for the bale weights (#186)?

**Comment by paul121** [comment]
Currently the product application rate units are hard-coded with the following:

```php
        // Product application rate.
        $rate_units = [
          'ml/ha' => 'ml/ha',
          'l/ha' => 'l/ha',
          'g/ha' => 'g/ha',
          'kg/ha' => 'kg/ha',
          't/ha' => 't/ha',
        ];
```

Today we decided to change these so they are pulled from the "Volume per unit area" hierarchy in the units taxonomy. This same hierarchy is used for the fertiliser target application rate units.

@aislinnpearson I forgot to mention this means the existing options will disappear unless they are added to the hierarchy. This might be obvious but just wanted to make sure you are aware. We'll need to make sure all sites are ready with this hierarchy!

**Comment by aislinnpearson** [comment]
Yup. I double checked that this morning - they are all there. :)
