### ISSUE TITLE
Experiment Module: Change 'treatment_factors' to 'column_descriptors'

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#190]
Following a discussion with the Stats team, we realised the terms for some of the experiment descriptors are wrong. Specifically what we have been calling 'experiment_factors' are really 'column_descriptors'. 

These need to be changed in the CSV upload files, which might affect the way they are uploaded into FarmOS, but probably after a conversation with the grassroots team.

Ideally we would also come up with a better naming convention for factor levels such as 'column_levels' as not everything is necessarily a factor.

**Comment by aislinnpearson** [comment]
Column definitions
Element descriptions/ Feature descriptions/ Component descriptions/ Component characteristics
Plot attributes

**Comment by aislinnpearson** [comment]
Hey @paul121 

To follow on from the e-mail discussion about this:

> I guess it just isn't very clear what all we want to change here. It would be simple to only change the column names in the CSV files but I assume we want to change "Treatment factors" to be "Column descriptors" in the farmOS UI as well - this is where it gets complicated and is just more things to change.

So ideally we would change the treatment factors to be column descriptors in the FarmOS UI as well, but I understand that includes a lot of awkward changes your end. I actually think that several of the names we have used are incorrect - for example, factor levels are often actually just column levels. It's something that @richardostler and I had a long discussion about on Friday without coming to any real conclusions - Richard sees these upload files as being used to represent treatments, but my opinion is that we use these uploads for reasons that extend beyond treatments and often includes management information. This flexibility has enabled me to get almost every experiment into FarmOS, while also annotating almost everything with an ontology term so I think we should keep the structure flexible and generic, but change the naming conventions to reflect this.*

The important thing to say though is that whatever names we use, it doesn't restrict us from using the experiment uploader, so if this is a lot of code to change we can leave it for the time being, especially as we are still debating the issue.

*As an aside, Richard and I agree that part of the complexity here is using a CSV to do the uploads (which limits us to a sort of 2D structure) and then converting that CSV into JSON. I think there are justifiable reasons for this (CSVs are widely understood and actually a bit easier to make) but weirdly this simplicity adds a level of complexity. :)

**Comment by paul121** [comment]
> The important thing to say though is that whatever names we use, it doesn't restrict us from using the experiment uploader, so if this is a lot of code to change we can leave it for the time being, especially as we are still debating the issue.

I would say this is "medium effort" to change the related code. And given that we are still debating I think we should wait. Notably we do have two database json fields that use this naming convention: `experiment.treatment_factors` and `plot.treatment_factors` but migrating these to a new field name wouldn't be too hard. Depending on what changes we might need to update some key names in that json as well, but again not very hard.

> *As an aside, Richard and I agree that part of the complexity here is using a CSV to do the uploads (which limits us to a sort of 2D structure) and then converting that CSV into JSON. I think there are justifiable reasons for this (CSVs are widely understood and actually a bit easier to make) but weirdly this simplicity adds a level of complexity. :)

Yea this is interesting! We should consider any changes to this process at the same time we change naming. We could certainly do 1 or 2 JSON imports (the plots geodata might always need to be in its own file) if you are able to prepare them elsewhere.

**Comment by paul121** [comment]
In the meantime we *could* simply rename Treatment factors to be "Column descriptors" in the UI, but not change the backend code. I think the treatment factors terminology is only going to be used once we add #162

**Comment by paul121** [comment]
Also some related issues:

#3
#143
#172

**Comment by aislinnpearson** [comment]
Hi @paul121,

> I would say this is "medium effort" to change the related code. And given that we are still debating I think we should wait

I agree with you. Let's leave the current structure and call it version 1. I'll document it and we can use it as a minimum information criteria for now and save the bigger changes for version 2 of the experiment module. 

To that end, I will remove this from the live issues feed and tag it with 'Experiment Module 2.0' so we don't lose track of it.

**Comment by aislinnpearson** [comment]
This will be resolved in #223
