### ISSUE TITLE
Harvest Quick Form: Add quantity for digitally recorded yields

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#193]
The North Wyke team have had a chance to test the harvest forms they think they work really well for the farm platform yields where they need to weigh every trailer. This is really great feedback as I had quite a few reservations about the new harvest quick forms but from a user perspective they work well enough for that use case (with the caveat that they could be improved further once we develop the draft quick forms in #95 and resolve the issue around adding multiple trailer loads to the same quick form, similar in nature to the issue in #82).

In order to adapt the Harvest (Combine and Forage Harvesters) quick form to commercial grass harvests Bruce has asked if we could please add a quantity field to the harvest data tab that captures the yield estimate produced by the combine or forage harvester. This is really a yield estimate and could easily be wrong if the combine hasn't been calibrated properly, unlike the trailer and bale weights which physically weigh the offtake. I'm not entirely sure what to call this data field (digital yield? forage/ combine harvester yield estimate? Machine recorded yield?) but Had asked that we please standardise it so that it is easily accessible through the API.

**Comment by paul121** [comment]
>  I'm not entirely sure what to call this data field (digital yield? forage/ combine harvester yield estimate? Machine recorded yield?) but Had asked that we please standardise it so that it is easily accessible through the API.

I like the idea of "Yield estimate" - this seems fairly standardized and in the context of the combine harvest log can be assumed that this came from the digital (maybe sometimes analog?) readout from the harvester.

@aislinnpearson I kept the units the same as the trailer weights (tonnes and kilogrammes) - let me know if you need something different.

Harvest logs with a "Yield estimate" quantity can be requested from the API like this:
https://rothamsted.ddev.site/api/log/harvest?filter[quantity.label]=Yield%20estimate

Here is a screenshot of the Yield estimate quantity in the Harvest Data tab:

![Screenshot from 2022-06-16 12-50-16](https://user-images.githubusercontent.com/3116995/174152696-76820953-ed47-4bc0-a61a-2c1030b1dff4.png)

**Comment by paul121** [comment]
Chatting today - lets change this label to "Machine yield estimate".
