### ISSUE TITLE
Taxonomy: add quantities to Taxonomy terms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#194]
A request to please add quantities to Taxonomy tems. 

Specifically this was requested in order to capture the nutrient ratios in different fertiliser products but would also have broad applicability to pesticide products and other materials used on the farm. Ideally it would reference the units taxonomy to help standardise it. I don't know how we would standardise the naming of the nutrients (Nitrogen, Potassium, etc) or active ingredients in the pesticides (Imidacloprid, etc).

This partially resolves #65 with the exception of a calculator

I am not sure about the use case for this in other taxonomies, I'm open to ideas on whether or not we do this for all taxonomies or just the material taxonomy. As we are adding terms to the taxonomy, I also wonder if it is worth adding a url field specifically for ontology terms - something we can discuss this evening.

Duplicate issues: #194

**Comment by paul121** [comment]
Generally we don't want to the normal "log quantities" to taxonomy terms.

Instead, we should identify what specific "quantities" we need (NPK rates, %, etc) and either add dedicated fields OR implement a key/value solution to let this be more dynamic.
