### ISSUE TITLE
Harvest Quick Form: Adding multiple trailer weights in each trailer harvest record

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#203]
Following my fortnightly call with the farm team this morning, Bruce told me they have now finished their first grass harvest and although the Harvest (trailer/ bale weights) quick form works really well and captures everything they need for the Farm Platform, it takes a long time to fill in: his estimate was 35 - 45 minutes extra per field for 7 -10 trailer loads (circa 5 minutes per form). 

Until we are able to create multiple harvest logs from the same quick form (see discussion here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/82) Bruce accepts this for the Farm Platform work where that resolution of data is necessary for scientific purposes, where we need to know the individual trailer weights as well as the tractor hours and fuel associated with each load. However, it isn't worth the effort for grass harvests on the commercial fields where he will just use the combine/ forage Harvest Quick Form and give a digital estimate of yield based on the combine records (#193).

This works at North Wyke, where there is no need to record the individual trailer weights for grass harvests, but it will be a nightmare for the commercial arable harvest at Harpenden (wheat, oilseed rape, barley, etc) where we are required to collect yield and moisture content for the grain as it is entering the storage barn for the [Red Tractor audits.](https://redtractorassurance.org.uk/wp-content/uploads/2022/04/Crops-SA.pdf) (Requirements T1.4 Key and ST.2 key). **Harvest is the busiest time of year on the farm, so we need to come up with a better system for the arable harvest before the end of July or I will be incredibly unpopular.**

The ideal solution would be to add multiple trailer weights to harvest (trailer/ bale weights) quick form which is how it was initially specified. However, we removed this functionality for the following two reasons:

1. The complexity of recording multiple quantities for each trailer load (each trailer load needs to have a weight associated with it as well as moisture content)
2. There is no way to save a draft quick form, which is essential if you are using the same form for multiple loads (#95) and don't want to run the risk of losing the information you have already entered.

**Comment by aislinnpearson** [comment]
We discussed this further in the call on the 07 June 2022 and made the following points:

1. The current form saves as multiple harvest logs, one for each trailer load
2. How would the form work if there were multiple trailer drivers?
3. That there are two steps to this process (1) saving a reloading a quick form that has not been completed (#95) and (2) cloning a quick form which pulls information from a previous record (#82). Issues 95 and 82 both have to be addressed, but 82 (reloading a quick form) is easier to implement given the current code base. Saving draft quick forms (95) has significantly less existing development behind it.
4. For this reason there are two ways of doing this. One is to have a single record for each trailer, the other is to add all the weights for a specific trailer to a single harvest record (in which case you would have two harvest logs if there were two separate trailer drivers). Although there will then be multiple quantities associated with each log (as many as 30 - 60 depending on the crop) these would be hidden when issue #184 is resolved.
5. It would be great to be able to add up and visualise the total number of trailer loads at the bottom of the harvest quick form, so you can see the total volume harvested.
6. The combine/ harvester quick form would ideally be saved as an activity log, so that harvest logs only reflected data captured in the trailer/ bale weights quick form. See issue #210.

Based on this conversation we agreed that we would start by creating the ability to reloading (cloning) a quick form which then _requires_ certain additional fields. To this end I have specified the changes in 82 which state how to select a previous record, and then created a new issue (#209) for the harvest (trailer and bale weights) quick form which specifies which required data fields need to be overwritten/ replaced. This would submit multiple logs for each trailer.

However, after thinking it through further yesterday, I am still not convinced that this is the best implementation for the harvest quick form (perfect for drilling, cultivation and spraying which are sometimes spread over multiple days but not ideal for trailer loads, which is a task associated with a lot of time pressure). For this reason I would like to cover all bases and still include an 'add multiple' option for the trailer loads (this issue). In the worst case scenario, records can be recorded on paper and then entered later.

The 'add trailer' option would include three quantities:
1. Number of bales on the trailer (optional)
2. Gross weight (required; units are kg or t)
3. Moisture content (optional, unit is %)

The fields 'trailer tare' and 'grain sample number' would be unique for each record and not repeated. I've attached a paper copy of the form here for reference: [FarmOS HARVEST (TRAILER AND BALE WEIGHTS) QUICK FORM.docx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/8869734/FarmOS.HARVEST.TRAILER.AND.BALE.WEIGHTS.QUICK.FORM.docx)

My thinking is that this way, we can give the farm team the option to do what works best for them at harvest (without adding to the time pressure they are under at harvest) and then revisit any new issues which arise after harvest if we need to. Either way the development work will be very relevant to other quick forms.

**Comment by paul121** [comment]
> The 'add trailer' option would include three quantities:
Number of bales on the trailer (optional)
Gross weight (required; units are kg or t)
Moisture content (optional, unit is %)

Hey @aislinnpearson a couple questions here. First, I want to ask about the "Nett weight" quantity. Since this is not included for each trailer, I'm assuming the "Nett weight" would represent the total of all trailers included in the submission?

Second, I'm curious if we should identify each quantity with the trailer number. If we were only submitting multiple "Gross weight" or "Number of bales" quantities this might not be so important, but because we have "Moisture content" it seems that it could be important to associate this with each trailer load? This means each quantity label would become more complicated like "Trailer 1 Gross weight".

> Although there will then be multiple quantities associated with each log (as many as 30 - 60 depending on the crop) these would be hidden when issue https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/184 is resolved.

It's true that we can hide a long list of quantities, but adding complexity to these quantity labels makes it harder to work with these quantities programmatically (via the API or when building reports). Since we might be less concerned with summing the Gross weights as compared to the Nett weights this might be less of an issue, but it's something I want to point out.

What do you think?

**Comment by paul121** [comment]
Chatting today:
- Nett weight can be removed from the UI and computed when the form is submitted, we will always have a single Nett weight quantity.
- Mositure content isn't always associated with each trailer load. Importantly, we need to record the time the moisture content was taken. We can save this as a single quantity on the harvest log and include the time (date is already captured on the log). eg: "Moisture content 10:15: 7.5%"

- Number of bales on trailer: move under the weight fields. @aislinnpearson will reach out to see if we can remove this quantity from each trailer and instead capture a single "total number of bales" for each quick form.

**Comment by aislinnpearson** [comment]
Hi @paul121 

Sorry to be slow. Bruce is on holiday this week, but Josh kindly helped me answer this question.

> Nett weight can be removed from the UI and computed when the form is submitted, we will always have a single Nett weight quantity.

I'm afraid I got this wrong - it turns out that the weighbridge at North Wyke is much more sophisticated that the ones at Harpenden or Brooms Barn, and automatically calculates Nett Weight (where as the ones here only do Gross Weight). Can we make the label associated with this quantity a choice between the two, so they can record whatever the weighbridge gives them?

> Number of bales on trailer: move under the weight fields. @aislinnpearson will reach out to see if we can remove this quantity from each trailer and instead capture a single "total number of bales" for each quick form.

Josh told me the 'Number of bales per trailer' data field can be deleted all together - as long as they know the total number of bales from a field, and can calculate the total weight, the number of bales per trailer that is probably a sufficient level of detail. If they did want this level of detail, they could resubmit the form multiple times, but this is likely to be an edge case.

Let me know if that makes sense. :)

**Comment by paul121** [comment]
> Can we make the label associated with this quantity a choice between the two, so they can record whatever the weighbridge gives them?

Great idea! This was an easy add.

> Josh told me the 'Number of bales per trailer' data field can be deleted all together 

Done.

@aislinnpearson here's what this ends up looking like. You can select multiple trailer loads (defaults to 1). Each trailer can have a Gross or Nett weight, and each of these is saved as a "Trailer X Gross/Nett weight" quantity in the submission. A final "Nett weight" quantity is computed as the sum of all Nett and (Gross - Tare) weights. I've added validation logic to ensure that all the weights have the same units as well as ensuring the Tare is less than each gross weight.

I've also added the Moisture content time option. Let me know if you would like to change the form label or description on any of these.

![multiple_trailer_weights](https://user-images.githubusercontent.com/3116995/177428964-5ad80a2e-1420-4519-b35e-2ffca3496078.png)

![example_submission](https://user-images.githubusercontent.com/3116995/177429651-1d902682-957f-43fc-a1e0-f39435d52353.png)

**Comment by aislinnpearson** [comment]
This looks great @Paul. The only thing I'd ask is if we can move 'Trailer Tare' to the top of the form as it's the first thing they'd measure. Thanks so much for all this!

**Comment by paul121** [comment]
Done.
