### ISSUE TITLE
Experiment Module: Update plot type options

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#205]
Please can we add the following to `plot_type`

**1. residual_effect:** the original treatments are no longer applied but there are residual effects of treatments applied in previous years, which may or may not constitute a part of the experiment design. This is used regularly in the long term experiments, especially where the nutrient treatments have been amended over time.
**2. observation_plot:** a plot which is not a part of the statistical design but which is being monitored. Examples include 'look see' plots where a new treatment or management attribute is being tested before being incorporated into a later experiment, or where an error has occurred and the plot can no longer be analysed as part of the experiment but still has observational value.
**3. discontinued:** plots in a multi-year or multi-season experiment which have been discontinued

And remove:

**4. "discard_plot":** This should instead be used to flag plots where an error has occurred (see #206).

The final list of plot types should be:

1. guard_plot
2. blank
3. treated_plot
5. observation_plot
6. residual_effect

**Comment by aislinnpearson** [comment]
This will be resolved in #223

**Comment by paul121** [comment]
> This will be resolved in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/223

@aislinnpearson just want to check in on this. Currently we have a dedicated `plot_type` field on `plot` assets which gets populated with this value. This makes it easier to filter plots by their plot type.

I'm curious if instead you would like to handle the `plot_type` entirely as a column descriptor. This could still be used to filter plots (as any column descriptor) and it has the added benefit that you could provide *any* plot_type value, but also means this would not necessarily be included on all plans (but we could hard-code this as a required column descriptor!). Adding this as a column descriptor means it could be harder to compare the plot_type values across experiments although I'm not sure how important that is.

I think I would prefer that we include this as a column in the `plot assignments` CSV (or equivalent file), but not consider this a "column descriptor". This helps enforce that a plot_type will always be provided as well as enforce the options to only the allowed values. BUT if the flexibility is really important that is OK, we can make it a "required" column descriptor as well!

**Comment by paul121** [comment]
> The final list of plot types should be:
guard_plot
blank
treated_plot
observation_plot
residual_effect

_For consistency can we make all of these have a `_plot` suffix? I guess it makes less sense for "residual_effect" but this can just be for the machine name!_

**Actually....** what if we just remove the `_plot` suffix from all of these? That suffix is already inferred with the field name being `plot_type`. We can still include "Plot" in the label!

Also need to include `discontinued_plot` in this list.

**Comment by paul121** [comment]
@aislinnpearson I made the above changes since they are so simple, let me know what you think. You can see my changes in this commit: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/commit/436d87b5cb48119d103eacf1b92d334d96ad82ef

**Comment by paul121** [comment]
We can remove residual effect!

**Comment by aislinnpearson** [comment]
HI @paul121,

Following our discussion last week, I spoke to Statistics and the plot_type they would like to add is a calibration plot:

plot_type: calibration
description: A plot which is used to calibrate the data generated in an experiment.
example: In an experiment where there is no replication, calibration plots can be used to estimate field spatial variability and calibrate the data of the main experiment accordingly.

Thanks for being so accomodating

**Comment by paul121** [comment]
Done! Note we recently added `baseline` and `seed_multiplication` plot types as well #333 

The current list is here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/40bb9fdb3c328113073a2d04bc2077da9cf07175/modules/farm_rothamsted_experiment/farm_rothamsted_experiment.module#L60-L77

**Comment by aislinnpearson** [comment]
This looks good to me. Thanks @paul121
