### ISSUE TITLE
Experiment module: edit experiment uploads

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#207]
Following on from issue #206 there are likely to be times when we want to edit the files uploaded into the experiment module - for example if 

1. treatment factors change (added, removed or edited)
2. factor levels change (added, removed or edited)
3. plot allocations change (added, removed or edited)

This might happen before the experiment is drilled or part way through. In either situation the ideal scenario would be to be able to edit the details in FarmOS (perhaps by re-uploading the excel spreadsheet, although I am open to ideas of how this might work) and keeping track of the replacement changes. It is at this point that we could flag specific plots with the labels mentioned in #206.

**Comment by aislinnpearson** [comment]
In the call on the 12 July 2022, we agreed that this would be discussed further and possibly implemented in the second phase of development of the experiment module (circa February 2023 or July 2023, depending on resource allocation). In the mean time any errors will have to be corrected manually OR corrected files uploaded and saved to FarmOS as a file rather than plot attributes. HOWEVER we agreed that plots must have flags associated with them that show they were swapped/ discarded/ etc and this will be implemented by the end of July 2022 (see #206)

**Comment by paul121** [comment]
> In the call on the 12 July 2022, we agreed that this would be discussed further and possibly implemented in the second phase of development of the experiment module (circa February 2023 or July 2023, depending on resource allocation)

It is march 2023 and this is now done. Right on schedule :grinning: Largely completed via #291 #276
