### ISSUE TITLE
Harvest (Trailer/ Bale Weights) Quick Form: Data fields which must be re-entered when re-loading a quick form

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#209]
Following discussion in #203 and the amendments in #82, the harvest (trailer/ bale weights) quick form, the following sections of the quick form should appear blank and require the user to enter new values:

1. Grass/ Straw Bales
2. Trailer Loads
3. Products
4. Operation
5. Job Status

**Comment by paul121** [comment]
Done!
