### ISSUE TITLE
Experiment module: expand basic data model

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#223]
Following the discussion on 12 July 2022, and fairly extensive development of the underlying experiment module, we agreed we would expand the underlying data model for the experiment module so it can be made live by the end of July 2022, in time for autumn crops to be sown. 

I've included a screen shot of the excel spreadsheet which we discussed in the call here, but assigned this issue to myself as I need to make example upload files and ideally create some initial documentation for @paul121, which I will do early next week.

Resolving this issue will also resolve #190, #204 and #205

**Comment by aislinnpearson** [comment]
Hi @paul121.

Here are the test files and template data files as promised. I've also included a markdown document with notes on which fields are required, and taken a first stab at the logic (although in reality, when you code this, what I have suggested might not make sense).

The plot types [#205] are listed in the plot attribute file, which is saved in the template file

[2022-07-19_farm_os_request.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9144171/2022-07-19_farm_os_request.zip)

**Comment by paul121** [comment]
Thank you @aislinnpearson !

These examples are looking good. Only one issue I'm seeing right now in the example file. The `plot_id` is not unique for the `guard` plots, they all have the same id `guard`.

![Screenshot from 2022-07-21 11-42-22](https://user-images.githubusercontent.com/3116995/180293629-92b1530b-b15e-4ba4-bb11-51bd51845ff8.png)

At a technical level we actually don't require this to be a truly unique ID. We use the `plot_id` in the `plot` asset name and also save it to the `plot.plot_id` string field, neither of which need to be unique. I understand these are separate from the plots used in the experiment (`treatment`), but I think we should still have a unique identifier for them. Would something like `guard_1`  be OK?

I'm curious how grassroots does this. Do they give unique IDs to non-treatment types of plots? Once we create the plot asset it will get a unique ID internal to farmOS, and I imagine they have something similar, but I think we need a unique ID that can be shared externally as well.

**Comment by paul121** [comment]
Ah also, the markdown convention file says the plot `plot_id` is optional. For the same reasons as above do you think we could make this required?

**Comment by paul121** [comment]
@aislinnpearson I think I'm seeing one bug in the example plot attributes file. The column EFO_0005136 references levels by their name, not ID. The other columns here all use the level ID. The computer would prefer to use the ID, but I remember you said the team likes to use the names as well. Either works, but we should be consistent.

![Screenshot from 2022-07-21 22-17-53](https://user-images.githubusercontent.com/3116995/180369119-d2f90f3c-a6a8-48c4-9f19-daf1ef5df86f.png)

**Comment by aislinnpearson** [comment]
HI @paul121,

Thank you so much for this. To try and answer your questions:

> The plot_id is not unique for the guard plots, they all have the same id guard.

This is interesting, and if I hadn't been out hand harvesting yesterday I'd probably have a different opinion _but_ I think that we should allow duplication in the plot_id _as long as_ the serial number is unique. Here is my reasoning: at the moment we are only describing the treatments applied to the plots, but ideally the underlying data model would also be able to supported measured response variables like yield Not always but occasionally you will take more than one replicate per plot, in order to average over variability within a single plot. In this instance the dataset needs to be extensible and most of the required columns (column, row, plot_id) will be duplicated (statistically this is important as you are accounting for variation within treatments, not across treatments). The _serial_ however is unique (see below for a quick visualisation, which might make a bit more sense). 

![image](https://user-images.githubusercontent.com/16349781/180403133-72fbf7ab-fc78-48af-8506-42a26a47459d.png)

So yes, I agree with you. As a part of our good practice guidelines you would number the guard plots so they can be easily differentiated (rather than simply by their row/ column numbers), but I'm not sure we should enforce that in FarmOS because I can see a situation where we may want to add response variables to the datasets in FarmOS, especially for routine analyses undertaken by the farm such as yield. Seeing as I haven't given this much thought my feeling is to leave it flexible for the time being but I have updated the test file and also included a note in the markdown file (attached). 

[2022-07-19_farm_os_request.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9168523/2022-07-19_farm_os_request.zip)

> I'm curious how grassroots does this. Do they give unique IDs to non-treatment types of plots? Once we create the plot asset it will get a unique ID internal to farmOS, and I imagine they have something similar, but I think we need a unique ID that can be shared externally as well

I'll ping Simon an e-mail now and ask him.

> Ah also, the markdown convention file says the plot plot_id is optional. For the same reasons as above do you think we could make this required?

Sorry - it should definitely be required. That was a late night, trying to get things done quickly error! 

> I think I'm seeing one bug in the example plot attributes file. The column EFO_0005136 references levels by their name, not ID. The other columns here all use the level ID. The computer would prefer to use the ID, but I remember you said the team likes to use the names as well. Either works, but we should be consistent.

So this is a more difficult question to answer. Yes, when setting up the excel spreadsheets it is easier for me to put the name in. But the excel files are only meant to be a stop-gap measure - the 'computer' should reference the id. Is it possible to reference the id based on the name in the spreadsheet in the uploader? Or is that a complicated solution.

The other thing I realised is that the unique id for each level is really column_id + level_id (e.g. EFO_0005163_1 for cultivar line 1).  To make things more complicated still, that is only unique _within_ and experiment. For example, cultivar EFO_0005163_1 might be line 1 in this experiment but 'Conqueror' (a common variety of wheat) in another. I don't think that matters here, but I thought I'd mention it just in case.

As a very rare use case, I have occasionally seen instances where you might have a column_id specified twice in the plot attributes. For example, if you are comparing cultivars ( EFO_0005163) which grow well together and give you extra disease resistance by introducing genetic diversity, you'd look at different combinations of cultivars. In this case I have called the columns  EFO_0005163-1 and EFO_000516-2 but reading your notes above makes me wonder if we want to formalise this.

**Comment by paul121** [comment]
Just chatted with Aislinn, here's what we decided:

re: plot_ids
- Change `serial` to `plot_number`, this should be a unique value.
- `plot_id` does not need be unique. (this allows for a new "replicate" or "yield strip" column to re-use plot ids)

re: plot attributes
- Plot attributes will always reference the *numeric* `level_id`
- If a column level `level_name` is not provided, use the `level_id`

re: duplicate columns
- Appending a `_1` `_2` suffix is the best for now. This is where the flexibility is nice.
- We discussed the case where there might be eg: 10 different options for cultivar mixes. Instead of creating 10 columns, this could be a single column with a factor level for each unique grouping of the cultivar mixes. But this depends on the experiment design, farmOS shouldn't dictate how it needs to be implemented.

**Comment by paul121** [comment]
@aislinnpearson we also have logic for a special (optional) plot attribute `crop` - when importing this will auto-create a new `plant_type` taxonomy_term and save to a dedicated `plot.crop` field. I don't see this in your requirements, is it safe to remove this? And the `crop` will now be a column descriptor when required?

**Comment by paul121** [comment]
This is done! @aislinnpearson I did the refactor to import all plot data from a single geojson file. I've opened #234 as todo for the next milestone.

**Comment by aislinnpearson** [comment]
Amazing. Thanks @paul121 

Sorry I missed this comment:

> @aislinnpearson we also have logic for a special (optional) plot attribute crop - when importing this will auto-create a new plant_type taxonomy_term and save to a dedicated plot.crop field. I don't see this in your requirements, is it safe to remove this? And the crop will now be a column descriptor when required?

The answer is yes, it is safe to assume. I've created an issue for it here (#235), which we can close straight away if it is already done.
