### ISSUE TITLE
Quick Forms: Move Start Time and Tractor Hours

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#233]
For all of the quick forms except the Commercial Assets Quick Form, please can we move start time and tractor hours to the first tab of the quick forms (setup tab).

**Comment by paul121** [comment]
@aislinnpearson I forgot to ask which order you would like these fields to appear in the Setup tab. Here I have added them directly before the tractor & equipment fields.

![Screenshot from 2022-08-22 13-14-55](https://user-images.githubusercontent.com/3116995/186010681-88e555e0-a8f4-4a25-8074-beac593a6363.png)

**Comment by aislinnpearson** [comment]
Hey @paul121,

That looks good to me. I don't think I specifically said this, but tractor hours (end) can stay on the operations tab. At least, that what how I interpreted the discussion I had with the farm team... this will probably be more relevant when it comes to saving draft quick forms (#95) that they can toggle back and forth between when entering a record, but I suppose we might as well put it in the right place now and see how we get on...?

**Comment by paul121** [comment]
Okay! I moved the end back to the operations. Also note that I have the log category up here now, too. How does that all look? The layout changes a bit with the screen width but it will stay in this order.
![Screenshot from 2022-08-24 16-06-23](https://user-images.githubusercontent.com/3116995/186539005-18bdd135-4901-486a-91c9-8b895ebc988f.png)

**Comment by aislinnpearson** [comment]
Looks good! Thanks @paul121 Very happy with that. :)
