### ISSUE TITLE
Experiment Module: remove 'add crop' logic from experiment upload form

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#235]
See comment https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/223#issuecomment-1192913578

Removing the logic in the experiment module which adds crops to the Crop Types taxonomy. Crops will now be a column type.

Can be closed if already completed.

**Comment by aislinnpearson** [comment]
hey @paul121 

I'm fairly sure this is done right? As in we never coded it this way in the first place - the experiment plan references the crop type, but not the crop listed in the plot attributes (which is the way I think it should be - see below images, which are as I specified them). The only time I can ever see this being an issue is when we improve the FarmOS maps and want to visualise the location of each crop _including_ plots. the challenge there is in the upload:

1. I'd have to get the scientists to type the crop name _exactly_ as it is in FarmOS, or at least allocate this at the upload
2. Crop isn't a column in every experiment - in fact, most are just one crop. We'd need to come up with a clever way of doing that too.

For the above reason's I'll mark this as closed and then create a new issue for the above two points.

![image](https://user-images.githubusercontent.com/16349781/185437926-30133e83-78ed-4734-b788-8c9b74764883.png)
![image](https://user-images.githubusercontent.com/16349781/185438608-e1e8ac40-4a9f-4366-b24f-3a06888efafc.png)

**Comment by paul121** [comment]
Actually @aislinnpearson this logic is still in place. Right now if a `crop` property is specified a `plant_type` taxonomy term will be auto-created or an existing will be used and saved as a reference in the `plot.plant_type` field. This logic harmless to keep in-place for the time being.

At first I thought we might want to remove the `plot.plant_type` field altogether, but now seeing issue #278, it seems that this field will be valuable for mapping outside the context of the experiment - it's just a matter of assigning the same plant_type to *all* plots in the experiment OR making it easier to assign individual/groups of plots the same plant_type.

SO it seems that we do want to remove the "add crop" logic from the upload form, and instead make this something that is assigned in the UI, does that sound correct @aislinnpearson ? If you agree let me know, I'll use this issue to remind myself to remove that little bit of code!
