### ISSUE TITLE
Quick Forms: Minor amendments to fertiliser and spraying quick form data fields

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#237]
A few minor requests to change the names, descriptions and required fields on the fertiliser quick form:

1. Target Rate: Please can we make this optional rather than required? Only needed for older fertiliser spreaders, most modern ones are accurate in terms of applying the set rate.
2. Treated Area: Please can we rename this "Machine Treated Area" to distinguish it from the field area. Fertiliser spreaders especially usually build in a small overlap, so the machine treated area is often larger than the field area. Please can we also change the description to "The total area to which the combined product(s) were applied, as recorded by the tractor or other equipment. If part of a hectare, please give the area to two decimal places."
3. Field Area: Please can we add a data field for 'Field Treated Area' to distinguish from machine treated area. The field would be numeric and recorded in hectares. The description should read "The total field area to which the combined product(s) were applied, to two decimal places. If part of a hectare, please give the area to two decimal places.". The question should be required and appear blank when the form is pre-populated. If possible, it would default to the area of the location (or combined locations) of the selected assets.
4. Please can we move the treated area, total volume applied and field area to the fertiliser tab

On the spraying quick form:
1. Please can we amend the description for water volume (spraying tab) to "The total amount of water added to the tank, as required to cover the field area(s)."

**Comment by paul121** [comment]
Nice, easy changes.

>  If possible, it would default to the area of the location (or combined locations) of the selected assets.

Unfortunately we don't have this ability just quite yet in farmOS 2.x, but if this is a larger priority we can certainly make it happen! @aislinnpearson here is the existing core issue, https://www.drupal.org/project/farm/issues/3209554, could you make a new issue here if/when you would like us to pursue this? 

Fertiliser updates: ![Screenshot from 2022-08-24 16-28-56](https://user-images.githubusercontent.com/3116995/186541037-28774974-4236-4d05-8b73-71692285ed8b.png)
