### ISSUE TITLE
Experiment Module: Plans not loading to live site

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#246]
HI @paul121, @mstenta 

I was trying to upload an experiment today and it all went perfectly, but I got the below error when I tried to actually view this plan: https://rothamstedfarm.farmos.net/plan/6

![image](https://user-images.githubusercontent.com/16349781/183071773-50133bd6-0c3e-40b1-87be-7c6e41ea791e.png)

I uploaded the exact same files to the Platformsh site and it all went well: https://2-5-xbzwxgi-2mu45anerqtvq.uk-1.platformsh.site/plan/16

I've attached the files below. Any idea where I might be going wrong? I did look for odd UTF-8 characters but couldn't find any... so I am not sure if the error is the same as #245

[2023-R-RAW-2313_farmOS-upload.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9268258/2023-R-RAW-2313_farmOS-upload.zip)

**Comment by mstenta** [comment]
Hi @aislinnpearson I got a few error notifications via email that alerted me to this.

@paul121 here is the error I saw:

`Error: Call to undefined function PHPUnit\\Framework\\assertNotEmpty() in /opt/drupal/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment/src/Plugin/Field/FieldFormatter/ColumnDescriptorsTables.php on line 54`

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/258915045d6fe9f10734e109878247b8e32613a2/modules/farm_rothamsted_experiment/src/Plugin/Field/FieldFormatter/ColumnDescriptorsTables.php#L54

**Comment by aislinnpearson** [comment]
Okay, thanks @mstenta. I'm not going to guess what that means, but no doubt Paul will have some useful ideas. Thanks both! :)

**Comment by paul121** [comment]
Thanks for sharing the error @mstenta! Sorry @aislinnpearson this is a goof on my part, accidentally using a function that isn't available in the production environment. I need to update my platformsh config so it better reflects a production environment, then I would have caught this earlier.

**Comment by aislinnpearson** [comment]
No worries @paul121 - it happens to the best of us, and these sorts of teething issues are to be expected. What do you need to do to resolve it? Is it the kind of issue where we need @mstenta to push a fix?

**Comment by paul121** [comment]
@aislinnpearson I'm preparing a fix and will tag a release including a few other issues here shortly!
