### ISSUE TITLE
Quick Forms: Archived assets still appearing in Quick Forms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#251]
I noticed that archived assets are appearing in the quick forms, which is makes it difficult to search for assets (see below). Can we please adjust the filter so that only unarchived plant and plot assets are shown? 

![image](https://user-images.githubusercontent.com/16349781/184623490-e410b902-5f8a-444b-bf45-dada85f0df46.png)

**Comment by paul121** [comment]
This was partially fixed as part of #260 . But I also noticed this happens in the commercial asset quick form. I fixed it there so that only active locations are available as options.
