### ISSUE TITLE
Sensors: Add Geometry to sensor assets

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#252]
Please can we add geometry to the sensor assets, so we can add point or polygon locations for where the sensors are installed.

**Comment by paul121** [comment]
Hey @aislinnpearson, assuming you are using sensor assets for your sensors, this should be possible right now! I believe you have two options actually:

1. Like any other asset, you can change an asset's location by creating movement logs. A benefit with this approach is you could track when sensors are deployed, by who, etc and also track their movement over time if needed. When you create movement logs you can 1) specify a "location" asset, 2) specify a precise geometry (not associated with an asset) or 3) do both! - this would be to say "this sensor is located in this field, at this specific GPS point. 

2. Alternatively, you can specify that the sensor asset "Is fixed" when editing the asset. This will display the map and let you draw a geometry representing it's fixed location. This should show the sensor asset on maps when it is relevant.

Let me know if that works and I think we can close this

**Comment by paul121** [comment]
![Screenshot from 2022-08-18 19-14-21](https://user-images.githubusercontent.com/3116995/185528533-cc668916-fa52-4409-bd66-b3621aac4611.png)

**Comment by paul121** [comment]
@aislinnpearson I'm going to close this, based on our conversation I think we figured it out. Feel free to open if you have any questions!
