### ISSUE TITLE
Quick Forms: Filter by Location

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#260]
A repeated request that comes from the farm team is to be able to filter plant assets by location. In version FarmOS version 1.x we made this possible for experiments by assigning each experiment a group and these groups then appeared as tick boxes under the location. IT made life much easier for the farm team, but the underlying data was very messy. Any single crop had three assets (a location, a plant asset and a group), and logs could be assigned either to the location or the asset. The new quick forms ensure that in theory at least you can only assign logs to active plant assets (see #251). 

For the commercial assets, this would be relatively straight forward: you'd filter by location and any plant assets associated with that location would be displayed (usually only one or two). Although even this gets complicated when you have commercial assets in two or more fields.

For experiments it is more complicated still, especially because we agreed that basal applications (i.e. when an input or activity is applied to all plots uniformly) should be recorded at plot level so that all plots have records of all activities. 

@paul121 suggested a pop-up box like the below which allows you to filter based on relevant terms (e.g. location, crop). This resolves the problem for commercial crops and maybe basal applications, but wouldn't' work for applying treatments to individual plots. However, it may at least be a step in the right direction.

The search terms suggested for the pop-up box were location, experiment code and crop. It would also need to filter the selectable assets so that only plant and 'other' asset types are included (the 'other' asset type being used to describe experiment boundaries).

**NOTE: This is a duplicate issue for #172 but is left in here as it contains some additional detail on how this should/ could be formatted.**

![image](https://user-images.githubusercontent.com/16349781/184672109-b4a6f1e3-5511-4988-9c40-ca46cd3653e0.png)

**Comment by aislinnpearson** [comment]
I discussed this with Tim today and he is adamant that, from a user perspective, tick boxes are much easier to manage. From an HCD perspective, I think it is worth putting in the development work if we can but I don't know if this means we need to reconsider the data structure. For example, should basal applications be assigned to the experiment surrounds, while plot treatments are applied to plots. I feel like this is safer than automatically blindly applying an activity to all plots by selecting the experiment surrounds. 

Instead, if you apply a treatment to an experiment, I feel like that treatment should be visualised amongst all the logs associated with the experiment. For example, if a log only refers to certain plots, that log still references the parent area by default and so shows up in all the logs associated with an experiment. Am I making sense?

**Comment by paul121** [comment]
Done!

**Comment by aislinnpearson** [comment]
Exciting! Looking forward to seeing it. :)
