### ISSUE TITLE
Experiment Module: view filtered plots as highlighted blocks

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#261]
When filtering plots in the experiment module, please can we make it so that **ALL** plots remain visible, but the selected plots are highlighted by filling the plot with a block colour - possibly orange to keep with the current colour scheme.

**Comment by paul121** [comment]
Simple! We just need to include the `All locations` layer on this map. It is normally added as a grey layer.
