### ISSUE TITLE
Quick Forms: Amendments to commercial asset quick form

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#269]
The Commercial Asset quick form is coming together now and I think I have found a nice way of making the harvest and drilling seasons unique by labelling each term as 'Harvest 2023' which is distinct from the drilling seasons labelled as 'Autumn 2022' or 'Spring 2023'. However, I think there are a few small changes we could make to improve the quick form still.

1. Change 'Season' to 'Drilling year' and limit the list _only_ to the terms under 'drilling year' in the Seasons taxonomy
2. Display the plant asset name by default at the bottom of the form so it is obvious what this will be. Then enable editing by selecting the slider.
3. Using the above convention for harvest and drilling seasons the automatic naming doesn't work quite as well. Ideally we would just select the year, but I don't know if this is possible. Perhaps if we invert the way they are named so the first four characters are always the harvest year. For example '2023 harvest' rather than 'harvest 2023'

**Comment by paul121** [comment]
Just chatted with Aislinn about this, for the naming issue 3 we can remove the "Harvest year:" prefix when adding the harvest year to the plant asset name.

**Comment by paul121** [comment]
Done!

> Display the plant asset name by default at the bottom of the form so it is obvious what this will be. Then enable editing by selecting the slider.

I moved the plant asset name to the bottom. To keep it simple I'm not going to display the asset name, this requires a bunch of AJAX as the form is being filled.. Once users use this once or twice it should become pretty clear. Is that OK @aislinnpearson ?

**Comment by aislinnpearson** [comment]
Hey @paul121 

I think I personally would have put it below crops and above associated files so it's a little bit more obvious _but_ as the functionality is working well, we can leave it as it is. The important thing is that it's there and we need to make this live so we can start entering logs for the experiments (currently held up by issue #307).

> To keep it simple I'm not going to display the asset name, this requires a bunch of AJAX as the form is being filled.

Sounds good to me - I've learnt the hard way with these AJAX fields! :)

Thanks for doing this
