### ISSUE TITLE
Experiment Module: Editing columns and column levels

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#276]
**This issue will now be address through two sub-issues:** 
Experiment Module: Add new columns #290
Experiment Module: Edit columns #291
Experiment Module: upload plot attributes as a CSV #275 
Experiment Module: Add/ edit factor levels and plot assignments #195 
Experiment Module: Edit plot geomentry #337 

**The final agreed mechanism for editing columns, column levels and plot attributes has been a process of some discussion.:** Our initial thinking is here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276#issuecomment-1359895471, which was updated here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276#issuecomment-1369949193 (with the later containing a new template for the GeoJSON and csv uploads), and then updated again here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276#issuecomment-1385344647.

-------------------------

As part of the experiment module, we occasionally need to edit the columns and column levels (with those changes transferring through to the column names and levels names in the plot assets). In addition to editing columns and levels, we may also want to add or delete them, with this again carrying forward into the plot assets.

From what I understand from @paul121 and @mstenta, I think we would need to look into how this data is stored in FarmOS, which I can't really comment on but which might also be another issue.

The only way I can think to do this is to add a 'edit', 'delete' and 'add new' button/ action to the column names, and a separate edit', 'delete' and 'add new' button/ action to the column levels, as all these actions are slightly different:

**Adding a column:** Requires you to fully define the new column and column levels, based on the properties of the other columns and column levels associated with the experiment, as well as upload a CSV where the new column and levels are associated with the plot_number and plot_id. While uploading, automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets..
**Edit column:** this will enable you to edit the column id as well as any one of the descriptor fields. Following @paul121's suggestion for the column levels, I'd suggest that we create the underlying data structure so the only required field is the column_id and column_name - the rest are optional and extensible (this may be impossible, but as they say if you don't ask, you never know!). If the column name or column id is edited, this is changed in the column levels and plot attributes. While submitting the changes, automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets.
**Deleting a column:** also deletes a column from the column levels and plot attributes. Automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets..

**Adding a column level:** Requires you to select a column and then define the column level attributes based on the attributes associated with other levels in that column. Requires you to edit the plot level attributes for that column or upload a CSV where the new column and levels are associated with the plot_number and plot_id (this is a bit complicated, I'm not sure how we'd want to do this). Automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets.
**Editing a column level:* will enable you to edit all fields _except_ the column name, column id and column level id. Editing the name of a column level automatically updates the name of the level in the plot attributes. Automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets.
**Deleting a column level:** Requires you to edit the plot level attributes for that column or upload a CSV where the new column and levels are associated with the plot_number and plot_id (this is a bit complicated, I'm not sure how we'd want to do this). Automatically creates a revision (with option to add a note) which is added to the plot and the experiment assets.

I am envisaging the above where you want to only edit or delete a minor detail here and there, or add additional detail to treatments. Sometimes however I think we'd want to be able to do batch uploads of either: 
1. the column levels (which requires you to re-upload the plot attributes), 
2. the columns themselves (requires you to re-upload the column levels and plot attributes). 
3. Just the plot attributes (covered in issue #275)
4. Independently re-upload the GeoJSON for example if the plots have been moved or mislabelled.

This is a massive task, but needed as otherwise the only option we have is to delete the whole experiment and re-uploaded it, which means re-associating logs.

> Following the call on the 20/12/2022, @paul121, @mstenta and I agreed that the best way to edit experiments in terms of a minimum viable product is to:
> 
> 1. Separate the column attributes from the GeoJSON so that only the plot geometry (with a plot_number as a required field) are uploaded, and then the plot attributes are joined via a separate csv upload, which also requires a plot_number as default
> 2. Every time the user would like to edit or add columns, they must re-upload all three csv files. At the same time, they will be required to submit a revision log message to say what has changed.
> 3. The original csv files and plot attributes will be saved as part of a revision log, so the history of all the changes is available and can be compared.
> 
> In future we may want to improve the editing functionality for plot attributes, but it makes more sense to do that once we have a variety of revision logs to look at and assess.
> 
> @paul121 This covers all the issues in the list at the top of this issue _except_ editing plot geometries. Do you think the same process would work there?

**Comment by aislinnpearson** [comment]
Hey @paul121, @mstenta, @richardostler 

As discussed in the FarmOS meeting on Tuesday I created two sub-issues for this: #290 and #291.

However, when I was doing it, I started to I wonder if maybe we are going to need a particular type of "asset" for the experiments that allows us to edit these column variables. Or, more complicated still, assets for the column variables and their levels, so we can actually associate plots with the specific column levels. I'm not saying that is definitely the case - @mstenta 
 and @paul121 you are the software engineers so probably have a much better idea of possible range of solutions - but I realised an additional complexity is that we want people to be able to define their own column attributes, especially for the column levels, but maybe also just for the column descriptors.

The whole thing makes my head spin. It's definitely something I think we are going to need to discuss, probably benefiting quite a bit from your insight too @richardostler!

**Comment by paul121** [comment]
> However, when I was doing it, I started to I wonder if maybe we are going to need a particular type of "asset" for the experiments that allows us to edit these column variables. Or, more complicated still, assets for the column variables and their levels, so we can actually associate plots with the specific column levels

@aislinnpearson you're thinking like a software engineer! Let me try to rephrase this in another way: should we model each column variable and column level to be a separate Drupal "entity"?

The base level "resource" or "thing" in Drupal is called an "entity". We've chosen to model most of the farmOS data model (assets, logs, plans, quantities, taxonomy terms) as entities because Drupal provides many helpers for building permissions, UI, Form and APIs around entities. I don't think assets would be a great fit for column descriptors and column levels, but perhaps taxonomy terms could work? We could even consider creating a custom entity type.

BUT maintaining custom entity types can be a lot of work so we really only want to do this when necessary (if we need all the permissions, UI, Form and API features). This is why we have started to model the experiment plan column descriptors as a simple JSON field on the plan. Plot assets have a key/value field used to reference the columns such as: `colum_id: column_level`

As we revisit these ideas to consider how to support Adding/editing column levels and descriptors I am tempted to use entities... but overall I don't think this is the right solution. Instead, I think we should continue to use JSON on experiment plans and the key/value field on plot assets, but create a more custom UI and Forms for adding/editing the column information associated with a plan. Building a more custom UI will give us much more control over the larger complexity I see here: updating plot asset(s) when column(s) are modified on the experiment plan.

Another approach could be to store this data in a custom database table. This would have some of the benefits of using entities (mainly the ability to quickly query the database for all column information) but also requires a good amount of custom work. I don't think we need this yet, but we could migrate to this if JSON proves to be too limiting.

I think it may be hard to visualize what this will look like because we don't have many examples of this type of thing in farmOS core, but it also means we have lots of flexibility! One example is the current "Column descriptors" table on the plan page - that is all custom, and we can add/remove anything we like there. I think it would make sense to include "Add column" and "Edit level" buttons on that page. Perhaps we should consider moving that from the "View" tab to its own dedicated "Column descriptors" tab, too. We could keep a consolidated list on the "View" tab.

All that said, we do have some time to implement this, so we should be thorough in planning out our implementation and all the use cases. For example, I'm making a major assumption that we don't need to support creating/editing column levels via the API... supporting this would add lots of complexity, and perhaps entities would support that use-case. Certainly want @mstenta perspective on this as well

**Comment by aislinnpearson** [comment]
Following the call on the 20/12/2022, @paul121, @mstenta  and I agreed that the best way to edit experiments in terms of a minimum viable product is to:

1. Separate the column attributes from the GeoJSON so that only the plot geometry (with a plot_number as a required field) are uploaded, and then the plot attributes are joined via a separate csv upload, which also requires a plot_number as default
2. Every time the user would like to edit or add columns, they must re-upload all three csv files. At the same time, they will be required to submit a revision log message to say what has changed.
3. The original csv files and plot attributes will be saved as part of a revision log, so the history of all the changes is available and can be compared.

In future we may want to improve the editing functionality for plot attributes, but it makes more sense to do that once we have a variety of revision logs to look at and assess.

@paul121 This covers all the issues in the list at the top of this issue _except_ editing plot geometries. Do you think the same process would work there?

**Comment by aislinnpearson** [comment]
Following our call on the 03 January we agreed that here are the distinct workflow processes for creating an experiment and the dependencies' between them:

**1. Select the location(s) of the experiment:** Select one or more field locations for the experiment
**2. Create an experiment boundary:** @paul121 I just realised the form we discussed won't work because the farm team will need to assign the experiment code and location _after_ the scientist has submitted a description of the experiment. For the MVP version I will have to teach the farm team how to add boundaries. See below note.
**3. Upload the plots GeoJSON:** This will be a GeoJSON that _only_ contains the plot_number. Ideally you would **have** to have a boundary in place **before** you can upload the plots so we can make sure there is always one present for the quick forms. If possible, I think this is the only logic we need to build in for now, except for the csv/ GeoJSON logic in 4.
**4. Upload the csv files:** All three csv files are uploaded simultaneously. **All three files have to be uploaded for the first upload _as well as_ any subsequent uploads where the columns, column levels or plot attributes have been edited**. This requires the GeoJSON to have been uploaded.

**Logic for enforcing requirements in future versions:**

At some point in the future it might be nice to create forms that help enforce some of our requirements. For example, when creating an experiment boundary as above. However, I think it makes more sense to do this later when we have a better idea of how people use the form and also in #324.

I have also attached the new template for the GeoJSON/ csv upload here. There are three versions: an initial upload, and then two were I have added/ removed columns which I thought might be useful for testing. 

[2023-01_2.10.x_example-upload-files.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/10338074/2023-01_2.10.x_example-upload-files.zip)

**Comment by aislinnpearson** [comment]
Following our call last week, @paul121 and I discussed the workflow further and agreed the following:

**1. Create a plan:** To create an experiment plan the only required field is the experiment name.

> Required fields: experiment name

**2. Add an experiment boundary:** In order to create an experiment boundary (saved in FarmOS as a land asset), the plan must already have field location(s) and an experiment code defined. This is because (1) the experiment boundary needs a parent location and (2) the experiment code is used to auto-create the name of the land asset/ experiment boundary. The option to upload a KML to the land asset/ experiment boundary is optional.

- Required fields: experiment name, experiment code, field location(s).
- Optional fields: geometry (KML) for the experiment boundary

**3. Add plot assets:** To create plots you must have specified an experiment boundary to document the location of the plots. Note that the experiment code, which must be provided to create the boundary, is also used in the default naming convention of the plots. The user then creates a list of plots by specifying the number of plots, which must be equivalent to the length of the plot_number field in the csv upload in order to add plot attributes. This creates the plot assets and assigns them a name of the format [experiment_number]: [plot_number], but at this point the plots do not have any geometry or other attributes. 

- Required fields: experiment boundary (which includes the experiment code).

**4. Upload plot attributes:** To add attributes to the plots, you must first have created the plots. You can then upload the plot attributes by uploading three csv files: one which describes the columns in your 2D array, one which describes the column levels and a third which describes the plot associations. Plot assets will be matched against their plot attributes using the plot_number as a primary key. 

- Required fields: plot assets (and the associated experiment boundary).

**5. Upload plot geometry:** Requires plot assets (not plot attributes). Plot geometry is added to the plot assets by uploading a geoJSON where the only attribute is plot_number. Any other plot attributes (e.g. plot area) should be uploaded via the plot attribute upload.

- Required fields: plot assets (and the associated experiment boundary).

A few other points:

**Editing Plot Assets:** @paul121 and I discussed the challenge of editing plot assets once they have been created. The solution we identified was that we can include a reset button if the experiment is in planning (but isn't available if the experiment is active). However, I feel like this solution needs to be refined - for example, I think we should probably stick with the standard FarmOS convention that you shouldn't be able to delete plot assets once a log has been assigned to them (you need to delete or reassign that log first). We also need to think through how this relates to the upload of the plot geometry and plot attributes. Should those be deleted first, and then re-uploaded? 

**Naming the CSV uploads:** @paul121 and I discussed this at length with no real consensus on a solution as they could also be called variables or columns descriptors.... My current thinking is that f we persuade people to think of the plot attributes as a fully described data frame (aka a 2D data array) which requires all three csv files that might solve our problem. Although if we did that, we might want to change what we are currently calling 'plot attributes' to 'plot associates' or something? The other name I thought of was 'Upload experiment attributes' which could also work, but to my mind doesn't include metadata. I remain open to suggestions.

**Comment by paul121** [comment]
Done!
