### ISSUE TITLE
Experiment module: add validation for allowed column types

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#279]
HI @paul121,

I was wondering if we could add another quick fix to the current milestone. 

I've just come across an experiment which needs a different column type: basal treatments (ironically following our conversation on issue #260). Let me know if that's okay.

**Comment by paul121** [comment]
Hey @aislinnpearson yep this is easy, what is the machine ID you would like for the column type? `basal_treatments` ?

**Comment by aislinnpearson** [comment]
Oh yeah. Good point. Maybe basal_treament (without the 's'?)

**Comment by paul121** [comment]
Yes without the s sounds great. @aislinnpearson I actually never got to implementing the validation logic to enforce only allowed  column type values. It got tangled up between #204 and #223 ...

Could you send me a list of all the column_type values you are currently using?

**Comment by aislinnpearson** [comment]
> Could you send me a list of all the column_type values you are currently using?

Sure:

design_factor
field_attribute
treatment_factor
treatment_component
treatment_application
basal_treatment
