### ISSUE TITLE
Experiment Module: Link to external documents

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#284]
One of our farm team has asked if we could please link to external documents which are saved on a shared drive. Specifically the experiment plans, which currently get uploaded to FarmOS as well.

The link would probably be to a SharePoint drive, but I'll need to confirm the exact specifications with @richardostler 

This field would ideally appear on all experiments, including those already in FarmOS, so we could retroactively add the links

**Comment by aislinnpearson** [comment]
I've just had a chat with Chris Mackay, and we thought it might be good to link to more than one file in an experiment (hopefully this is relatively easy: if we can link to one, we can link to many). The other thing we thought is that the actual files would ideally be attached to the logs, but equally when you look at the experiment you'd like to be able to look at all the files and find related logs. Maybe that is a second issue, but putting it here temporarily so we can discuss it.

**Comment by paul121** [comment]
Two fields (URL or Link):

- Experiment plan
- Experiment files

> but equally when you look at the experiment you'd like to be able to look at all the files and find related logs

We'll hold off on the log files portion of this for now.

**Comment by aislinnpearson** [comment]
A couple of example links for testing:

Experiment plan: https://rothamsted.sharepoint.com/:x:/r/teams/FieldExperiments-ExperimentPlans/Shared%20Documents/2023%20Experiment%20Plans/2023-R-BK-1_Broadbalk.xlsx?d=wbaca7dacbc6c44b5881023972edb0bf0&csf=1&web=1&e=4gMnC2

Experiment file: https://rothamsted.sharepoint.com/:f:/r/teams/FieldExperiments-Experimentfiles/Shared%20Documents/2023%20experiment%20files/2023-R-BK-1_Broadbalk?csf=1&web=1&e=s3E4GI

@paul121 you won't be able to access these links (our Teams drive is only accessible internally) but I can at least test them for us and make sure it is doing what we need it to. :)

**Comment by paul121** [comment]
Done! I've added two link fields to experiment plans in the "Trial design" area. @aislinnpearson you can test this out here: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/plan/1

Let me know if those links worked, I copy/pasted into the form and they appear to take me to a Microsoft site. Also let me know if you would like to move the links to a different area in the UI, that is an easy change.

**Comment by aislinnpearson** [comment]
Hey @paul121,

This looks amazing - worked perfectly for me, and the fact that you can't access it also means we know it's private so that's good too.

The one small adjustment I'd ask is if we can automatically make it open in a new tab, but I realise that might be browser specific...
