### ISSUE TITLE
Quick forms: Experiment assets not displaying when field selected

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#286]
**This issue was addressed in two sub-issues:**

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/292
https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/293

---------------------------------------

HI @paul121, @mstenta 

Not really a bug, more just me getting confused by how the location attributes work for the new feature in #260 :

I just noticed that because the experiments have their own location they don't appear when you enter a field in the location. See for example the below for Blackhorse:

Locations within the field:
![image](https://user-images.githubusercontent.com/16349781/189976450-19a4803c-b5f8-4f0b-8065-cb1b7b0cf02d.png)

Assets appearing in the Quick Form:
![image](https://user-images.githubusercontent.com/16349781/189976675-a5ef06ea-1340-473b-9990-c5b4db590092.png)

I think there is an added level of complication here in that how we previously dealt with this, and how we now deal with it in the experiment module is different:

Previously experiments had one or more land assets with the land type 'bed'. Each bed has a plant asset associated with it and logs would be assigned to those assets.

In the new experiment module the experiment areas get a land type of 'other' but there is no plant asset associated with the whole area.

A short term workaround is to type in the experiment code and pull up the land asset in the locations box, which displays the plant asset, but this takes longer or an equivalent amount of time to the old way of doing things. It also only works for old way of doing things...

Given the logic is already quite complicated, open to your suggestions @paul121 on the best way of approaching the problem. Apologies for failing to see it before. Otherwise it looks really good.

**Comment by paul121** [comment]
> Previously experiments had one or more land assets with the land type 'bed'. Each bed has a plant asset associated with it and logs would be assigned to those assets.
...
A short term workaround is to type in the experiment code and pull up the land asset in the locations box, which displays the plant asset, but this takes longer or an equivalent amount of time to the old way of doing things.

Ah yes. So to confirm, the expected behavior for the "old" way of doing things, you would like to see:

1. Type in "Blackhorse"
2. See plant assets located in Blackhorse (as currently displayed, these are OK)
3. ALSO include the plant assets located in sub-locations of Blackhorse (2022/R/CM/2201 etc as seen in your screenshot - each of these has an additional plant asset associated with it)

> It also only works for old way of doing things...

Right. So right now I'm ONLY displaying `plant` assets as options in the checkboxes. To change this I think we would need to allow `land` assets as well, but I think the worry is that users will select land assets in the hierarchy instead of the individual plant asset.

BUT we could add another rule to this: only allow land assets that are associated with an experiment plan? In this case you could submit the quick form to create logs referencing only the "parent area" (experiment surrounds/bounds) but not individual *plot* assets. I think we just want to make sure users choose plant assets *most* of the time, unless they are submitting data for an experiment?

**Comment by aislinnpearson** [comment]
HI @paul121 

> So to confirm, the expected behavior for the "old" way of doing things, you would like to see:

> Type in "Blackhorse"
> See plant assets located in Blackhorse (as currently displayed, these are OK)
> ALSO include the plant assets located in sub-locations of Blackhorse (2022/R/CM/2201 etc as seen in your screenshot - each of these has an additional plant asset associated with it)

Yes, you are correct. That is what we are expecting to see for the historic experiment assets so is probably something we need to do regardless (unless we consider changing all the historic experiment assets to a plant asset with a fixed location as per the below?). For the new experiment module though I am hesitant to display anything other than plant assets for the same reason you are... we've been there, and I'm not sure we want to go back!

For the new experiment module I had a couple different way of doing things, both of which have their pros and cons.

1. We could create a plant asset associated with the experiment land asset. 
**Pros:** this follows the same conventions as before, with experiments and commercial areas following the same convention.
**Cons:** it's a bit awkward and cumbersome as every experiment would have plot assets, land asset(s) and plant asset(s), which is bound to get confusing

2. We could make the experiment boundary a plant asset with a fixed location
**Pros:** Fewer assets, so less potential for confusion. Follows a similar convention to commercial areas, and possibly a better convention because the experiment boundary isn't strictly a land asset in the way a field is the land asset. I think a better description for this is a plant asset with a fixed geometry. As our farm manager put it "fields stay in the same place, and plants are things that move through them over time".
**Cons:** slightly more complex to implement as requires changing the experiment module _and_ quick form logic (we'd still need to display plant assets associated with nested locations for backwards compatibility). Follows a similar convention to commercial areas but not exactly the same. Also I have never used plant assets in this way, so can't be certain what the pitfalls of this approach would be. For example, how would harvest locations work?

Let me know what you think, happy to also have a call about it if that's easier

**Comment by aislinnpearson** [comment]
Another thought which just occurred to me is that we could use plant assets with a fixed location for temporary areas/ tranitory fields at North Wyke (#80)

**Comment by aislinnpearson** [comment]
> Also I have never used plant assets in this way, so can't be certain what the pitfalls of this approach would be. For example, how would harvest locations work?

It occurred to me that I could test the use of plant assets in the 2.5.x Drush site: https://2-5-xbzwxgi-2mu45anerqtvq.uk-1.platformsh.site/plan/16

It seemed to work well, including when submitting a harvest form: https://2-5-xbzwxgi-2mu45anerqtvq.uk-1.platformsh.site/locations

And when submitting a drilling quick form: https://2-5-xbzwxgi-2mu45anerqtvq.uk-1.platformsh.site/quick/drilling

Sorry I didn't think of this before. It was only when testing it that I realised you use the same logic (is fixed and is location) for land assets, and we wouldn't be changing all the much except the metadata associated with the plant asset, much of which I realised is duplicated from the View page (e.g. crop, variety, season which aren't available in the land assets). This makes me even more certain option 2 makes sense, but let me know what you think @paul121

**Comment by paul121** [comment]
Shoot sorry for the delay getting back to you on this.

I agree that option 1 you described is quite awkward, I think we should avoid creating multiple assets when trying to represent the same "thing".

> This makes me even more certain option 2 makes sense

I'm not fully convinced we should change the experiment boundary to be a plant asset. One minor issue with this is that all plant assets are *required* to have a crop/variety and I'm not sure we could accurately fill this in for the experiment boundary (plots may be multiple crop/varieties?)

> because the experiment boundary isn't strictly a land asset in the way a field is the land asset. I think a better description for this is a plant asset with a fixed geometry. As our farm manager put it "fields stay in the same place, and plants are things that move through them over time".

I agree the boundary isn't the same as a field, but I think it is more similar to a land asset than a plant asset. Perhaps a good way to think about it is as a "Management area", which I would consider a grouping/hierarchy of sub land and plant assets. It seems that making this a plant asset is more convenient for the quick forms than it is for the experiment plan data model. I think we should try and keep the experiment plan data model true to form. 

I'd like to propose option 3: a new "land type" option of "Experiment boundary". This makes it a clear distinction what the land asset represents. It also provides a strict rule we can use when searching for assets via the quick form: only allow plant assets OR experiment_boundary land assets.

**Comment by aislinnpearson** [comment]
HI @paul121 ,

I think that's a great idea. In that case we would have three elements associated with an experiment:

- an experiment asset (which is a location and has a geometry)
- plot assets
- an experiment plan

I think that is neat and very tidy, with a nice differentiation between experiments and commercials. However, my other thought when reading the above is that field experiments always have at least one crop/ variety... and where they really differ from commercial plant assets is that they have a lot of different properties too - experiment codes, objectives, crop rotations to name but a few. Of course however, those things are currently associated with the Experiment plan so now I have the question in my head of where is the appropriate place to store that information? The plan or the asset?  think we could try to link this with the ISA model in #202 and Grassroots.

In short I think we need to think carefully over the next couple months about which data fields are associated with which element (and I have created a new issue for that here and assigned it to myself so we tackle this relatively soon). But I am also aware we need to resolve this issue soon, as they are already assigning records to the new experiments.

For now , I was going to suggest we keep it simple for the time being and use only the following data fields in the experiment asset:

- name
- status
- notes
- parent
- images
- files
- is location
- is fixed
- geometry
- revision log message

And then think about it more seriously between now and December, on the basis that we could write an update hook to move any data fields in later versions. Does that seem like a sensible way of doing things? It sounds quite technical to me, so let me know if I have overlooked anything...

**Comment by paul121** [comment]
> However, my other thought when reading the above is that field experiments always have at least one crop/ variety... and where they really differ from commercial plant assets is that they have a lot of different properties too - experiment codes, objectives, crop rotations to name but a few. Of course however, those things are currently associated with the Experiment plan so now I have the question in my head of where is the appropriate place to store that information? The plan or the asset?

Yes, I think the majority of this should be associated with the experiment `plan` entity, not the experiment boundary land asset. Just to cross reference, we already added many of these metadata fields (including a crop/variety) to the experiment plan with this issue: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/78

> For now , I was going to suggest we keep it simple for the time being and use only the following data fields in the experiment asset:

Great, these are the default fields included with `land` assets so I don't think we need to do anything here for the data model. Right now there may be more fields visible in the land asset form UI... @aislinnpearson  if you would like to change which are visible could you open a new issue? Although I'm hesitant to suggest that we change this right now, I think it would be better to leave it with the default form for now.

> on the basis that we could write an update hook to move any data fields in later versions. Does that seem like a sensible way of doing things?

Absolutely! Things at the data model should be given more thought. It seems like we can store most all of this information at the experiment plan level for now. The "experiment asset" (experiment boundary land asset) feels like a concept that is still evolving. But I like adding an `Experiment boundary` land type as a first step to formalizing this concept, this will make it much easier to select this asset from the quick form UI.

**Comment by paul121** [comment]
@aislinnpearson if you're happy I think we can close this issue. I've created two follow up issues that solve the original issues here:

- https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/292
- https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/293

**Comment by aislinnpearson** [comment]
Okay, great. Thanks @paul121. I've made a new issue to review the data model for the plan/ asset/ plot data items as part of the next phase for the experiment module (#296) and will close this issue as the two sub-issues are now done.

**Comment by aislinnpearson** [comment]
Hi @paul121 

> Right now there may be more fields visible in the land asset form UI... @aislinnpearson if you would like to change which are visible could you open a new issue? Although I'm hesitant to suggest that we change this right now, I think it would be better to leave it with the default form for now.

I think the only one which is missing is the ID tags. We may want to use this later for monitoring experiment numbers, but right now I think we have everything we need until issue #296 is addressed.

I also checked all of the other asset types but didn't see anything that stands out as something we need to add in now. At some point, we may want to point to a website where the data is stored similar to what has been done for the sensor asset but I definitely don't think that is something we should do _before_ reviewing the data model.
