### ISSUE TITLE
Update Hook: Log Categories

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#288]
Please can we create an update hook which takes categories from the previous (2.5.0) implementation of the quick forms which were saved in the notes and updates them so they are converted to log categories as per issue #160 

There are only two quick forms where we previously implemented this:

**HARVEST QUICK FORM (trailer and bale weights)**

On the harvest quick form we previously had three options:

![image](https://user-images.githubusercontent.com/16349781/190439939-16f8d6e9-2ed9-4cfb-8626-e8dd9be51010.png)

They were **only used** in the Trailer and Bale weights quick forms (logs with the name Harvest (Trailer and Bale Weights)) where they were displayed as Type of harvest: Bailing

![image](https://user-images.githubusercontent.com/16349781/190455191-1dcb40d4-beaa-4e10-9fc4-19a5e43f95e7.png)

These are now correct in the log categories taxonomy for North Wyke:

![image](https://user-images.githubusercontent.com/16349781/190454420-8b193b1b-b068-4dcf-92c4-ff370fce6ce3.png)

And Harpenden

![image](https://user-images.githubusercontent.com/16349781/190454551-70d3c7f2-5fbc-425a-bd8f-8efda4cd49c5.png)

**OPERATIONS QUICK FORM:**

For the field operations quick form this replaces the Task field, which we also use to generate the log name. They were saved as Task: [Operation] in the logs:

![image](https://user-images.githubusercontent.com/16349781/190595456-36aaec83-af2b-4986-953d-95788d7ae87b.png)

Again, I have tried to keep the list of terms identical. 

![image](https://user-images.githubusercontent.com/16349781/190592441-9a9e106d-575e-43eb-9aa5-efd6da84add9.png)

![image](https://user-images.githubusercontent.com/16349781/190593079-6b982906-af5e-49a2-b783-52295f72f446.png)

These are now correct for North Wyke:

![image](https://user-images.githubusercontent.com/16349781/190594893-192f6ebf-718e-4863-a198-ae3d75e2b9e3.png)

![image](https://user-images.githubusercontent.com/16349781/190594990-252c9990-2a91-4857-8478-4e266444e872.png)

And Harpenden

![image](https://user-images.githubusercontent.com/16349781/190593987-e8d3addd-454b-4b8a-bb80-6804f57544d3.png)

![image](https://user-images.githubusercontent.com/16349781/190594082-b035aad8-6271-43cd-b44c-2854c5c04a2d.png)

**Comment by paul121** [comment]
Done! I added a log message for the admin whenever we update logs. This should help give us a sanity check that the update hook worked

![Screenshot from 2022-10-24 15-40-49](https://user-images.githubusercontent.com/3116995/197643630-0fd73d1f-7b39-4e0c-b4a4-6c504f4587b6.png)

**Comment by aislinnpearson** [comment]
Amazing. Thank you Paul!

**Comment by aislinnpearson** [comment]
@paul121 I couldn't check this because it doesn't apply to the dev site but happy with the above test you have done and can check it when it's live.
