### ISSUE TITLE
Experiment Module: Add new columns

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#290]
Child issue for #276: Add a column to the plot attributes for an experiment

The ideal way to do this is would be if, in FarmOS, the user would:

1. Click a button to add a new column to the plot attributes
2. Fill in the required data fields:
    **Column Type:** List (Required)
    **Column Name:** Short text (Required)
    **Column Abbreviation:** Short text (Optional)
    **Column Description:** Long text (Optional)
    **Data Type:** List (Required)
    **Length:** Integer (Required)
    **Ontology Term:** This would ideally select from a taxonomy in FarmOS which has the below properties, and be used to 
               **Ontology ID:** Short text (required). Must be a unique identifier for the ontology term. 
               **Ontology Name:** Short text (required). The name of the term, as defined in the ontology 
               **Ontology Description:** Long text (required). The description of the term, as defined in the ontology. 
               **Ontology URL:** URL (preferred). The doi/ permalink to the ontology term. The reason this is _not_ requires is that it has to 
               be left blank for terms which are not in an ontology
3. Be asked if they want to specify the column levels (otherwise they are just given a sequential integer from 1:n based on the number of levels with no description)
4. If yes, they are given a list of sequential integers associated with the column name/ id and asked fill in the required fields:
    **Level Name:** Short text (Required)
    **Level abbreviation:** Short text (optional)
    **Level description:** Long text (optional)
    **Ontology term:** URL (optional) or possibly pulls from the Ontology taxonomy as above
    **Quantity:** The option to add one or more quantities (Optional)
    **Application window:** Two boxes of short text? (Optional) The period of time during which the treatment should be applied or 
        the activity take place. Would ideally be a date range but sometimes this is simply "Spring" or Summer".
    **Growth Stage** Short text (optional)
    **Level abbreviation:** Short text (optional)

Once complete, the user is asked to upload a csv with the plot numbers linked to the _**names**_ of the column levels, as defined above (or sequential integers if levels haven't been defined). 

I don't know if this is possible, but ideally we would be able to upload more than one new column at a time - for example, if the stats team are uploading all of their design files.

Using the above method will also mean that different teams can add different pieces of information to the experiment plan in version 2.0 of the experiment module. e.g. the Farm team could upload the plot layouts, the Stats team could upload the experiment design, the sponsors could upload the varieties, etc

**Comment by aislinnpearson** [comment]
See this comment here for the final agreed mechanism for editing columns, column levels and plot attributes is here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276#issuecomment-1359895471

**Comment by paul121** [comment]
This will be done with #276. When re-uploading CSVs a new column can be added.
