### ISSUE TITLE
Experiment Module: Edit columns

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#291]
Child issue for https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276: Edit a column which already exists in the plot attributes for an experiment

Edit column: this will enable you to edit any of the column attributes listed in issue #290 _including_ the column id (for example, if a term gets added to an ontology).

Editing a column would also enable users to:

**Add a column level(s):** for example, if the number of varieties change in an experiment, or the experiment design is changed.
**Editing column level(s):** will enable you to edit all attributes associated with a column level, as described in #290 
**Deleting column level(s):** delete any previous column levels
**Upload replacement plot attributes** if the column levels are edited, it makes sense that this would cascade through to the plot attributes, so ideally the user would be able to upload a csv with the plot numbers linked to the edited plot attributes.

Editing the column levels should automatically create a revision (with option to add a note).

We may want to consider creating a specific column 'asset' (or something similar) not only so we can submit revisions, but also so we have a consistent ID if the column_id changes (which is possible if the ontology term changes - for example, if one of the Rothamsted terms is added to a proper ontology and we want to use their url).

**Comment by aislinnpearson** [comment]
See this comment here for the final agreed mechanism for editing columns, column levels and plot attributes is here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/276#issuecomment-1359895471

**Comment by paul121** [comment]
This will be done with #276. When re-uploading CSVs existing column data can be modified.
