### ISSUE TITLE
Experiment Module: Extend experiment metadata

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#298]
As a part of phase 2 of the experiment module we need to assess what metadata is linked to the experiments.

The metadata associated with each experiment (treatments, factor levels, sponsor, etc) should be based on the current version of FieldNet, where the minimum information is well reasonably well defined, as well as the standards currently used for [GLTEN,](https://www.glten.org/), Grassroots and the ISA framework (#202)

This is a child issue for #295

**Comment by aislinnpearson** [comment]
After a period of extensive discussion @mstenta, @paul121, @richardostler and I have agreed on the basic data model for this. 

Based on the above data standards, we have created a data model with five entities:

**1. Researchers:** An entity which contains metadata about the people associated with the experiments, not all of whom are FarmOS users. As @paul121 pointed out "Heck, the root of this may even be useful in a generalized module for other farms, wanting to add all employees into the system, but not necessarily as users..." so this may also have broader applicability for FarmOS core at a later stage
**2. Programmes:** An entity which contains metadata about research programmes associated with experiments
**3. Experiments:** An entity which contains metadata about experiments.
**4. Designs:** An entity which contains metadata about the designs associated with one or more experiments.
**5. Plans:** This entity already exists, but will need additional data fields added to it

The initial list of data fields for each entity is here, but is likely to be updated as we continue to discuss minor points in the design: 
~~[Experiment Module Data Fields.xlsx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/10555722/Experiment.Module.Data.Fields.xlsx)~~ _See below for updated file_

I agreed with @paul121 that I would create separate issues for each entity:

Researchers: #354
Programmes: #355
Experiments: #356
Designs: #357
Updated Plans: #358

As a list of next steps, @richardostler and I need to create a clear linking diagram to show how these entities relate to each other. I also need to overlay the data fields onto the various data standards (see #202)

**Comment by aislinnpearson** [comment]
Hi @paul121,

Here is an updated file as promised. I amended the design so the first four fields of the treatments are similar to those in the column uploads.

One day in the future, it might be nice to make a widget for this that you can export to csv... but that can definitely come later. :)

~~[Experiment Module Data Fields.xlsx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/10735178/Experiment.Module.Data.Fields.xlsx)~~ _Updated in the comment below_

**Comment by aislinnpearson** [comment]
Hi @paul121,

Here is an updated excel file with the changes we discussed last night:

**1. Experiment Design Tab:** Treatments now a text box with 'add treatments' widget removed (as discussed this was a duplication of columns csv upload, and better to eventually work towards creating entity types for treatments/ columns which will allow us to do everything in the user interface). 
**2. Experiment Design Tab:** I also added an additional question about the number of treatments, to save users having to count them in the columns file (but also because at some point we might be able to use this for validation).
**3. Experiment Tab:** I removed the 'add rotation' widget as discussed as an experiment with more than one rotation which _isn't_ a treatment is an edge case probably better dealt with in the plan/ csv uploads. As discussed, if the user selects 'rotation is treatment' there is no need to describe the rotation applied to the experiment as a whole.

[Experiment Module Data Fields.xlsx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/10803384/Experiment.Module.Data.Fields.xlsx)

**Comment by paul121** [comment]
I've completed the 3 items listed above. I also added the "tabs" to the Experiment and Design forms to better organize the fields.

![Screenshot from 2023-02-27 17-13-17](https://user-images.githubusercontent.com/3116995/221726939-8f5eda7d-3bed-4232-a988-44f89231aaa0.png)
