### ISSUE TITLE
Experiment Module: Create e-mail alerts

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#299]
Once a user has been given a login (#76) they will be able to create experiment plans, providing metadata about their experiment (#296). When these plans are created and edited, an alert should be sent to anyone associated with the experiment (#322) and as well as a designated list of people on the FFEC. Basic specifications are

- An e-mail is sent any time a user presses 'Save' on an experiment plan
- The email should be sent to any users associated with the plan and a designated group of users within FFEC (the committee who review the experiments)
- For the alerts sent to FFEC, we have two options. We could create a dedicated e-mail list or send them to users listed as Field Trials Managers. The second would require creating a new user type, and needs discussing.

@paul121 suggested sending the e=mails themselves was a relatively easy fix, with Drupal modules available.

This has deliberately been kept simple for the first version of the release, but realistically we will want to review how often e-mails are sent. Suggestions include:

- Not sending e-mails, but instead having alerts within FarmOS
- Sending summary e-mails once a week
- Including the revision log message in the e-mail
- Allowing users to set the alerts/ e-mail frequencies
- Highlighting changes in red, so a field trials manager has to approve them

What is possible will also depend on the Drupal module.

This is a child issue of https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/295

**Comment by paul121** [comment]
We chatted more about this today. Here are the features I'll work on for the first pass of experiment alerts:

1. Add a user reference field to plans: `plan.notification_user`. Email updates will only be sent to these users.
  - We considered using an email field instead. This would be useful for cases when an email isn't associated with a user (eg: FFEC "inbox" address) but we determined that this isn't necessary. Creating a user should cover most of the initial use-cases.
2. Also create an "Experiment admin" configuration that accepts a list of emails that should receive ALL experiment plan updates. This could be Aislinn or perhaps FFEC emails as well
3. To start, when the experiment plan is created, updated, deleted we will send emails.
  - At a minimum this email will include the general experiment metadata (name, code, etc) as well as a link to view the experiment plan.
  - I will investigate if it is possible to include details on "what changed"... eg: status changed from a->b

**Comment by paul121** [comment]
Bumping this to 2.10

**Comment by paul121** [comment]
I'm going to include this in 2.10 since I already had much of the code written. Here are some examples. Note that "Drush Site-Install" would be replaced with the name of the farm as configured on each instance! :-)

When entities are created I include some basic information in the email (name, codes, status, etc). When an entity is updated I include which fields values were changed (but don't include the actual fields themselves... could add this later.) Last, there is also a simple email for when things are deleted.

With the exception of the deletion event, these emails always include a link to the entity as well as the revision log message if one was provided.

Create experiment:
```
A new Plan 'Plan 1' was created by admin.

Revision message: None.

Plan info:

- Name: Plan 1

- Status: Planning

- Name (Abbreviation): P1

- Experiment Code: 123

- Project Code: 123

- Experiment Design: Design 1 [1]

View the new Plan here: https://rothamsted.ddev.site/plan/3

-- Drush Site-Install team

[1] https://rothamsted.ddev.site/rothamsted/design/1
```

Update experiment:
```
The Plan 'Plan 1.1' was updated by admin.

Revision message: Adding some new data.

Changed values: Name, Status, Notes, Flags, Assets, Name (Abbreviation),
Experiment Code, Cost Code, RRES Experiment Category, Objective, Drilling
Year, Harvest Year

View the new Plan here: https://rothamsted.ddev.site/plan/3

-- Drush Site-Install team
```

Update program:
```
The Research Program 'Program 9' was updated by admin.

Revision message: None.

Changed values: Principal Investigators

View the new Research Program here:
https://rothamsted.ddev.site/rothamsted/program/9

-- Drush Site-Install team
```

**Comment by aislinnpearson** [comment]
Awesome, thanks @paul121 - I've flagged this as something that needs documenting so we can keep on top of which e-mails are sent when (important for when we pass this on to FFEC, especially if they ask to modifiy them).

**Comment by paul121** [comment]
We've got a simple first pass at emails. It sounds like there will be some follow up changes. lets create new issues as needed:
- Only send emails when first created or status changes
- Add emails/permissions fields to determine who gets email (currently only the admins get emails)
