### ISSUE TITLE
Break column_descriptors filter into separate filter for each column

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#305]
Follow up from #279

**Comment by paul121** [comment]
![Screenshot from 2022-10-18 23-23-22](https://user-images.githubusercontent.com/3116995/196612739-062b0c90-39ec-4a58-bc5b-32df1d7206b2.png)

**Comment by paul121** [comment]
@aislinnpearson I just realized I may have taken this a step further than the issue title was suggesting. I've broken the filters down to each column, not just the column type. See screenshot above.

I'm assuming this is what we were wanting... if we break it down by column_type there could still be many options in a single filter.

I also recall that we discussed only including some of the column_types as available filters, eg: only the statistical columns need to be included here. Does that ring any bells @aislinnpearson ?

**Comment by paul121** [comment]
I'm going to move forward with this as filters for each column. There would be some issues having it grouped by column type anyways. I think I created this issue too quickly in the moment to give it a proper title/description

**Comment by paul121** [comment]
Of course @aislinnpearson let me know if you see any issues with the above screenshot!

**Comment by aislinnpearson** [comment]
Looks amazing - happy for you to close this issue as per our discussion. Thanks Paul. :)

**Comment by aislinnpearson** [comment]
HI @paul121,

So I just tested this and found a small bug. It seems that we get a blank column when uploading experiments. It seems to happen for all experiments (or, at least, the two I tested):

![image](https://user-images.githubusercontent.com/16349781/198244814-03d1d303-efce-485c-939b-4c878e9ce293.png)

This is the same experiment loaded into the current version of FarmOS (the exact same files) but the added column isn't there: https://rothamstedfarm.farmos.net/plan/15/plots

**Comment by paul121** [comment]
Thanks @aislinnpearson ! This was an easy fix :-)
