### ISSUE TITLE
Let users choose filter logic for column descriptors

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#306]
After #305

Let users choose `AND` or `OR` logic when applying multiple column descriptor filters

**Comment by paul121** [comment]
We decided we don't need this. #305 added separate filters for each column descriptor. Each filter has an `OR` between all the values. All of the filters use an `AND` between them. So you can do a query like: `plots where ( (nutrition is 1, 2 or 3) AND (fert is 1, 2 or 3) )`

We do not think there is an immediate need to do an `OR` query across column descriptors. This would also need some complex UI.

**Comment by aislinnpearson** [comment]
Thanks for this Paul! :)
