### ISSUE TITLE
Cannot prepopulate assets into quick form

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#307]
![192270476-e758eb9d-ff23-4bd0-8fa5-08276f59bdaa](https://user-images.githubusercontent.com/3116995/192619018-ea979515-fef4-4726-b5b3-c531f496d987.png)

>  I wanted to submit a record for plots in an experiment. I went through the normal route of selecting plots in the experiment module, filled in the operations quick form and when I went to submit, I got the below:

Hmm I am seeing this now as well.. The `location` is disabled when the form is initially loaded, but then appears again when the form is submitted. Notably it happens without uploading a file, so might be unrelated to other things we are chatting about here.

_Originally posted by @paul121 in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/297#issuecomment-1258278365_

It seems that we are losing the "state" of which assets are prepopulated. When submitting the form it sees that none are prepopulated, so it is expecting a `location` and `asset` checkboxes to be selected.

**Comment by paul121** [comment]
Notably this happens without uploading a file. So this is largely unreleated to what we were seeing in #297

**Comment by aislinnpearson** [comment]
Hi @paul121 I was speaking to Chris about this today and he says it happens every time they submit a quick form (I previously thought it was only happening when there was an error entering data). Reading your issue request above I think you already caught this, so including it more as a correction to my original post.

**Comment by paul121** [comment]
My somewhat temporary solution for this is to revert a behavior I added to farmOS core earlier - auto removing prepopulated entities in quick forms: https://www.drupal.org/project/farm/issues/3269543

I think it is possible that this is a more general bug in farmOS core at the moment. What I just don't understand is *how was this working earlier??* I can't imagine I never submitted a form during my testing.

So, the unfortunate aspect of this is that we need to add a button to "Clear prepopulated" assets. Otherwise, if a user starts to prepopulate a form, but never finishes, then the form will remain in the prepopulated state. This isn't the end of the world but it's going to bug me until we make it better!

@aislinnpearson if you could test this as well and close issue if all is well - you should be able to prepopulate from the Experiment plots page and any plant asset table!

**Comment by aislinnpearson** [comment]
Hi @paul121,

So I actually really like the 'clear prepopulated' button (I think I would call it 'clear selected' but that is a minor point). The reason I like is so much is that I can add stuff to the taxonomy (in this case the log categories), press refresh and now the new categories are there _but_ I don't lose the prepopulated information. If anything, from a user perspective, I'd prefer that behaviour and would like it from the whole form. I don't think there is an issue for this actually, but it would be in addition to a feature such as #95. However, I do see why it is annoying that you can't clear this selection - I couldn't do that when re-opening the quick form on the test version.

I have to caveat this though in that I couldn't actually submit a test form - I couldn't for the life of me add equipment. The usual 'group' option was missing from the bulk actions and I know you told me there is another way of doing it, but I can't remember what it is. Maybe we can run through this in the call today.

**Comment by paul121** [comment]
> I have to caveat this though in that I couldn't actually submit a test form - I couldn't for the life of me add equipment.

Ah shoot, I forgot to enable our testing module. It populates testing values for a lot of things (equipment, taxonomy, plant & land assets...). Done now

**Comment by paul121** [comment]
> However, I do see why it is annoying that you can't clear this selection - I couldn't do that when re-opening the quick form on the test version.

I've fixed this! Sorry about that. Will be on the demo site shortly.

**Comment by aislinnpearson** [comment]
This is now working. :)
