### ISSUE TITLE
Feature Request: Bulk action for log categories

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#309]
Following issues #160 and #288 please can we also have a bulk action at the bottom of the quick forms which allows us to assign logs to a specific log category.

This is especially important for North Wyke, where there is a backlog of logs that need to be assigned a log category

**Comment by paul121** [comment]
@aislinnpearson pointed out today that we do not currently have an easy way to filter to logs *without a category*... that will be a requirement for this.

Adding this capability to farmOS core could be complicated. @mstenta suggested we create a simple log view for this purpose. I will do that as part of this issue and then we can remove the view later when no longer needed.

**Comment by paul121** [comment]
I've created a bulk action PR to farmOS core https://github.com/farmOS/farmOS/pull/590 . If it doesn't seem like this will make it in for our next release ~2 weeks I can include the action in our code base as well.

**Comment by paul121** [comment]
I've added a view of uncategorized logs at the path `/logs/uncategorized`

**Comment by aislinnpearson** [comment]
Thank you @paul121

**Comment by paul121** [comment]
This will be included in the next farmOS release coming soon so I think I will close this issue for now.

**Comment by aislinnpearson** [comment]
Hey @paul121,

was this meant to be in the release @mstenta just did? I can't find it on the Harpenden instance...

**Comment by paul121** [comment]
Hey, yes it should be there now!

Uncategorized logs: https://rothamstedfarm.farmos.net/logs/uncategorized

And on this page (or any page with logs) you can select the "Categorize" action after selecting log checkboxes
