### ISSUE TITLE
Add seed dressing field to drilling logs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#311]
Currently these are saved to the notes

![image](https://user-images.githubusercontent.com/16349781/192821272-e141ee7f-68e1-4b49-abaf-395235eae06b.png)

**Comment by aislinnpearson** [comment]
Following discussion last night we agreed that the seed dressing would be saved as a custom field, given the drilling quick forms are custom to Rothamsted anyway. The other option discussed was to save it as a quantity with zero value, but was decided against.

**Comment by paul121** [comment]
Done! I've also added an update hook to copy from the "Seed dressings: One, Two, Three" of previous drilling log submissions.

**Comment by aislinnpearson** [comment]
HI @paul121,

I tested this and it works really well if you add one or three seed dressings... but I also noticed a minor correction we will need to make at some point.

Seed dressings don't have rates associated with them - the are just applied to the product when you purchase it. So adding a seed dressing field works well because it is not a quantity. The below implementation in this test log is perfect: https://rothamstedfarm.farmos.net/log/6441

![image](https://user-images.githubusercontent.com/16349781/204561158-820cbe75-a788-46d2-8bb0-c585c7d037ed.png)

However, I noticed that you can also select seed dressings as product, and when you do this the data standard is different: https://rothamstedfarm.farmos.net/log/6442

![image](https://user-images.githubusercontent.com/16349781/204562045-efed6254-531e-46c1-8387-0469f0b91ee6.png)

I've added this as a new issue (#344), in case we ever need to address it (this may actually be a useful feature for when we _do_ know the application rates, although the data standard would still be different)
