### ISSUE TITLE
Experiment Module: Replace 'Field Locations' with location asset reference

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#314]
In issue #259 we added location to the experiment upload form, and as a follow on issue I was wondering if we could replace the data field 'field location' with this location asset.

**Comment by paul121** [comment]
Done! I've changed the field type with an update hook. I've also updated the experiment upload form to set populate the `location` field of the plan.

@aislinnpearson worth noting that I did not include a migration for this change. It would be hard to ensure we got everything right so I would rather leave it to you if that's OK.

**Comment by aislinnpearson** [comment]
> @aislinnpearson worth noting that I did not include a migration for this change. It would be hard to ensure we got everything right so I would rather leave it to you if that's OK

Thanks Paul - I'll make a point to change them over once we push this milestone.

**Comment by aislinnpearson** [comment]
> Thanks Paul - I'll make a point to change them over once we push this milestone.

This is done. :) 

@paul121 one quick question so I can remember to add it to the documentation: if I add a location when uploading the plots does this asset appear on both the plan and the experiment boundary, or just the boundary? Mainly asking out of curiosity because I didn't get the chance to upload any new experiments.

**Comment by paul121** [comment]
It will appear on both!

And to clarify what this means... the "Location" entered in the form will 1) be saved to the Plan "Field locations" data field and 2) be used as the "Parent location" for the experiment boundary asset that is newly created.
