### ISSUE TITLE
Quick Forms: Save locations to log location

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#315]
Following #260 it seems we no longer save the location _as well as_ the plant asset in the logs. Please can we 

- [x] update this so that both are saved
- [x] write an update hook to make sure all logs also reference the location associated with the plant asset.

Duplicate issue: 
- https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/263

**Comment by paul121** [comment]
Done. We don't need an update hook for this because we are already saving the asset's current location to the log location field.

**Comment by aislinnpearson** [comment]
This issue can be pushed although I noticed that for plot assets we don't save the experiment boundary and I wonder if we should? This is not a must fix issue as I notice that all logs (those associated with plot assets and experiment boundaries) are grouped together under the plan assets, it just means that if I click on an experiment boundary I can't see the logs associated with all the child assets. We may want to address this in future, so I created a separate issue here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/327
