### ISSUE TITLE
Bug: file validation error does not prevent form submission

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#318]
When uploading an experiment into the 2.7 platformish site I got an error telling me the last row of the column levels csv wasn't populated (although it was and the expriment uploaded any way). I was able to reproduce the same error in the Harpenden instance:

![image](https://user-images.githubusercontent.com/16349781/194017703-edca33a5-246e-4649-9c14-e23929b0b32f.png)

The error again didn't stop me uploading the experiment, which is here (with the upload files): https://rothamstedfarm.farmos.net/plan/11

Even more bizarrely, it looks like there is a column descriptor which wasn't uploaded properly:

![image](https://user-images.githubusercontent.com/16349781/194017948-e0aec277-94a3-4eff-b49e-4b3077809d59.png)

But as far as I can tell they are all accounted for.

**Comment by aislinnpearson** [comment]
I have figured this out @paul121 - it happens when there are blank rows where once there was text.

For example say you add a couple rows, then change your mind and delete the contents in excel. If you don't delete the rows themselves, it's like there is a memory of the data that was there that the farmos upload picks up on. I think it's an excel issue, because I remember having the same issue with R in the past.

**Comment by paul121** [comment]
> I have figured this out @paul121 - it happens when there are blank rows where once there was text.

Thanks @aislinnpearson. I'll keep this issue open to fix a related issue that these validation errors do not prevent you from submitting the form & creating the experiment. It seems like this may be related to the `managed_file` element and how it manipulates `$form_state`.

**Comment by paul121** [comment]
> It seems like this may be related to the managed_file element and how it manipulates $form_state.

Ah ended up being easier than this. Adjusted the logic to ensure all the files are validated again on the final form submission.

**Comment by aislinnpearson** [comment]
Note to self: the fix that Paul created means you can't upload csv files where there was historically data. Those blank rows need to be deleted in order upload the file. This should go in the documentation (with an example for WGIN 2023)

**Comment by paul121** [comment]
@aislinnpearson could you email a file that has this issue? I wonder if there is a different way we could export/save to ensure these rows are not included from excel. I imagine someone has figured this out.

**Comment by aislinnpearson** [comment]
Done. :)
