### ISSUE TITLE
Bug: Quantities (General) CSV Download Not Working

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#319]
Hi @mstenta and @paul121,

We noticed an issue today which I think relates to FarmOS core in that you can't download quantities from Records - Quantities - Overview. It gives the below error:

![image](https://user-images.githubusercontent.com/16349781/195565049-0fe71634-5bbb-4ba4-8c09-6eb2fa6074e2.png)

Initially we thought this was because we were trying to download so many quantities at once so we narrowed the date range, but got the same error. You can however download quantities over the same time period from the 'Materials' and 'Standard' tabs.

I added this to a milestone for FarmOS core issues, but please let me know if it is a Rothamsted module issue and we can find a more appropriate way to schedule it.

**Comment by mstenta** [comment]
Huh that's interesting. Here is the more detailed error in the log:

```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "A" plugin does not exist. Valid plugin IDs for Drupal\farm_entity\QuantityTypeManager are: material, standard in Drupal\Core\Plugin\DefaultPluginManager->doGetDefinition() (line 53 of /opt/drupal/web/core/lib/Drupal/Component/Plugin/Discovery/DiscoveryTrait.php).
```

**Comment by mstenta** [comment]
Oops... and if I try to replicate without any filters I get:

`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /opt/drupal/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php on line 484`

**Comment by mstenta** [comment]
And I'm able to replicate the issue you encountered @aislinnpearson by filtering down to just 1 month of quantities.

So it seems like two different issues:

- One is a bug (`The "A" plugin does not exist.`)
- The other is a performance consideration: it isn't possible to export ALL quantities because there are too many.

If I remember correctly our CSV exporters in v1 used a batch operation to export large sets, so I guess we need to look into that for v2 (assumed it did that already I guess).

As for the bug, I'm not able to replicate this on other farmOS instances, so I wonder if there's something different about this one. :thinking:

**Comment by mstenta** [comment]
One thought I had was maybe some quantities were being saved to the database with an invalid type... but the results of this query I ran look correct:

```
select type from quantity group by type;
   type   
----------
 material
 standard
(2 rows)
```

I'm a bit stumped... @paul121 any ideas what might cause this?

**Comment by paul121** [comment]
Very weird indeed..

I'm curious for the "A" quantity type, can you check what the actual link
is for the "Export CSV"? Maybe that is being generated incorrectly and has
a malformed "quantity type" parameter in the URL.

**Comment by mstenta** [comment]
Ah ha... good question @paul121 ... here is the path:

`/quantities.csv?log_name=&label=&value_min=&value_max=&units=All&measure=All&type=All&log_timestamp_start=2022-09-01&log_timestamp_end=2022-10-31&log_status=All&log_type=All&items_per_page=50`

If I copy and paste that into another farmOS instance, I get the same error.

It must have something to do with `type=All`! If I remove that, I get the CSV. :-)

So this is in fact a farmOS core issue. I think we can just move this issue over to the `farmOS/farmOS` repo, unless you would prefer to keep it here and open a new one?

**Comment by paul121** [comment]
> I think we can just move this issue over to the farmOS/farmOS repo, unless you would prefer to keep it here and open a new one?

How about a fix to farmOS core? :smiley: https://github.com/farmOS/farmOS/pull/584

Also I think we still have a second issue re: the performance consideration. Maybe we can keep this issue open to track that.

**Comment by aislinnpearson** [comment]
Hi Both,

Thanks so much for this. There was no way I could have figured this out! :)

We usually keep two issues @mstenta - one for FarmOS core, and one here so both I can keep track and update people on their requests. I don't think Paul and I have ever formally agreed this, it just worked out that way. Good to know you can transfer issues though.

> Also I think we still have a second issue re: the performance consideration. Maybe we can keep this issue open to track that.

Reading the above thread I assume that is also a core issue? Let me know if not and I'll create a separate issue here. Otherwise I'll leave this one issue in and will remove you both as assignees, as really it's just a monitoring issue.

**Comment by mstenta** [comment]
> How about a fix to farmOS core? https://github.com/farmOS/farmOS/pull/584

Merged! :-)

**Comment by paul121** [comment]
This should be fixed now
