### ISSUE TITLE
Experiment Module: Migrate contacts to a user reference field

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#322]
The current experiment module has a 'people' tab, where we can:

1. Add multiple principle investigators
2. Add multiple data stewards
3. Specify the statistician
4. Specify a primary and secondary contact, along with their e-mail addresses 

However, in order to create a user for scientists (#76) these need to be migrated to a user reference field. There are several steps in this process:

- [x] Convert the text field for primary and secondary contacts to a user reference field that allow you to find and select multiple farmOS users (**Paul**)
- [x]  Delete the existing data fields for principle investigator, data steward, statistician, primary contact, secondary contact and associated e-mails (**Paul**)
- [x] Create users and re-assign to experiments* (**Aislinn**) 

* We previously discussed writing an update hook for this, but as there are so few experiments and I need to change people's permissions, I'll just do this manually
 
This is also related to issue #116 _but_ currently only managers can see contact details so this is not a priority issue

Images of the current people tab on the experiment module for reference:

![image](https://user-images.githubusercontent.com/16349781/197485513-0cff8447-d386-49a8-9cb2-a352d2ffbda5.png)
![image](https://user-images.githubusercontent.com/16349781/197485593-104ab5c2-2b5d-46c2-a5bf-2d5fdc692222.png)

**Comment by aislinnpearson** [comment]
I've tested the functionality in terms of adding people to an experiment and it works perfectly:

![image](https://user-images.githubusercontent.com/16349781/204567056-84617b89-caa4-4591-a312-6804bdeb8feb.png)

But I can't test editing rights for sponsors until chatting through #76 with you @paul121/ @mstenta 

Re-opening it with this comment just so I don't forget to do that testing once we resolve #76

**Comment by paul121** [comment]
Chatting today we talked about turning the single `contacts` field into separate fields for each type of contact eg: primary investigator, secondary, data steward, statistician, etc.

@aislinnpearson once you have tested this current functionality could you open a new issue for the above?

**Comment by aislinnpearson** [comment]
Hey @paul121,

I tested this and it all seemed to work really well. There's a few visualisation bits that are confusing - like being able to see the Quick Forms button but not submit any quick forms - but these feel very minor for a first version, especially as we might create an observation quick form at some point.

The one thing I did notice is that I can't add quantities to the observation log... let's chat about it this evening and then hopefully I can close this (it is done, just to check if this needs a new issue).

> Chatting today we talked about turning the single contacts field into separate fields for each type of contact eg: primary investigator, secondary, data steward, statistician, etc.

I did come up with a solution to this, but I think it is part of #298 - let's definitely chat about it this evening.

**Comment by paul121** [comment]
> The one thing I did notice is that I can't add quantities to the observation log... 

See #347

**Comment by paul121** [comment]
> I did come up with a solution to this, but I think it is part of https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/298 - let's definitely chat about it this evening.

I agree this is a part of #289. We decided it will be easier to add these user metadata fields to the `user` entity (people's page) instead of one-off fields on the plan. So all "team members" will be added into farmOS as users, although some may not have permissions. This is the easiest way to capture this information for everyone in one place!
