### ISSUE TITLE
Experiment Module: Change the way experiments are uploaded

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#323]
Currently new experiment plans are created by uploading two excel files (one for columns, one for column levels) and a geoJSON with plot annotations. The only other required data fields are the experiment name, experiment code and field location.

In future we want the Sponsors (scientists) to be able to provide a minimum amount of information, which can be used for discussion in the experiment planning process. The minimum information needed is:

1. Experiment name (required)
2. Experiment abbreviation (preferred)
3. Project code (preferred)
4. Cost code (preferred)
5. A description of the experiment (required)
6. Hypothesis (required)
7. Crop(s) (required)
8. Statement on confidential treatments (required)
9. Statement on genetically modified crops (required)
10. Statement on genetically edited crops (required)
11. Statement on off-label products (required) 

This is all part of a larger set of metadata (see #298), where the sponsor would initially provide as much information as possible,  but the important thing to note is that the process for creating an experiment is very different, and should probably be more akin to that of creating a new asset, where all the data fields are visible. 

We may also want to change the way the columns and column levels are uploaded so it is more akin to #276 (and that parent's child issues #290 and #291)

**Comment by paul121** [comment]
This is done! Some of the minimum information above may be out of date. See #358 for the latest changes there.
