### ISSUE TITLE
Brooms Barn: migration to 2.8.x

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#330]
The Brooms Barn transfer to 2.x. will hopefully happen in the week of the 7th November. Having discussed this with Mike and Paul, Brooms Barn will be *starting* on 2.8.0, so farmOS will NOT run any of the 2.x update hooks - because it isn't updating from a previous 2.x version. The "update" from v1 to v2 is actually a "migration" not an "update" - so update hooks in the 2.x code do not run.

Below is a checklist to cover during the migration, which we will want to make live _before_ 2.9.x is made live

- [ ] Update to current version of FarmOS (2.x.x)
- [x] Review any "update hooks" necessary to run after updating from an old version (probably be as simple as running a couple of Drush commands manually).
- [ ] Arrange training in the new version for the farm team at Brooms

Feel free to edit this @mstenta and @paul121 - not entirely sure I have it all correct. :)

**Comment by paul121** [comment]
I've just done a quick pass through all of the `farm_rothamsted_*.post_update_*` update hook implementations... I don't think there are any relevant to this migration.

Many of our update hooks simply add new config, and there are only a couple that update logs submitted from previous 2.x quick forms. I labelled the relevant issues with update hooks and will try and do this going forward: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues?q=is%3Aissue+label%3A%22Update+Hook%22+is%3Aclosed

**Comment by mstenta** [comment]
Oh that's great! Thanks for reviewing @paul121! So it sounds like we don't need to worry about update hooks, and we can just perform the migration like normal.

**Comment by mstenta** [comment]
@aislinnpearson Do you have a specific date in mind you would like to target for this? Would you like to _start_ the week of the 7th on 2.x? Or migrate _during_ the week?

**Comment by aislinnpearson** [comment]
Complete by Mike on 26/ 11/ 2022
