### ISSUE TITLE
Remove plots from dashboard

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#334]

**Comment by paul121** [comment]
This is fixed via #336 by changing the `asset.type.plot` config entity to have `third_party_settings: farm_location: is_location: false`

**Comment by aislinnpearson** [comment]
This works for the Harpenden instance (the only one where we have plots so far):

![image](https://user-images.githubusercontent.com/16349781/204567675-3b36fc8c-9bd4-46e9-9eee-db3d65fccfdd.png)
