### ISSUE TITLE
Experiment Module: Change plot assets to not default as locations

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#336]
Update plot assets so they are no longer locations by default. We will need an update hook to change this. The reason behind this decision is that the visualisation of these plots in the maps on the locations tab is probably contributing to a 'slowing down' of FarmOS (for example, when trying to load maps on the plans), although we identified several other issues which were also likely to be slowing the processing speed, some of which had to do with broadband/ wifi connection speeds.

This will also remove plots from the location hierarchy.

See also #339

**Comment by paul121** [comment]
This should fix #334

**Comment by aislinnpearson** [comment]
HI @paul121, @mstenta,

I think this partially fixed our problem.

When I went to try and load Meadow (the field with several thousand plots) on Monday I had the same problem: the experiment areas wouldn't load. Today I then went through and deleted the previous versions of WW/2302 when it timed out (see #335) I deleted over six thousand plots from the failed uploads. After this, the experiment boundaries under Meadow on the quick forms appeared.

Using this comment to re-open the issue just so we remember to discuss it this evening, and if any further work is required.

**Comment by paul121** [comment]
Chatting today we identified that there still is an issue in the quick forms when searching for assets via locations. When there are many thousands of plots this is slow to load, but not slow without the many plots.

Closing this issue but I've opened a new issue to work on this #345
