### ISSUE TITLE
Experiment Module: Edit plot geometry

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#337]
We encountered a problem last week where we wanted to move all of the plots within an experiment by about 2m. As the experiment had >40 plots this would have been very time consuming to do on a plot by plot basis, so we ended up deleted and re-uploading the plan. Nonetheless it raised the issue that there is no way to edit a number of plot geometries (which would ideally record a revision on a plot level)

We discussed this in the call on the 8th November but with no obvious simple solution. A sub-issue of parent #290 and is closely linked to #275 (uploading plot attributes as a csv).

Marked as 'must do' because we are redesigning the meta-data for this experiment and this is part of that process #298, but it is a relatively rare occurrence that we need to change the location of the plots.

**Comment by paul121** [comment]
This is done
