### ISSUE TITLE
Quick Forms: Plant Assets not loading

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#342]
There is an error on the Harpenden instance where the experiment boundaries aren't loading in the quick forms for agricultural fields where we have a lot of plot assets. The main example is Meadow, where we should have a number of experiment boundaries but none are displayed:

![image](https://user-images.githubusercontent.com/16349781/202683943-8efd5ec0-bf76-4a26-926c-5262fae654a3.png)

Talking this through with Mike and Paul, this is probably because of the complexity of the search which looks for structures and plant assets associated with that location as well as any children or grand children locations, where the complexity is finding movement assets associated with those assets within a location. We think this might be resolved via #336 but aren't sure as plots are excluded from the search query.

I have included a follow up issue here in case the problem is not resolved by the 2.9.x release in which case we might need to think of other options. One suggestion was to add a caching layer for location, with the suggestion that is this something we may need to do anyway given the amount of geometry associated with the project.

**Comment by paul121** [comment]
@aislinnpearson I believe this should have been fixed with v2.9.2. Could you try again?

**Comment by aislinnpearson** [comment]
Hi @paul121 

Yes, this works. Sorry - I'll close it with this comment
