### ISSUE TITLE
Quick form locations slow to load with many plots

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#345]
When I went to try and load Meadow (the field with several thousand plots) on Monday I had the same problem: the experiment areas wouldn't load. Today I then went through and deleted the previous versions of WW/2302 when it timed out (see #335) I deleted over six thousand plots from the failed uploads. After this, the experiment boundaries under Meadow on the quick forms appeared.

_Originally posted by @aislinnpearson in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/336#issuecomment-1330728672_

**Comment by paul121** [comment]
Indeed the plots were still being included in a sub-query to get all assets moved to child locations. Removing plots from this sub query fixes the issue. Changing plots to not be locations was not sufficient because for legacy reasons we do include "non location" assets in the sub-location query.

**Comment by aislinnpearson** [comment]
Thanks Paul. That sounds like a tidy fix
