### ISSUE TITLE
Experiment Module: Editing Plot Geometry

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#352]
Following on from #337 we agreed that, for the experiment module MVP, editing the geometry associated with the plots would have to be done manually. This also includes adding and deleting geometry. The current workaround for this is simply to delete and reupload the plans.

That said however, there are occasions when plots uploaded are in the wrong place. We may also want to give people the option to add and delete (or archive) plots. To this end we initially suggested that: 

**Deleting Plots:** This would require high level administrative access (ideally plots should be archived, not deleted - _especially_ if they have logs associated with them).

**Adding Plots:** 
1. The plot_number for each experiment must be unique (giving each plot a unique id). So, if you have already uploaded an experiment with a plot_number 1, you can't upload a new plot with that same plot_number _unless_ the previous one has been deleted (i.e. this needs to be checked against archived plots as well as live plots).
2. If you are adding or deleting plots you must, by default, re-upload all the three csv files that define the columns, column levels and plot attributes

**Comment by paul121** [comment]
We have added the ability to Add + Edit plot geometries via #337 

> Deleting Plots: This would require high level administrative access (ideally plots should be archived, not deleted - especially if they have logs associated with them).

We have not added a feature for deleting plots. I've created a new issue for this: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/382
