### ISSUE TITLE
Mismatched entity and/or field definitions for Column descriptor(s) field

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#353]
After a recent update (forget which one exactly, but could probably figure it out), I started noticing the following in the Drupal status report:

> Mismatched entity and/or field definitions
> The following changes were detected in the entity type and field definitions.
> 
> **Plan**
> 
> - The Field Location(s) field needs to be updated.
> - The Column descriptors field needs to be updated.

Notably, Rothamsted shows both the "Field Location(s)" field and the "Column descriptors" field, but Northwyke only shows "Column descriptors".

@paul121 noted in chat that that's a good clue:

> we did have an update hook for the plan.location field, "Field Locations" in that error message
> so northwyke prob installed after/without the update hook

But he noted:

> re: column descriptors... not so sure. I don't think we've had an update hook changing that field

We've experienced this kind of error message before, with the `client_id` field on `consumer` entities in farmOS core, which were fixed by simply running:

```
$man = \Drupal::entityDefinitionUpdateManager();
$field = $man->getFieldStorageDefinition('client_id', 'consumer');
$man->updateFieldStorageDefinition($field);
```

A similar attempt did not resolve the "Column descriptor(s)" field. I didn't try to "Field Locations" field.

This doesn't appear to be causing any issue, so it doesn't seem urgent, but it would be good to figure out and fix.

**Comment by mstenta** [comment]
> I didn't try to "Field Locations" field.

Update! I ran the following code on Rothamsted and it fixed the "Field Locations" field!

```
$man = \Drupal::entityDefinitionUpdateManager();
$field = $man->getFieldStorageDefinition('location', 'plan');
$man->updateFieldStorageDefinition($field);
```

So it's just the "Column descriptor(s)" field that needs to be fixed... I will update this issue's title accordingly.

**Comment by aislinnpearson** [comment]
Okay, thanks @mstenta/ @paul121. If it is a fix that can wait then maybe we can add it to the 2.11.x milestone? Currently only has a couple open issues... let me know if you think it needs to be prioritised before then though? The technical aspect of this is a bit lost on me. :)

**Comment by mstenta** [comment]
I think waiting is OK - it seems to be working fine, so I think the risk is low.

**Comment by paul121** [comment]
Hunting this down some... we provide two `column_descriptors` fields.

On Plot assets this is a `key_value` field type:
https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/13c96ae97ec883bf3fb418c1c44eee1f49d2fd32/modules/farm_rothamsted_experiment/src/Plugin/Asset/AssetType/Plot.php#L71-L75

On Experiment plans this is a `json_native` field type:
https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/13c96ae97ec883bf3fb418c1c44eee1f49d2fd32/modules/farm_rothamsted_experiment/src/Plugin/Plan/PlanType/Experiment.php#L173-L179

I believe this is related to this open issue in the json_field module: https://www.drupal.org/project/json_field/issues/3294831

**Comment by paul121** [comment]
> I believe this is related to this open issue in the json_field module: https://www.drupal.org/project/json_field/issues/3294831

That issue references this issue, which changed the schema for the `json_native` field type we are using (see [commit](https://git.drupalcode.org/project/json_field/-/commit/b62621b)) and was included in a 1.0 release October 10, 2022: https://www.drupal.org/node/3252426.

**Comment by paul121** [comment]
I've recreated this by installing farmOS w/ drupal/json_field v1.0-rc4. Updating to drupal/json_field v1.0 adds the message to status report.

**Comment by mstenta** [comment]
Thanks for digging into this @paul121! I've reviewed the upstream issues, and it doesn't look like there is any risk from this "error". The JSON Field module maintainers need to clean up after the change they made for SQLite3 databases, which does not affect us. I think we can just wait for them to fix this, without spending our own time/resources on it. We can safely assume that will happen on its own, and this error will go away when it does.

@aislinnpearson I think we can close this issue as "not planned".
