### ISSUE TITLE
Experiment Module: 'Programme' Entity

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#355]
Create an entity for collecting metadata about research programmes. See https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/298#issuecomment-1411784802

**Comment by aislinnpearson** [comment]
Hey @paul121,

Just tested this and found the following issue which seems to relate to the way the dates are entered and formatted? 

The other thing I realised is that you _have_ to have the researchers listed in order to submit a programme but that is okay. We can work that in with the farm workflow (in the same we would need someone to email our farm staff in order to be added to the old fieldnet system).

All in all, it seems to work really well. Once we sort the date issue I am happy for this to be closed.

![image](https://user-images.githubusercontent.com/16349781/221177199-3a827c13-d029-4a4a-a026-5a72bf2ce5d3.png)
![image](https://user-images.githubusercontent.com/16349781/221176848-0c455b20-19b0-41b0-8154-5070ab8f70b4.png)

**Comment by paul121** [comment]
Yes, thanks for mentioning this. I've changed this so it will only show the date selector.

But FYI in the future @aislinnpearson it is just asking for you to provide a time here. I know we haven't specified that these start/end dates need a time... it's just that it's easier for me to use a `timestamp` field in the database for these values. Improving the UI means no one will even know that the time is included (defaults to 00:00).

We're working on this in farmOS core for a few other things as well. In particular we want to make it easier to only provide a date when a field can also accept a time. A good example is an animal birth date.

**Comment by aislinnpearson** [comment]
@paul121 thanks for explaining! 

Until we update the UI, I wonder if we should (a) include a note to say 'please set the time to 00:00:00' and/or make them compulsory fields, so people don't encounter the error? Maybe you could check I interpreted this properly though... I'm not sure I have looking at your changes.

I've created a monitoring issue for FarmOS core here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/355#issuecomment-1445700948

I did also go through this entity with a fine tooth comb, as well as adding the form validation logic. Again I'll add an updated excel spreadsheet later today but for now a screenshot of the discrepancies I noticed:

![image](https://user-images.githubusercontent.com/16349781/221574005-f73626fa-9d6e-4327-a8a5-905e3cb1eb11.png)

**Comment by paul121** [comment]
>  I wonder if we should (a) include a note to say 'please set the time to 00:00:00' and/or make them compulsory fields, so people don't encounter the error? Maybe you could check I interpreted this properly though... I'm not sure I have looking at your changes.

I did remove the `time` input so users can only enter a date. But yes, now I see two separate things: 1) the descriptions are configured, but they aren't appearing! 2) The current description is incorrect about the desired format is incorrect without the `time` input. Will also work on allowing 1800s - hadn't noticed this either.

Thanks for including that spreadsheet. For funders, would it be OK if we kept this as a simple text field? And in the description ask for users to include the grant code? This is one of those "compound" items that's hard to include without creating another entity.

**Comment by aislinnpearson** [comment]
Hey @paul,

For the funders we could create a 'select multiple' list (I just need to get a list of names for you) and then a short text field for one or more grant codes? If you think that works, it would help us standardise the data slightly more than just a text box... 

I had a meeting this afternoon, but the experiment bit is almost good to go and then I will try to get around to the design later this evening. Let me know if this format works for you, or if there is anything I can do to make it easier.

Thanks for doing all this minor checking with me. :)

**Comment by paul121** [comment]
> If you think that works, it would help us standardise the data slightly more than just a text box...

Yep, absolutely! That sounds great.

**Comment by paul121** [comment]
Okay I've corrected the dates (remove time input, add description, and set desired dd/mm/yyyy format). I also added the funders and grant codes fields. @aislinnpearson let me know on the list of funders and I can button that up.

@aislinnpearson on another note I'm curious what the `date` form input looks like for you.. Ideally it would be the dd/mm/yyyy format. Because this is in the form (not the display) this is something that the browser should take care of. Most browsers should detect your language/locale/region and set the format appropriately. I tried modifying my browser and system language/locale settings but couldn't get it to change. See screenshot below for how it appears in my browser (chrome):

![Screenshot from 2023-02-27 15-34-35](https://user-images.githubusercontent.com/3116995/221714778-12088e2a-07a4-437b-a90f-b7393bc87d76.png)
![Screenshot from 2023-02-27 15-34-20](https://user-images.githubusercontent.com/3116995/221714781-2cf2d929-dbbc-46ea-932b-70b5f9115d83.png)

**Comment by aislinnpearson** [comment]
Hey @paul121,

Thanks for making those changes. I only have one more and then we can close this issue:

The project code doesn't need to be a required field (the validation criteria I have at the moment is the bare minimum - for example, I can see a situation where the scientists don't know the project code but want to create programme... I'll look into the complexities of this when we get to #324). 

I think that is it though - then we can sign this entity off as well. I'll list these things out properly for the other issues so it's a bit clearer as well.

> I'm curious what the date form input looks like for you.
It looks correct - thanks for checking it so rigorously:

Before submission for 31 January 1853:
![image](https://user-images.githubusercontent.com/16349781/221896175-ca15d389-a638-4f21-a7d1-fbf16f24cf09.png)


And after submission:

![image](https://user-images.githubusercontent.com/16349781/221896576-c9b1af4f-657f-4d51-9ac8-ebea221df852.png)

**Comment by aislinnpearson** [comment]
Oh, sorry @paul121 - I also meant to say I've emailed our grants team to ask for a full list of funders. Hopefully they will have one in the next couple days.

So this _and_ that last required field should be the final bits for this entity. :)

**Comment by aislinnpearson** [comment]
Hey @paul121,

Here is the list of funders from our grants team, so we can convert that to a list. Hopefully have the list of stats terms for the Design entity by the end of the week as well.

ADAS;
AHDB;
AHRC;
BASF;
Bayer;
BBSRC;
British Council; 
BEIS; 
CIMMYT;
Defra;
Chadacre Agricultural Trust; 
CHAP; 
Environment Agency;
EPSRC; 
European Commission; 
European Space Agency (ESA);
Foreign Commonwealth And Development Office; 
Foundation for Food and Agricultural Research;
Innovate UK; 
International Potato Centre;
Ireland EPA;
KTN;
Met Office;
Natural England;
NERC;
Norwegian Research Council;
Novo Nordisk Foundation; 
Novozyme;
Syngenta;
The Royal Society;
The Alan Turing Institute;
UKRI;
