### ISSUE TITLE
Experiment Module: Create 'Design' Entity

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#357]
Create an entity for collecting metadata about experiment designs. See https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/298#issuecomment-1411784802

**Comment by aislinnpearson** [comment]
Hi @paul121,

Here are the minor amendments for the Design entity:

**Description Tab:** 
- Add description to 'Experiments' data field
- Design type: needs to be changed to a list (Aislinn to supply a list after hearing back from the stats group)
- start and end year are in the format dd/mm/yyyy - ideally would be YYYY but maybe that's not easy to implement?

![image](https://user-images.githubusercontent.com/16349781/221923004-58ca9d0f-dc8e-4879-9056-6749f33c6d83.png)

**Comment by aislinnpearson** [comment]
Hi @paul121,

Following our e-mail conversation/ discussion with Kirsty and Suzanne here is an updated specification for the **Design Type** field:

**Design Type:** Changed from a data field to a widget
**Blocking Structure:** New data field, which is a parent list for statistical design. The list is:

- Completely Randomised Design
- Randomised Complete Block Design
- Resolvable Block Design
- Non-resolvable Block Design
- Resolvable Row-Column Design
- Non-resolvable Row-Column Design
- Split plot design
- Augmented design
- Not Randomised
- Other

**Statistical Design:** New data field, and the child list for Blocking Structure

Blocking Structure | Statistical Design
-- | --
Completely Randomised Design | Completely Randomised Design   (CRD)
Randomised Complete Block Design | Randomised Complete Block Design (RCBD)
Resolvable Block Design | - Balanced Incomplete Block Design (BIBD), Unequal block design, Alpha Design (AD), Cyclic Design (CD)
Non-resolvable block design | Incomplete Block Design (IBD), Alpha Design (AD), Cyclic Design (CD)
Resolvable Row-Column design | Latin Square (LS), Complete Latin Square (CLS), Quasi-Complete Latin Square   (QCLS), Lattice Square Design (LSD)
Non-resolvable Row-Column Design | See Description
Split plot design | Split Plot Design (SPD), Split Main Plots Design (SMPD), Split-split Plot Design (SSPD), Criss-cross (Strip Plot),   Design (CCD)
Augmented design | See Description
Not Randomised | See Description
Other | See Description

**Additional Blocking Constraints:** New data field. A list of additional blocking constraints. The list is: 

- T-Latinization
- Spatial Standards
- Spatial Design
- Unequal Replication
- Other

As an aside, I have occasionally had experiments which have two (yes two) statistical designs associated with them. Do you think we could make this widget an 'add multiple'? If not, I'll put in a separate issue for the data model that we can address at a later date (it's so rare that this is just a nice to have feature to capture edge cases).

![image](https://user-images.githubusercontent.com/16349781/223172938-e6b460cc-3d9f-4fa6-93d0-54ca389399cb.png)

**Comment by aislinnpearson** [comment]
Hey @paul121,

I have tested everything except the plans, and so far the only major issue I have found is that I can't 'create' designs.

I think it must be something to do with the referencing of other entities. For example, Here I have selected Park Grass as the experiment 

![image](https://user-images.githubusercontent.com/16349781/224054421-e784b5ac-49d7-471a-b8a0-5ede3f1d4b35.png)

And Suzanne as the Statistician

![image](https://user-images.githubusercontent.com/16349781/224054535-0f960497-0e11-44db-85fb-542a30c4cd66.png)

When I press submit I get this error message:

![image](https://user-images.githubusercontent.com/16349781/224053600-b85a9e3d-c8c1-4550-8dd8-459246d8d485.png)

And then those two fields appear blank if I go back to my original submission.

The other thing I noticed which is a **nice to fix** is that you can only reference one design (sometimes two experiments will have the same design for example where the same experiment is replicated in multiple different locations). But we can add this issue to 2.11 and push as a later fix.

**Comment by paul121** [comment]
The above issue was because we changed the name of the `design_type` field and it was failing when sending emails because it was trying to use this name. That issue is fixed and this initial design entity is done!
