### ISSUE TITLE
Drilling and input log quick forms save material quantities

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#359]
@aislinnpearson reported this bug this morning. All quantities submitted from quick forms that create `drilling` or `input` logs are creating `material` type quantities, not `standard` quantities.

This started happening with farmOS 2.0.0-beta8 around ~Nov 25 2022. The change is from this PR https://github.com/farmOS/farmOS/pull/601 where the behavior for creating a quantity without a specified `type` changed: previously `standard` was the default, now we first try the log type's "default quantity type" before defaulting back to `standard` if the quantity type exists. This affected our quick forms because I currently do not specify a default `type = standard`, only `type = material` where necessary.

This should be an easy fix with two parts:
- Add a default `type = standard` for all quantities in our quick form
- Add update hook to correct logs & quantities from submitted quick forms

**Comment by paul121** [comment]
> Add update hook to correct logs & quantities from submitted quick forms

I think we can use the following logic:

- Check for logs/quantities created from the following quick forms: fertiliser and spraying (input logs) and drilling (drilling logs)
- For each log, identify`material` quantities to convert to `standard` if the `label` is one of:
  - All quick forms: Time taken, Tractor hours (start), Tractor hours (end), Fuel use
  - Drilling: Seed rate, Drilling rate, Thousand grain weight (TGW), Seed Germination Test Result, Target plant population, Establishment average, Drilling depth
  - Fertiliser: Machine treated area, Field treated area, Total volume applied, Target application rate
  - Spraying: Harvest interval, Pressure, Water volume, Temperature (C), Wind speed, Area sprayed, Speed driven, Tank volume remaining
- Convert identified quantities...
  - Option 1) Create new quantities and update log to reference new quantities. We cannot delete old quantities because old revisions of the logs will reference the old material quantities. Any issues with this approach? Hopefully those old material quantities wouldn't show in quantity views?
  - Option 2) Do a more more heavy-handed update to truly "convert" the type from these `material` quantities to be `standard`. This is a bit outside my comfort zone but might be the more "correct" option, keeping past log revisions "correct"... looking closer this might not be too hard. I believe we would need to do the following:
      - Update `type` in the `quantity` table
      - Remove rows with matching quantity id from `quantity__material_type` and `quantity_revision__material_type` (just to be safe.. none of these quantities should have a populated material_type reference)
      - Notably: `quantity_revision` `log__quantity` and `log_revision__quantity` look to be OK, no reference to the quantity bundle
      - Do we need to add a revision/revision message to logs? I think not...
  - Looking closer, option 2 seems to be best, but want to run this by @mstenta too
- After updating logs/quantities we might need to clear cache to ensure logs are rendered with correct types

**Comment by aislinnpearson** [comment]
Thank you so much for this @paul121

**Comment by mstenta** [comment]
> Looking closer, option 2 seems to be best, but want to run this by @mstenta too

Yea I think this is safe to do. I've done similar things in the past to convert from one type to another.

> For each log, identify `material` quantities to convert to `standard` if the `label` is one of: 

I wonder, would it be easier to just convert to `standard` if the quantity doesn't have a `material` term reference? Might be simpler than checking all the labels?

**Comment by mstenta** [comment]
> I wonder, would it be easier to just convert

Oh haha you already have a PR opened. :smile: Taking a look now...
