### ISSUE TITLE
Rothamsted Core: Review and document user permissions

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#373]
The FarmOS permissions need reviewing and documenting.

This is especially in relation to the new experiment module now we have added the additional entities (originally a sponsor could create new plans and edit the ones they are associated with – but how does that work with experiments, designs, research programmes, etc implemented in issues #355, #356, #357, #358)? 

Sub-issues:

- [x] #543
- [x] #544
- [x] #545
- [x] #546
- [x] #547
- [x] #548
- [x] Operator (basic)
- [x] Operator (advanced)
- [x] Remove asset/log revert any revision (no one should be able to)

Related issues:

- #366
- #367
- #274 
- #328
- https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/382

Additional considerations include:

- Scientist roles should include Viewer, Editor, Submitter (reproducibility, and similar to grant process so only a PI can submit)
- Data stewards/ admin as new type?
- Limit who can edit revisions (data stewards only or possibly not at all for data integrity)
- Can add logs to a named experiment (and edit logs?)
- Proposal should not be editable after approval
- External users (possibly all scientists) should only be able to see data associated with their experiments (and possibly field history?)

**Comment by aislinnpearson** [comment]
Aislinn to review/ document permissions based on this list:

https://2-10-1-fs545ai-2mu45anerqtvq.uk-1.platformsh.site/admin/people/permissions

**Comment by aislinnpearson** [comment]
Needs to be applied at an experiment level - e.g. a viewer for one experiment might be the editor for another.

Scientist role - ability to submit is when you are listed as a submitter. Anyone who is listed as a scientist. Can also be referenced as a viewer or an editor in other proposals... and would have to apply to experiments with associated designs and plans as well. 

Restricting who can see what experiments includes additional complexities (to be discussed when have more information on how the roles work)

Data Stewards and Statisticians would have to be listed as Resrach editors so can view and edit all trials...

**Comment by aislinnpearson** [comment]
Hey @paul121 

For obvious reasons this link doesn't work any more. Is it possible to set up something similar again? Sorry I didn't get around to using it at the time, but actually it would be really useful for testing

**Comment by paul121** [comment]
One thing to note here - we've specified "view/update own researcher" for researcher entities which means "view/update researchers I have created", but I think we actually want "view/update researchers assigned to my farmOS user".

**Comment by paul121** [comment]
@aislinnpearson here is an updated demo, you should be able to view the permissions page here: https://pr-7-yhhmlra-2mu45anerqtvq.uk-1.platformsh.site/admin/people/permissions

Most of these permissions outlined in sub-issues above should be implemented. One remaining thing is view/update associated logs, as well as the experiment admin needs some updates.

**Comment by paul121** [comment]
Some updates & changes from recent discussions:
- We do not want to use the standard Manager, Worker and Viewer roles. It is hard to add research entity permissions to these roles, will be easier to create new roles.
- Create Farm Manager with full access to all entities
- Create Farm Viewer (previously specified as Research Viewer)
- Create Operator (basic) - this has view access to assets & research, full access to taxonomy, and create/edit access to all of their own logs
- Create Operator (advanced) - this is same as basic operator, except they can create/edit assets as well.
- Restricted viewer (same as specified)
- Reviewer (same as specified... basically a duplicate of the Farm Viewer, but allows access to submit Reviewed Comments on proposals/etc)

Separately:
- #568

**Comment by paul121** [comment]
> We do not want to use the standard Manager, Worker and Viewer roles. It is hard to add research entity permissions to these roles, will be easier to create new roles.

Actually, there is value in re-using these roles. If we create new ones we basically need to do the same altering for permissions. We only need the Manager and Viewer roles, though.

**Comment by aislinnpearson** [comment]
Thank you so much for this @paul121 - let me know when you have a role created/ completed and I can test them as we go (or when they are all done and I'll test them all simultaneously if that is easier for you).

**Comment by paul121** [comment]
Here is the final list of roles we've come to:
![final-roles](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/5fb6af94-66a6-4dce-9cb2-ef3581d90e32)

**Comment by aislinnpearson** [comment]
Notes from email conversation on 19 October:


> I went through all the roles except the Account Admin. I found a few errors and also decided to make a few changes.
> 
> The following roles are all good, no changes required:
> 
> Viewer
> 
> The following have simple(ish) changes:
> 
> Reviewer:
> Research entities: The edit button shows when you have previously edited a research program, research proposal, experiment or design (not true on the plans or experiment researchers). This is a fairly unique problem and I probably only noticed it because I have been changing the user type of the test account so often, but thought I’d mention it as something I had noticed.
> 
> Operator (basic)
> Logs: Please can we revoke the permission to delete own logs (see below comment)
> 
> Operator (advanced):
> Taxonomy: Can only view taxonomy terms. Should be able to create, update and view any (e.g. when adding pesticides, crops, varieties, etc). Sorry – this was a specification error on my part.
> Logs: Please can we revoke the permission to delete own logs and change to only update own (see below comment)
> Assets: Please can we revoke the permission to delete assets (see below comment)
> 
> I’ve then had a long think about how the Manager and Farm Admin roles should differ so they meet the needs of our internal politics. My conclusion is that a manager should be able to create, update or view anything on the system, but they should not be allowed to delete anything (and I’ll follow this up with [an issue that allows various user types to bin something without deleting it](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/573)). Only the Farm Admins should be able to permanently delete items or revert changes. For this reason (and for clarity) I suggest we rename the Farm Admin as the Data Admin, and I’ll restrict this user type to a limited number of data stewards only. Having already accidentally deleted a proposal myself, and seen a few other things mysteriously disappear from Farm OS, these really do need to be trusted permissions I think. The only thing I don’t know is how that fits with the FarmOS core role.
> 
> A summary of what those changes mean in practice:
> 
> Manager: 
> Logs: Please can we revoke all permissions to delete logs, so the new permissions are Create/ Update any/ View any
> Assets: Please can we revoke all permission to delete assets, so the new permissions are Create/ Update any/ View any
> Taxonomy: Please can we revoke all permission to delete taxonomy terms, so the new permissions are Create/ Update any/ View any
> Research module: Please can give them permissions to Create/ Update any/ View any entity with in the research module
> 
> Research Admin:
> Taxonomy: Can currently only view taxonomy terms. Please give permission to create, delete, update and view any (e.g. when adding pesticides, crops, varieties, units, log categories, etc). 
> Research entities: Can’t revert to previous versions on any of the research entities except the plans (this I the only user profile that should be able to revert to previous versions on all entities)
> Rename this Data Admin
> 
> I then also went through the Research Editor and Research Lead and noticed a huge error on my part in that the logs by the farm sometimes cover more than one experiment. So when we give them permission to edit logs they are ‘associated with’ they are also editing the logs associated with other people’s experiments which seems like a massive flaw in the system to me. For this reason I suggest we change the logic for activity, drilling, harvest and input logs to ‘view any’. For observation logs I think we can use View any/ Create/ Update own. [I’ll then make an issue to be able to comment on logs and maybe ‘at’ people so they get an alert if their logs are being queried.](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/574) I noticed that users can edit logs if associated with the field (e.g. Commercial Field 2) but actually should only be if associated with the experiment boundary so perhaps the logic for land assets needs to include ‘if experiment boundary’ for Research Editors and Research Leads?
> 
> A summary of what those changes mean in practice:
> 
> Research Lead and Research Viewer:
> Observation logs: Please can we change observation logs to View any/ Create/ Update own. 
> All other logs: Please can we change activity, drilling, harvest and input logs to ‘view any’.
> Edit button on Research entities: Again the edit button shows when you have previously edited a research entity. Again I probably only noticed it because I have been changing the user type of the test account so often.
> Deleting Research entities: please can we revoke the permission to delete entities you are associated with.
> Land assets: Can only edit if have type ‘Experiment boundary’
> 
> Finally, I had a detailed look at the research viewer and realised that the logic works if you have a direct link to the asset/ log/ research entity but you can’t actually get to those in the system because can’t access the overview pages. I also realised that the logic works really well if the asset/ log is linked to an experiment but it doesn’t work if you are an owner of the asset or log. Ideally it would work if you are either an owner or linked to the log via an experiment, although this got very confusing in my head so I think for now let’s leave it as ‘related to an experiment’ and come back to the owner thing later. I’ve created that issue here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/575
> 
> Restricted Viewer:
> Equipment: Currently no view access (should be view all)
> All other assets: logic works but there is no access to the dashboard/ overview pages so can’t access the asset unless you have the direct link 
> Logs: logic works but there is no access to the dashboard/ overview pages so can’t access the log unless you have the direct link 
> Research entities: logic works but there is no access to the dashboard/ overview pages so can’t access the research entities unless you have the direct link

**Comment by aislinnpearson** [comment]
Summary of changes for different users as per our call last night:

**No changes:**
Farm Viewer
Operator (basic)

**Farm Manager:**
1.	Can currently revert changes on assets. Please change to can’t revert changes on all assets
2.	Can currently revert changes on logs. Please change to can’t revert changes on all assets

**Operator (advanced):**
1.	Assets currently have the permission to update any. Please change to update own with the exception of plot assets, which should be view any (cannot create or update)

**Farm Data Admin:**
1.	Can’t currently revert changes on logs. Please change to can revert changes on all logs.
2.	Can’t currently revert changes on experiment entities (except plans). Please change to can revert changes on all experiment entities, including plans.

**Research Leads and Research editors:**
1.	Can edit logs associated with (I think? the edit permissions seem to be a bit strange on the logs - see for example log 26). Please change to View any for all logs except observation logs which should be Create/ Update own/ View any
2.	Can’t edit plant assets associated with (plant assets are currently View Any). Please update to view any/ update associated with. My thinking here is that we initially deliberately excluded plant assets from editing because we only them for commercial crops, but for consistency I think it makes sense to the logic the same as that for all the other asset types. You never know when someone might want to include experiments on fruit trees and I believe we have some agroforestry experiments coming up where this might be useful. Equipment and Group assets can remain exclusions (view any permissions only) to restrict people editing farm equipment. See also comment below.

**Restricted viewer:**
1.	Can’t view revisions on assets. Please change to can view revisions (assuming this will only be for assets they are associated with). I couldn’t test the revert asset function, but this should also be no.
2.	Can’t view revisions on assets. Please change to can view revisions (assuming this will only be for assets they are associated with). I couldn’t test the revert asset function, but this should also be no.
3.	The logs and plots aren’t visible on the plan, so they can’t be accessed (but you can see them if you have the url)

**Research Leads and Research editors:**
I’ve just realised a fundamental flaw with these two users where people can add an asset that doesn’t belong to them, and by adding it given themselves permission to edit it. I doubt this will happen maliciously, but I imagine it could happen in error. I can’t think of an easy way around this except to all leads and editors to create rather than add assets (only research data admins can add existing assets?) That would become a nightmare though if they want to add assets every year (a separate conversation to have, especially with the concept of cloning plans). My other thought is you can only add and edit assets if you are listed as an owner, and maybe we include an error message that says ‘you don’t have permission to edit this asset, please contact your Farm Data Administrator’ with a list of who those people are? Issue created here for discussion: #578 

**All user types**
It also occurred to me that we might want to set up some rules where if you have one user type, you can’t have another. For example, you can’t be a restricted viewer and a Farm Data Admin but in theory at least we might want someone to be a Research Lead and a reviewer. Created an issue here for discussion: #580

**A quick point for the update:** I thought if we leave the current user types in, I’ll update everyone and then we can remove them in the next milestone? Does that work? I created an issue here just so it gets remembered: #581

**Comment by paul121** [comment]
Thank you @aislinnpearson ! I was able to make all of these changes except for _Restricted Viewer item # 3._ That will need to tackled in a follow up as it related to #582

> It also occurred to me that we might want to set up some rules where if you have one user type, you can’t have another.

Absolutely! This is a good idea and would not be super hard to implement.

> A quick point for the update: I thought if we leave the current user types in, I’ll update everyone and then we can remove them in the next milestone? Does that work? 

Yes and no. During this update we need to modify/delete the previous Rothamsted roles as needed to implement the new roles, so these will change when we do the deploy. BUT the farmOS core roles ("Manger", "Worker", "Viewer") can remain in-place until you are ready to remove them and Mike can uninstall the `farm_role_roles` module. I will comment in that issue

**Comment by paul121** [comment]
@aislinnpearson I've pushed these changes and am going to tag a release. If you think these permissions are good close this issue and we get a deploy out tomorrow!

**Comment by aislinnpearson** [comment]
Go ahead @paul121 - it sounds to me like only those using the experiments will be affected, and I can e-mail everyone to tell them they might not be able to access things for a day or two. It should be fine :)
