### ISSUE TITLE
Experiment Module: Minor fixes

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#379]
Hi @paul121,

Here is the list of minor fixes as promised:

**All Entities:**
- [x] Add "Requested" to the 'Status' data field 
- [x] Add the 'Status' data field from the "plans entity" to the Researchers, Program, Experiment and Design entities (for the Researchers and Program entities, we only need 'Active' and 'Archived' for the Status if this is possible).
- [ ] #381

**Researchers Entity:**
- [x] Add field for job title

**Program Entity;**
- [x] Add "Lawes Agricultural Trust" to list of funders.
- [x] There seems to be a formatting issue with some of the data fields (I double checked and don't think I pressed enter?)

![image](https://user-images.githubusercontent.com/16349781/224126472-ef584d53-64ad-402d-9237-5339f0ab0ba5.png)

**Design Entity:**
- [x] Rename description "Design Description" to clarify the difference between this and the Experiment entity
- [x] Make 'Statistical Design" appear as 'None' until "Blocking Structure" is selected.
- [x] Add the unit 'm' to plot length and plot width
- [x] Add the unit 'm2' to the end of plot area, total plot area and experiment area
- [x] Ideally we would come up with a way of stating if the plot sizes are 'non-standard' (e.g where plots have different lengths and/or widths and so areas). This just needs to be a tick box (the actual size and areas in in the GeoJSON)

**Plots:**
- [x] Ideally these would have the plot_type "undefined" rather than "blank" to make it clear that the attributes haven't been uploaded (we originally defined blank plots as "A plot that doesn't exist in the field, but is included to help create rectangular plot layouts in field design software", where these plots do physically exist, they just haven't been defined).

Let me know if they raise any questions. Also I totally understand if you don't get them all done today. Any that aren't completed in this milestone I will make another issue for.

**Comment by paul121** [comment]
> There seems to be a formatting issue with some of the data fields (I double checked and don't think I pressed enter?)

This is because these are multi-value text fields. If you provide multiple values then it will make more sense why it is indented. Maybe they don't need to be multi-value?

![Screenshot from 2023-03-09 15-03-45](https://user-images.githubusercontent.com/3116995/224180318-6cf22381-dcdd-4b49-9e9c-2d6c029241f1.png)

**Comment by paul121** [comment]
Okay, I believe I have complete all of these requests, except for adding Flags. Unfortunately flags are quite coupled to farmOS core asset/logs/plans so we cannot re-use them on custom entity types. We could add another `list_string` field with well-defined options to serve the same purpose, but lets do this in a new issue :-)

**Comment by paul121** [comment]
Created a new issue for flags: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/381
