### ISSUE TITLE
Experiment Module: Visible columns and filtering

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#383]
As discussed, please find below a list of column names and searchable items for the Experiment Module entities @paul121 

**Research Program:**

- **Column names:** No Change
- **Filterable terms:** Please add:
-- start date 
-- end date

**Proposal:**

- **Column names:** No Change
- **Filterable terms:** Please add:
-- Experiment Category (see #380) 

**Experiment:**

- **Column names:** 
-- please remove `public release` and `website`
-- please add `status notes` and `crops`
- **Filterable terms:**
-- Please add 'crops`
-- Please remove 'Public release`

**Design:** 

- **Column names:** 
-- please remove `number of treatments`, `number of blocks`, `number of columns` and `number of rows`
-- please add `status notes`, `start year` and `end year`
- **Filterable terms:** 
-- please add 'start year` and `end year`

**Plan:**

- **Column names:** 
-- please add `status notes`, `experiment`, `experiment category` and `researchers`
- **Filterable terms:** 
-- please add 'experiment`, `status notes` and `experiment category`

**Researchers:**

- **Column names:** No change
- **Filterable terms:** No change

**Comment by paul121** [comment]
> Filterable terms: Please add:
-- start date
-- end date

@aislinnpearson I'm going to hold off on this - filtering by date would require they select the specific start date. I think you might want to filter a time range for both the start and end date? This just gets more complicated..

**Comment by aislinnpearson** [comment]
> @aislinnpearson I'm going to hold off on this - filtering by date would require they select the specific start date. I think you might want to filter a time range for both the start and end date? This just gets more complicated..

@paul121 you are right. I didn't think this through... we have drilling year and harvest year, and that is enough I think.

**Comment by aislinnpearson** [comment]
HI @paul121,

I just double checked this and you've done everything perfectly, but I'm questioning my own logic.

**Design:**

- Ideally we should put blocking structure before statistical design in the columns and search terms just because the blocking structure determines the design (and it would be consistent with what is on the form).
- I wonder if we should put all three elements in (i.e. add Additional Blocking Constraints)?

**Proposals:**
- Can we move the status notes so they come after the status (to be consistent with the experiment, designs and plans)

**Plans:**
- To make additional space, we could remove experiment category from the columns (just keep it as a searchable term)
- For the life of me, I don't know why I asked you to add status notes to the list of searchable terms. Can we remove it?

This is just a list of the things that occurred to me when checking the issue in the dev version. We can do the actual work in 2.11.x, which I think I would prefer to delaying 2.10.x
