### ISSUE TITLE
Experiment Module: Minor Edits

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#384]
Hi @paul121,

Here's the list of minor issues as promised:

**Experiment Entity:**
- Please can we create a 'Status' tab and move the `Status` data field to this tab
- Please can we rename the "layout" tab as "in-field layout", and put it _before_ the design tab (it comes first in the process)
- Please can we move the data fields `Number of blocks`, `Number of plots per block`, `Number of main plots`, `Number of subplots per main plot`, `Number of subplots`, `Number of sub-subplots per subplot` and `Number of sub-subplots` to the Treatments tab
- Please can we make the `treatments` data field an 'ad multiple' field so it is the same as that on the proposal (see [comment in #380](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/380#issuecomment-1477991388))

**Design Entity:**
- Please can we create a 'Status' tab and move the `Status` data field to this tab
- On the description tab, please can we add a new optional long text data field called `changes from previous design` with the description "Where relevant, please describe any changes from the previous statistical design and why the changes were made."

**Plan Entity:**
- On the Description tab please can we make it so that the plan references: 
1. the experiment (above the experiment design) 
2. the proposal (below the experiment design). Ideally the status plan on the proposal would also reference the Plan, and it would auto-update, but I am not sure how complicated that is...
- on the Description tab please can we remove the 'project code' data field (this is now on the Program entity) and the `Objective(s)` data field (this is now on the Experiment entity)
- Please can we rename 'Drilling year' as 'Planting year' (that way the terminology also covers crops such as willow which are transplanted rather than drilled).
- On the description tab please can we edit the description of the start and end dates so they read "The start(end) date of the plan' (currently it says programme)
- For the restrictions, please can we copy the format from the Proposal entity
- On the restrictions tab can we also please so add the same management restrictions data fields as well as the 'Other restrictions' question (see [comment in #380](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/380#issuecomment-1477991388))
- On the 'management tab' please can we add the option 'Not applicable' to the `seed provision` data field
- For the plots page on the Plans please can we show plot number in addition to plot id.
- Please can we also change the order in which the plots are displayed: plot number should be numeric, and plot id alpha-numeric (currently I think they are sorting as though they are text? For example, 1, 10, 100, 2, 20, 200, etc...)

**Multiple Entities:**
- Please can we add the `status notes` data field that is currently on the proposal to the experiment, design and plan entities

Also, a couple questions:
1. Do we have revisions for the new entities? I couldn't see them in the test module but maybe that's because of the level of permissions I have?
2. Can we include mathematical notation in the `statistical models` data field on the Design (description) tab?
3. I realised that although we can edit the plot geometries and attributes, we can't easily add or remove the physical plot assets once we have said how many there are...
5. On the management tab, each of those data fields has a few different options associated with it: (1) it could be a treatment (in which case it doesn't need a description, but it is a restriction of sorts), (2) it might have restrictions associated with it (in which case it does need a description), (3) there are no restrictions  (standard management applies) and (4) ideally we would also say who is responsible (farm, sponsor, other or a combination thereof). I was wondering if there is a clever way of doing this... especially if we could link it to the flags?

**Comment by paul121** [comment]
Mostly all done! A few notes + new issues below:

> On the Description tab please can we make it so that the plan references:
the experiment (above the experiment design)
the proposal (below the experiment design). Ideally the status plan on the proposal would also reference the Plan, and it would auto-update, but I am not sure how complicated that is...

We talked about this and decided to not add this as a reference field. Instead, we can include the existing Plan -> Design 
-> Experiment relationship in the table view.

> on the Description tab please can we remove the 'project code' data field (this is now on the Program entity) and the Objective(s) data field (this is now on the Experiment entity)
Please can we rename 'Drilling year' as 'Planting year' (that way the terminology also covers crops such as willow which are transplanted rather than drilled).

Lets save these for a new issue for "Updating old plan fields" after this release. I'd rather only add fields in this pass, and do cleanup + migration (as needed) after.  See #385 

> For the restrictions, please can we copy the format from the Proposal entity

I'm going to save this for another issue, lower priority: #386

> For the plots page on the Plans please can we show plot number in addition to plot id.
Please can we also change the order in which the plots are displayed: plot number should be numeric, and plot id alpha-numeric (currently I think they are sorting as though they are text? For example, 1, 10, 100, 2, 20, 200, etc...)

New issue: #387

**Comment by aislinnpearson** [comment]
A few additional comments on the above:

> Do we have revisions for the new entities? I couldn't see them in the test module but maybe that's because of the level of permissions I have?

Yes, just wasn't visible in the development version

> Can we include mathematical notation in the statistical models data field on the Design (description) tab?

Possibly. There is a Drupal Tex module for this but it isn't active. Not a development priority (won't do). #388 

> I realised that although we can edit the plot geometries and attributes, we can't easily add or remove the physical plot assets once we have said how many there are...

This relates to this issue here: #382 

> On the management tab, each of those data fields has a few different options associated with it: (1) it could be a treatment (in which case it doesn't need a description, but it is a restriction of sorts), (2) it might have restrictions associated with it (in which case it does need a description), (3) there are no restrictions (standard management applies) and (4) ideally we would also say who is responsible (farm, sponsor, other or a combination thereof). I was wondering if there is a clever way of doing this... especially if we could link it to the flags?

See this issue here: #386
