### ISSUE TITLE
Form states logic for plan restrictions

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#386]
The proposal entity has nice form state logic so boolean checkboxes show/hide the restriction text fields. We would like this on the plan entity as well, the challenge is that we don't have direct access to the plan's form so this is more challenging.

**Comment by aislinnpearson** [comment]
See also this comment here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/384#issuecomment-1485195980

**Comment by paul121** [comment]
This will be solved with #419
