### ISSUE TITLE
Experiment Module: Minor edits

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#397]
Program entity:
- [x] #427
- [x] #428

Proposal entity:
- [x] #406
- [x] #411
- [x] #407
- [x] #408
- [x] #409
- [x] https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/403
- [x] #425
- [x] #426

Experiment Entity:

- [x] #402
- [x] #403
- [x] #429

Design Entity:

- [x] #402
- [x] #404
- [x] #418
- [x] #417
- [x] #423
- [x] #430
- [x] #431
- [x] #432

Plan entity:

- [x] #405
- [x] #415
- [x] #419
- [x] #421
- [x] #422
- [x] #420 
- [x] #424

**Comment by paul121** [comment]
@aislinnpearson I have a question about the "approved quote" field. Currently this is listed for the Plan entity, but I wonder if you meant for this to be included with the Proposal entity after the "Initial Quotes" field?
