### ISSUE TITLE
Experiment Module: Move rotation tab to design entity

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#400]
Having looked at this in more detail, I was wondering if it is possible to move the rotation tab to the design entity? That way, when a rotation changes, it can be submitted as a new design. 

This would involve moving the whole tab from the experiment entity to the design entity.

Speaking to @paul121 this would mean any rotation information already in the live versions of FarmOS would be deleted. Currently this is just Hoos Barley, and I already have a copy of that information. So as long as we can get this done in the next week or so, I can just add that back in once this is deployed

**Comment by paul121** [comment]
Okay, I've implemented this and tested the update hook as follows.
1. On the demo site I created an experiment entity with rotation information. Also created a basic design entity.
1. Ran the update hook and saw no warnings or errors. Rebuild the cache.
1. After the update the rotation data was removed from the experiment entity and the fields (without any data) were available on the design entity.
1. I was able to save the existing experiment and design entities. Most importantly was able to add new rotation info to the design entity.
1. No field definition errors in the status report

Update hook:

```
     ----------------- ----------- ------------- ---------------------------------- 
      Module            Update ID   Type          Description                       
     ----------------- ----------- ------------- ---------------------------------- 
      farm_rothamsted   move_rota   post-update   Move rotation fields from         
      _experiment_res   tion_fiel                 experiment to design entity with  
      earch             ds                        2.10.1 release.                   
     ----------------- ----------- ------------- ---------------------------------- 
    
    
     // Do you wish to run the specified pending updates?: yes.                     
    
    W: >  [notice] Update started: farm_rothamsted_experiment_research_post_update_move_rotation_fields
    W: >  [notice] Update completed: farm_rothamsted_experiment_research_post_update_move_rotation_fields
```

**Comment by aislinnpearson** [comment]
That all sounds good to me. Thanks so much @paul121 - @mstenta feel free to go ahead. I deliberately haven't entered any additional data, and I have a copy of everything that is in there.
