### ISSUE TITLE
Change boolean sliders to required yes/no widget

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#413]

**Comment by paul121** [comment]
I needed to use a radio instead of a select dropdown, but this should have the same effect. It actually is less clicks using the radio widget.

**Comment by paul121** [comment]
![Screenshot from 2023-04-26 17-37-06](https://user-images.githubusercontent.com/3116995/234730858-94f0b878-cca6-4a43-aa3e-e3e3f4c653f3.png)

**Comment by aislinnpearson** [comment]
Still looks good to me. :)

**Comment by paul121** [comment]
Need to do this for the design restrictions as well (currently on the plan, moving to design with #419 )
