### ISSUE TITLE
Add 'is treatment' check boxes to management tab

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#420]
Please can we add an 'is treatment' question with three options (Yes, No, Not Applicable) to the following questions on the management tab.

Questions with as descriptions below:

**Sub-section: Seed**
- Seed treatment as treatment: Are seed treatments a part of the treatment structure?
- Variety as treatment: Is variety a part of the treatment structure?

**Sub-section: Cultivation**
- Cultivation as treatment: Is cultivation a part of the treatment structure? 

**Sub-section: Planting**
- Planting date as treatment: Is planting date a part of the treatment structure?
- Planting rate as treatment: Is planting rate a part of the treatment structure?

**Sub-section: Spraying**
- Fungicides as treatment: Are fungicides a part of the treatment structure?
- Insecticides as treatment: Are insecticides a part of the treatment structure?
- Nematicides as treatment: Are nematicides a part of the treatment structure?
- Molluscicides as treatment: Are molluscicides a part of the treatment structure?
- Plant growth regulators (PGR) as treatment:  Are plant growth regulators a part of the treatment structure?

**Sub-section: Irrigation**
- Irrigation as treatment: Is irrigation a part of the treatment structure?

**Sub-section: Nutrition**
- Nitrogen (N) as treatment: Is nitrogen a part of the treatment structure?
- Potassium (P) as treatment: Is potassium a part of the treatment structure?
- Phosphorous (K) as treatment: Is phosphorous a part of the treatment structure?
- Magnesium (Mg) as treatment: Is magnesium a part of the treatment structure?
- Sulphur (S) as treatment: Is sulphur a part of the treatment structure?
- Micronutrients as treatment: Are micronutrients a part of the treatment structure?
- Liming (pH) as treatment: Is liming or pH a part of the treatment structure?

**Sub-section: Other**
- Other aspects of management as treatments: Are there any other aspects of management which form part of the treatment structure?

**Comment by paul121** [comment]
@aislinnpearson just FYI we have the elements for Phosphorous (P) and Potassium (K) mixed up in a few places.. I'll fix them now but maybe update in your spreadsheet too, else I'll likely copy/paste an errant want in the future!

**Comment by aislinnpearson** [comment]
> @aislinnpearson just FYI we have the elements for Phosphorous (P) and Potassium (K) mixed up in a few places.

Sorry @paul121 - this is one of those errors I make all the time. For some reason I can never remember which is which
