### ISSUE TITLE
Quick Forms: Create separate log categories for two Harvest quick forms

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#438]
Please can we create two separate sets of log categories for each of the two harvest forms (currently only under one)

**Comment by paul121** [comment]
Absolutely. Currently both forms are using the `Harvest Categories` parent term to allow users to select which log category. If you create a new log category "group" on all instances eg: `Trailer Harvest Categories` and let me know what it is, I will make this change for the relevant quick form

**Comment by aislinnpearson** [comment]
@paul121 for consistency can we go with a name that more fully reflects the quick forms. E.g.:

'Trailer/ bale weight harvest categories'
'Combine/ forage harvest categories'

But if that is too wieldy to implement then I like your suggestion:

'Trailer harvest categories'
'Combine harvest categories'

**Comment by paul121** [comment]
Lets go with the shorter ones:
'Trailer harvest categories'
'Combine harvest categories'

@aislinnpearson after this is deployed the quick form will show this warning until the log categories have been created:

![Screenshot from 2023-06-19 14-12-43](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/344e71e3-9329-44f8-b6e3-3db67f9c1e00)
