### ISSUE TITLE
Experiment Module: Email alerts to Proposal contacts

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#441]
@mstenta, @paul121 

This is a specification error on my part, but I have just realised if you are a researcher viewer or research editor associated with a proposal then you don’t get e-mail updates when the status changes.

How I imagine this working is that any researcher listed on a proposal who has a farmOS user account will get an email describing any changes to the proposal form.

This is very important for the planning process though, so ideally we’d push the change quite quickly (maybe as 2.11.1). As I say I think this is my fault. I assumed it this as the default behaviour, but I don’t ever remember saying anything to you about that process. But if we could get it amended and pushed as soon as possible I'd be very grateful.

**Comment by aislinnpearson** [comment]
Hey @paul121,

Thanks so much for fixing this. I don't know if this is related at all, but even as an administrator I don't seem to always get an email when someone updates a proposal (I do when people edit a program or a researcher). 

Re-opening the issue so we can chat about it in today's meeting, but as I say possibly resolved in the above

**Comment by paul121** [comment]
> but even as an administrator I don't seem to always get an email when someone updates a proposal

Yes! I noticed we weren't sending any emails for proposals. I've fixed that in this process :+1:
