### ISSUE TITLE
Logs with missing asset references

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#444]
Alberto discovered (via farmOS Python API experimentation) that there are some logs in the system that are referencing non-existent assets.

We aren't sure *why* this happened... farmOS core prevents the deletion of assets that are referenced by a log, and it also validates logs when they are saved to ensure that all the assets it references exists (this is the error Alberto was seeing when he was trying to save them again via the API). But it's possible that some code somewhere is working around those protections somehow.

I will use this issue to dig in and see if we can identify how widespread this is via direct database queries.

**Comment by mstenta** [comment]
Here is a query that reveals all the affected logs, with a count of invalid references on each. It seems that all of the logs were created by quick forms, so this also shows which quick form they came from.

```
SELECT
    l.id,
    l.uuid,
    l.type,
    lq.quick_value,
    COUNT(la.entity_id)
FROM log__asset la
LEFT JOIN log l ON la.entity_id = l.id
LEFT JOIN log_field_data lfd ON l.id = lfd.id
LEFT JOIN asset a ON la.asset_target_id = a.id
LEFT JOIN log__quick lq ON l.id = lq.entity_id
WHERE
    a.id IS NULL
GROUP BY
    l.id,
    lq.quick_value,
    lfd.created
ORDER BY lfd.created DESC;
```

**Comment by mstenta** [comment]
FYI checked the `location` field and that seems OK. Query:

```
SELECT
    l.id,
    l.uuid,
    l.type,
    lq.quick_value,
    COUNT(ll.entity_id)
FROM log__location ll
LEFT JOIN log l ON ll.entity_id = l.id
LEFT JOIN asset a ON ll.location_target_id = a.id
LEFT JOIN log__quick lq ON l.id = lq.entity_id
WHERE
    a.id IS NULL
GROUP BY
    l.id,
    lq.quick_value;
```

**Comment by mstenta** [comment]
@paul121 identified the root cause: there's a bug in the asset reference code in the quick forms that causes a `0` asset ID reference to be saved for all "unchecked" assets in the quick form.

These queries will clean up all the affected records:

```
DELETE FROM log__asset WHERE asset_target_id = 0;
DELETE FROM log_revision__asset WHERE asset_target_id = 0;
```

Probably makes sense to wait until the bug is fixed to run those...

**Comment by aislinnpearson** [comment]
Hey @stellalberto 

Voila! The answer to your question (thanks @mstenta and @paul121). 

@stellalberto - thought you might also find the code useful?
