### ISSUE TITLE
Experiment Module: Add a mandatory data fields for Statisticians and Data Stewards

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#445]
Please can we add a mandatory data field for Statisticians and Data Stewards to the proposal forms.

**Data Field Name:** Statistician
**Data Field Description:** Please select the statistician associated with this proposal.
**Format:** Widget which selects from a list of researchers who have the role 'Statistician'
**Implementation:** The selected statistician will receive email alerts whenever the proposal is saved/ edited.

**Data Field Name:** Data Steward
**Data Field Description:** Please select the data steward associated with this proposal.
**Format:** Widget which selects from a list of researchers who have the role 'Statistician'
**Implementation:** The selected statistician will receive email alerts whenever the proposal is saved/ edited.

**Comment by paul121** [comment]
email alerts with #441

**Comment by aislinnpearson** [comment]
Hey @paul121,

I found a minor error: I think this currently pulls a list of statisticians rather than a list of data curators.

To get us through this the current round of proposals, I've had to change the researchers listed as data curators to data stewards (these are being referenced in the updated proposals) so we we push this change can we please make sure that any ‘statisticians’ that have been added to the proposals as data curators will remain associated with that data field on the proposals, even when we change them back to ‘data curators’.

**Comment by paul121** [comment]
Hey sorry @aislinnpearson I was confused by this too and almost asked you about it but in the end went with what is described above. Both of the requested fields specify to select form a list of `statisticians`:

> Data Field Name: Statistician
Format: Widget which selects from a list of researchers who have the role 'Statistician'

> Data Field Name: Data Steward
Format: Widget which selects from a list of researchers who have the role 'Statistician'

Also we do not have a "Data Steward" but instead a "Data Curator" role. Would it make sense to change the Proposal: Data Steward field to be "Data Curator" instead? Or do we need to add "Data curator" as a new role?

**Comment by paul121** [comment]
> so we we push this change can we please make sure that any ‘statisticians’ that have been added to the proposals as data curators will remain associated with that data field on the proposals, even when we change them back to ‘data curators’.

Yes - will make sure this still works after we correct this.

**Comment by aislinnpearson** [comment]
Sorry @paul121 - this sounds like it was a mis-specification on my part then (trying to do too many things at once and it is starting to show). Also the data curator/ data steward terms are sometimes used a little bit interchangeably here in that the data stewards sometimes help curate the farm data... so I can see how I am not helping from that perpsective!

The Data Curator field should please reference the Data Curator role (where the job title for some people listed as data curators will be 'Data Steward'). Third time lucky hopefully!

**Comment by aislinnpearson** [comment]
Hi @paul121,

We've been updating the forms to add the data stewards as data stewards, but discovered that the data stewards field pulls from the list of statisticians, and the list of statisticians pulls from the list of data stewards.

I have just swapped the role for the data stewards/ statisticians, and the form submits just fine, so not an urgent fix (it can wait until Mike gets back from holiday).

Please can you also assign this task to me before closing it as a reminded to change the job roles back?

I am almost convinced this is my fault again, and I have forgotten something we discussed or I am doing something wrong! So apologies in advance.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/aaf2ce3a-8539-4eb6-9019-19e485ce2901)
![image2](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/b4c9b31a-6b7c-4e98-8449-67b25b5371de)

**Comment by paul121** [comment]
Gosh I'm sorry @aislinnpearson that is my mistake. I simply made this change to the wrong field. Will have this fixed for the next release

**Comment by aislinnpearson** [comment]
Aislinn to update internal systems

**Comment by aislinnpearson** [comment]
> Aislinn to update internal systems

Done
