### ISSUE TITLE
Experiment Proposal: Remove 'Proposed Amendments' data field on Proposal

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#450]
Please can we remove the 'Proposed Amendments' data field on the experiment module (this has been replaced by the comment feature).

Currently there are no experiments using this data field but we will need to double check this. If there are any data fields using this box, they should ideally be transferred to a comment (either manually or progamatically).

**Comment by paul121** [comment]
Here is an API query we can use to find proposal entities that do have an amendment specified:
`/api/rothamsted_proposal/rothamsted_proposal?filter[amd][condition][path]=amendments.value&filter[amd][condition][operator]=IS%20NOT%20NULL`

@aislinnpearson this will be much easier to do manually. I just checked rothamstedfarm.farmos.net and did not see any proposals with amendments :+1:

**Comment by paul121** [comment]
I have removed this field from the code. Just need to do a quick review before we deploy to move existing data to comments

**Comment by paul121** [comment]
We discussed this today, there is no data that needs to be moved if we update over the weekend/early next week.
