### ISSUE TITLE
Make 'Orcid ID' data field on Researcher entity a hyperlink

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#451]
Please can we make the 'Orcid ID' data field on Researcher entity a hyperlink, and edit the data field so that "https://orcid.org/" appears on the left hand side of the data field (prompting the user to only add their identifier rather than the whole url).

Several of the orcid ids which already include the hyperlink will need to be edited either manually or programmatically to remove the "https://orcid.org/"

**Comment by aislinnpearson** [comment]
HI @paul121,

I was updating the data stewards/ statisticians as part of #445 and noticed that the orcid ID field doesn't submit if there is an X on the end of the orcid id (see image below). I only had two staff with this problem, myself and Tegan:

Aislinn: 0000-0002-9793-025X
Tegan: 0000-0003-2367-043X

I did take a look into this and I can't figure out what the X is for, but I did find some information on how they are structured (and how to store time in a database0 here: https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier#:~:text=The%20ORCID%20iD%20is%20expressed,the%20identifier%20to%20aid%20readability.

I resolved the issue by deleting the orcid Id's for Tegan and myself, which meant I could then at least update our two roles. Could please leave this open once the push is done and reassign it to me so I can add us both back in. :)

Thanks

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/588bfbe8-8c89-4ad7-9cd5-51143e0e3151)

**Comment by paul121** [comment]
Oh interesting! I guess the IDs are not quite always 16 digits... They are 15 digits + a final checksum that can be 0-9 or "X" to represent 10. Kind of odd but an easy fix!

**Comment by paul121** [comment]
Done. Also https://support.orcid.org/hc/en-us/articles/360053289173-Why-does-my-ORCID-iD-have-an-X-

**Comment by aislinnpearson** [comment]
All corrected. thank you!
