### ISSUE TITLE
Experiment Proposal/ Design: Edit Treatment descriptions

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#454]
Please can we edit the descriptions for Treatment Factor, Number of Factor Level Combinations and Number of Replicates on the Proposal and Design entities.

**Number of Treatment Factors** (statistical design tab on both the proposal and design entities): "_The number of treatment factors being tested in the experiment, where a treatment factor is a variable under the control of the experimenter (sometimes also called explanatory variables) with two or more levels._"  

**Treatment Factors** (statistical design tab on both the proposal and design entities): "_A description of the treatment factor(s) being tested in the experiment, with a list of the factor levels where applicable. Please add a new box for each treatment factor. For example: "Fungicide exposure (high, medium, low, none)" in one box and "Plant Breed Line (Cadenza, KWS Zyatt, KWS Extase) in another._" 

**Number of Factor Level Combinations** (statistical design tab on both the proposal and design entities): "_The number of unique treatments, where a unique treatment might be a combination of factor levels from two different treatment factors. For example, if you have two treatments factors, one for Fungicide Exposure with four factor levels (high, medium, low, none) and a second treatment factor for Wheat Variety with two factor levels (Variety 1 and Variety 2) and all four fungicide treatments are applied to each of the two varieties, then there are 8 factor level combinations (Variety 1 with high fungicide exposure, Variety 2 with high fungicide exposure, Variety 1 with medium fungicide exposure, Variety 2 with medium fungicide exposure, etc)._"

**Number of replicates** (statistical design tab on both the proposal and design entities): "_The number of times each factor level combination is repeated in the experiment_."

**Comment by aislinnpearson** [comment]
@paul121 - I have updated the above descriptions slightly (noticed a couple typos and also Stats gave me a little bit of feedback).

We should now be good to go with this issue :)

**Comment by paul121** [comment]
Done - note that "Number of Factor Level Combinations" is not a field on the proposal.
