### ISSUE TITLE
Experiment Proposals: Edit descriptions for add multiple fields

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#455]
Please can we edit the descriptions for each of the add multiple data fields so it is obvious a new box needs to be added for each research question, measurement, etc. The fields which need to be edited are:

- Research Program: "The research program which this proposal is part of. You can add multiple Research Programs."
- Research Question: "The research question you expect to answer with the experiment, and how it relates to the research program. You can add multiple questions. Please add a new box for each research question."
- Measurements: "Please add a new box for each measurement. Describe the measurements you propose to take, approximate dates and who is responsible for taking the measurements. This should include who is responsible for taking the measurements (farm, sponsor, external consultants, etc)."
- Other Restrictions: " If there are any other restrictions not covered above, please add them below. Please add a new box for each additional restriction."

**Comment by paul121** [comment]
> For short form fields it makes sense to have the #description appear below the form widget; however, in long lists of checkboxes and/or radio buttons it would be nice to be able to have a toggle whether the #description appears above, or below, the form widget.

Great, we can use the `#description_display = 'before'` option from Drupal FAPI for this: https://www.drupal.org/node/2324025 (cc @mstenta, might be of interest)

Now the question is *how* to apply this... the fields listed above are a mix of entity reference and text area, all with unlimited cardinality. Generally I think it might make sense to put the description `before` the form element whenever cardinality is unlimited (covers entity reference, text area, short text, any others I might be missing?)

**Comment by aislinnpearson** [comment]
Hey @paul121,

I might be misinterpreting this but it make it easier if I say we just put the description for _all_ fields 'before'?

**Comment by aislinnpearson** [comment]
> Now the question is how to apply this... the fields listed above are a mix of entity reference and text area, all with unlimited cardinality. Generally I think it might make sense to put the description before the form element whenever cardinality is unlimited (covers entity reference, text area, short text, any others I might be missing?)

We discussed this on the call that @paul121's suggestion as a first pass, and see how we go.

**Comment by paul121** [comment]
Afh unfortunately `#description_display` doesn't work here... the template for these multi-value fields (`field-multiple-value-form.html.twig`) uses a table to rendered the multiple field items and actually hard-codes the `description` to always render after the `table`. This make sense because the table header is the "field title"... so simply rendering the description above the table is weird:

![Screenshot from 2023-06-26 10-51-19](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/ea1c3409-2005-4011-935e-bd33bee68db0)

Maybe we should include the description under the title in the table header? Hmm

**Comment by paul121** [comment]
I've found an option that is a good improvement: moving the description to the table caption. This still doesn't feel like the best way to include the title and description above these "tables" but ultimately accomplishes what we want without a lot of work.

![Screenshot from 2023-07-17 11-01-46](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/e8730213-0baf-4a63-8f87-27da89c2ef58)

**Comment by paul121** [comment]
Aha, found a hack and actually able to include the description in the table header...
![Screenshot from 2023-07-17 11-24-58](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/68d23919-e506-4b65-8a8d-a7c9761b5f59)
