### ISSUE TITLE
Fertiliser Quick Form: Field treated area allow 3+ decimal points

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#463]
On the fertiliser quick form, please can we edit the Field Treated Area data field so it can accept decimal points

**Comment by paul121** [comment]
Just tested this, it is able to accept 2 decimal points. But I noticed that entering 3 decimal points raised an error. I'll increase the allowed number of decimal points to 4

**Comment by aislinnpearson** [comment]
thanks @paul121 

Four decimal places is probably over kill for analysis but I still think this is useful from a user perspective - I personally have been prone to getting the calculation and just putting in all the decimal places, and I have seen others do similar, so it saves that confusion when an error comes up.

Something to think about standardising though for #130
