### ISSUE TITLE
Experiment Module: Filter by year

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#480]
Request to please filter proposals, plans and designs by year

**Comment by paul121** [comment]
Designs have a start + end year data field so we can filter to a year between the start + end. But a couple questions:
- Plans have a planting year and harvest year data fields. Do we want filters for both of these?
- Proposals do not have a data field for the year. We could use the "created" timestamp for when the proposal was created.. but I don't think that is what you want?

**Comment by aislinnpearson** [comment]
Hi @paul121,

Sorry - I really shouldn't try to create these issues in a rush. I've mis-specified this one too.

For the proposals we want to exactly replicate what is on the plans: planting year and harvest year. We would then like to be able to also filter the proposals by planting and harvest year as you can with the plans:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/5ee9dff6-aa46-46d7-8a1f-356669cd39a9)

However, when I was looking at the plans I noticed that the filter field is still called drilling year (realistically because I forgot to ask you to change it when I specified that). So ideally we'd fix that, just let me know if you want to create a separate issue.

Thank you also for catching all my mistakes.

**Comment by paul121** [comment]
Done! Proposals have these filters and I fixed the "Drilling year" text on the experiment plan filter.
