### ISSUE TITLE
Experiment Proposals: Add planting and harvest year

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#481]
Please can we add planting year and harvest year to the statistical design section of the proposal forms, and then add these two data fields to the filter and header list (essentially so it is the same as on the Plans, only the filter term for both should be planting year):

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d27a06cc-3987-4550-ba11-d6300ce172f9)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/0bbabbaf-56b4-4961-ac77-87c331edb8ed)

**Comment by paul121** [comment]
Done
