### ISSUE TITLE
Experiment Plans: Save Plot GeoJSON files to experiment plan

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#484]
In previous versions the plots geoJSON was listed by default in the plan files, but this doesn't seem to be the case with the current version (2.12.x)

**Comment by paul121** [comment]
Ah yes, this likely changed when we made the plan + plot + geojson forms a multi-step process. We could add this in so the file is added to the plan. What should we do when the plot geometries are updated multiple times? Would it be confusing if there are multiple geojson files on the plan? Maybe we can expect users to name them accordingly?

**Comment by aislinnpearson** [comment]
Hey @paul121 

I hadn't thought about version numbering... in my experience you can't really rely on the users to implement that sort of thing.

My suggestion is we either over write them or maybe add some kind of default naming convention... although that sounds complicated to me. One to chat about today I think...
