### ISSUE TITLE
Experiment Module: Resolve issue of bounced emails

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#485]
From @mstenta 

With the introduction of email notifications, we've also created a new issue that we'll have to address: email bounces.

Farmier servers relay emails through Amazon's Simple Email Service ([https://aws.amazon.com/ses/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faws.amazon.com%2Fses%2F&data=05%7C01%7Caislinn.pearson%40rothamsted.ac.uk%7Cc608ff49cd834b10f70e08db6777080d%7Cb688362589414342b0e37b8cc8392f64%7C1%7C0%7C638217533155766429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xZ5ptiLB550M6LO%2B5MkuFNpXHh78xlKQRnGuUtV2uak%3D&reserved=0)), to ensure good deliverability and fewer emails in spam folders.

However, if my servers send a lot of emails that "bounce", it will negatively affect my server's "reputation", which can lead to consequences, up to and including AWS terminating my email account - although I don't think we're anywhere near that. From their website:

When it comes to email sending, reputation—a measure of confidence that an IP address, email address, or sending domain is not the source of spam—is important. Amazon SES maintains a strong reputation with email providers so that they deliver your email to your recipients' inboxes. Similarly, you need to maintain a trusted reputation with Amazon SES. You build your reputation with Amazon SES by sending high-quality content. When you send high-quality content, your reputation becomes more trusted over time and Amazon SES increases your sending quotas. Excessive bounces and complaints negatively impact your reputation and can cause Amazon SES to reduce the sending quotas for your account, or terminate your Amazon SES account.

[https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-deliverability.html](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2Fses%2Flatest%2Fdg%2Fsend-email-concepts-deliverability.html&data=05%7C01%7Caislinn.pearson%40rothamsted.ac.uk%7Cc608ff49cd834b10f70e08db6777080d%7Cb688362589414342b0e37b8cc8392f64%7C1%7C0%7C638217533155766429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=uLLVmd0KX7iJCvh66D8sc8mJnKNkdyKP2QNy7PZge%2Bc%3D&reserved=0)

The new notification feature has been resulting in a higher number of bounced emails originating from my servers. As of right now my account is still considered "Healthy", but I would like to address it before it becomes an issue.

There are two potential solutions, I think:
1.	Figure out how to prevent incorrect emails in the Rothamsted farmOS module code itself.
2.	Set up a separate Rothamsted AWS SES account that has its own reputation, and route emails from Rothamsted's servers through that instead.
I suggest we open a new GitHub issue to discuss options for #1. Option #2 is relatively easy, but only kicks the can down the road, and ultimately would affect YOUR reputation in the same way (and maybe worse, because it would be a higher percentage of bounces overall).

One specific issue that has been occurring a lot lately seems to be coming from this "Researcher" with an email address of "
[na@rothamsted.ac.uk](mailto:na@rothamsted.ac.uk)": [https://rothamstedfarm.farmos.net/rothamsted/researcher/101](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frothamstedfarm.farmos.net%2Frothamsted%2Fresearcher%2F101&data=05%7C01%7Caislinn.pearson%40rothamsted.ac.uk%7Cc608ff49cd834b10f70e08db6777080d%7Cb688362589414342b0e37b8cc8392f64%7C1%7C0%7C638217533155766429%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yfj95uMGEBpcUI7rlefMIQ8%2FavNo79gqrQXIU40y%2BFw%3D&reserved=0)

Perhaps we should add some logic to NOT send emails to that one specifically? Or perhaps add some kind of flag or checkbox that prevents emails being sent? Perhaps that would be an easy fix? If so, I would like to request that we make that a high priority for the next release.

**Comment by paul121** [comment]
It seems there are maybe two things we could implement, both quite easy:
- Do not require an email be provided for researchers (that is currently why `na@rothamsted.ac.uk` is being used)
- Add a filter to not send emails to `na@rothamsted.ac.uk` if we want this as a convention for a placeholder email

Also @aislinnpearson I need to double check, but I should also make sure that we do not send emails to inactive researchers, yes? I imagine that 1) they do not need email updates once they are inactive and 2) their email be invalid once they are inactive

**Comment by aislinnpearson** [comment]
Hey @paul121,

Of the two above options, I initially liked the fist one best:

> Do not require an email be provided for researchers (that is currently why na@rothamsted.ac.uk is being used)

That way people can choose to remove their email address if they don't want to receive email alerts until we figure out how we want that to work in more detail... At the same time though, the farm need contact details so I am not sure if that is the best solution. Perhaps a better solution is to go for the second option and create an issue to opt out of emails... but then I can't help but think that might be experiment/ plan specific. In short, I am confusing myself.

As for your second point:

> I should also make sure that we do not send emails to inactive researchers, yes? I imagine that 1) they do not need email updates once they are inactive and 2) their email be invalid once they are inactive

Yes, that is a great idea. Thanks for thinking of it. It will help.

**Comment by paul121** [comment]
> At the same time though, the farm need contact details so I am not sure if that is the best solution. Perhaps a better solution is to go for the second option and create an issue to opt out of emails... but then I can't help but think that might be experiment/ plan specific.

Yes. I see how contact information is important so asking to remove their email to turn of notifications is not great.

To start, we could add a generic checkbox that enables users to turn on/off notifications more generally. I imagine that this would be a useful feature even if/when we have features for notifications specific to an experiment plan.

**Comment by aislinnpearson** [comment]
Following discussion in today's call we agreed that this would ideally integrate with the ability to:

1. Let the user tick a box saying they want to receive notifications (required question)
2. Give an email address for receiving those notifications
3. Otherwise no email is sent by default

This has the added benefit that it is defined/ expected behaviour rather than a 'quirk' of the system where only one email address is ignored.

**Comment by paul121** [comment]
![email-notifications](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/3657dc20-c751-4131-9ebe-9f6321c783f6)

Good addition :+1:

**Comment by aislinnpearson** [comment]
This is great, thank you @paul121
