### ISSUE TITLE
Experiment Design: Add organic amendments

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#491]
Please can we add and 'add multiple' text box to the management (nutrition) tab:

Field name: Organic amendments
Type: long text (add multiple)
Description: Request specific organic amendments (farmyard manure, poultry manure, compost, etc).

As a note to myself, I then need to add this data for Broadbalk, so please assign it to me before closing it off @paul121

**Comment by aislinnpearson** [comment]
Correction:

Type: long text (singular - does not need to be add multiple)

**Comment by paul121** [comment]
Done, assigning to @aislinnpearson to update Broadbalk

**Comment by aislinnpearson** [comment]
Done
