### ISSUE TITLE
Proposal entity: Move Reviewers data field to bottom of comments

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#501]
When we were reviewing the proposals, it became quite difficult to read the proposal, comment and then go to edit the proposal and add your name as a reviewer. 

For this reason we were wondering if it would be possible to add the reviewer's name at the bottom of the comments (possibly as a check box?). This would ideally only be enabled for people who are reviewers (see issue #373) and you would only be able to add the name of the reviewer who is logged in.

**Comment by aislinnpearson** [comment]
Discussed with @paul121 and we agreed a check box for reviewers (which is only visible to reviewers). We will also look into #502 alongside.

Remaining question: 'Reviewers' or 'Approvers'. Aislinn to ask FFEC and let Paul know

**Comment by aislinnpearson** [comment]
HI @paul121 - we are going to go with 'Reviewers' (in keeping with the scientific jargon!)

**Comment by paul121** [comment]
@aislinnpearson just want to clarify how the existing `proposal.reviewers` field should be used. It sounds like we're currently trying to use it for both 1. "These Researchers need to review" as well as 2. "These Researchers have reviewed".

With this new approach 2 will be captured with the Proposal comment "Reviewed" checkbox.

Does that sound correct to you? This way we can do a calculation of "How many of the requested reviewers have a left a comment with Review = yes?"

Example screenshots:
![Screenshot from 2023-09-08 10-52-07](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/1cede97c-9319-4ae3-920a-1c9bbe17f572)

![Screenshot from 2023-09-08 10-48-30](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/47c77f53-5bbc-4fa2-835b-2c41257ee25b)

**Comment by aislinnpearson** [comment]
HI @paul121,

I think I might be misunderstanding this... 

> "These Researchers have reviewed".

The check box for the reviewer is perfect for this, and answers question your second question

> 1. "These Researchers need to review"

For the first question, in my head this is just a list of people who are given 'Reviewer' permissions, rather than specific people allocated to reviewing certain proposals. So the % bar would just be a % of the total number of people with reviewer permissions. I have already spoken to FFEC about this and they accept it will never be 100% (not least because some scientists are on FFEC and so can't review their own proposals) but it is just meant to be indicative and they didn't seem too worried about this.

I noticed the comment box is also required which is great (they should be saying they are happy to sign it off or whatever) but I am increasingly coming to realise that sometimes these 'required' boxes can be a limitation so I suspect this is a feature which will need some testing...

**Comment by paul121** [comment]
After chatting today: Need to add logic to populate the `proposal.reviewers` field with the reviewer after they submit a reviewed comment
