### ISSUE TITLE
Proposal Entity: Visualise proposals by status

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#503]
Similar to what has been done on the Plans page, please can we separate the Proposals into tabs based on their status. The order of these should be:

1. Draft
2. Submitted
3. Approved
4. Planning
5. Postponed
6. Rejected
7. Cancelled
8. Archived

See also https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/504

Consider which columns are needed with each view

**Comment by paul121** [comment]
@aislinnpearson if you could specify the columns you like for each tab! I assume there are some "common" columns and then maybe unique ones for different status?

**Comment by aislinnpearson** [comment]
Hey @paul121,

I've just been told that Jonah will probably be out harvesting for the rest of the week, so I'm going to go with my best guess so we don't hold up the process. Here is my first attempt, but I might need to make some minor amendments later...

**Draft:**
- Name (name of the proposal, required)
- Program (Research program associated with the proposal, required)
- Planting year (easy to sort plans based on this)
- Harvest year (easy to sort plans based on this)
- Statistician (to ensure drafts have been allocated a Statistician)
- Data Steward (to ensure drafts have been allocated a Data Steward)
- Contacts (contact for the proposal, required)
- Status notes (any notes associated with the status)

**Submitted/ Approved:**
All the same columns required for Draft proposals but also includes:
- Reviewers
- Initial Quote

**Planning:**
All the same columns required for Draft proposals but also includes:
- Experiment (so can be added/ viewed easily)
- Design (so can be added/ viewed easily)
- Plan (so can be added/ viewed easily)

Postponed/ Rejected/ Cancelled/ Archived
- Name (name of the proposal, required)
- Program (Research program associated with the proposal, required)
- Planting year (easy to sort plans based on this)
- Harvest year (easy to sort plans based on this)
- Experiment (so can be added/ viewed easily)
- Design (so can be added/ viewed easily)
- Plan (so can be added/ viewed easily)
- Contacts (contact for the proposal, required)
- Status notes (any notes associated with the status)

**Comment by paul121** [comment]
> Here is my first attempt, but I might need to make some minor amendments later...

This is great! Easy to change things in the future.

**Comment by aislinnpearson** [comment]
Hi @paul121 

> This is great! Easy to change things in the future.

Great news! Having used the new system once I have already noticed an oversight: please can we add a tab for 'All'?

Ideally we would do this on the experiment plans as well, but maybe I need to make a new issue for this?

**Comment by aislinnpearson** [comment]
Agreed in the meeting that we would re-open this issue, and the columns for 'All' proposals would be the same as those for Draft proposals. Aislinn to create a separate issue to deal with this under plans.

**Comment by paul121** [comment]
> Aislinn to create a separate issue to deal with this under plans.

@aislinnpearson I didn't see an issue for this but I've gone ahead and done this. Will release under a 2.16.2 so we can get this out to you all soon!
