### ISSUE TITLE
Experiment module: improve e-mails (parent tracking issue)

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#506]
Having been through the review process once, we now have a better idea of how we would like the email process to work:

**Researcher entity:** 
Researcher gets an e-mail notification if edited

**Proposal entity:** 
1. All named researchers get an email when the draft is initial created or edited
2. Reviewers get an email when the proposal is submitted
3. All named researchers and reviewers get an email when the proposal is approved/ rejected/ cancelled. _This should include instructions on what happens next, depending on the status._
4. All named researchers get an email when the experiment moves to planning, _with instructions on what to do next plus any links to experiment, design and plan entities_
5. All named researchers get an email when the proposal is archived, _with instructions on how to find it again if needed._

**Experiment/ Design/ Plan entities:**
- Named researchers (and trial managers?) get an email when a management record is submitted.
- Then there are two options:
1. Immediate updates when a change is made
2. A daily summary of changes for that experiment (or for multiple experiments if a trial manager?)

**Data administrators** 
Get emails for all changes?

As you can see, there are still a few questions so need some more discussion about what is and isn't possible before specifying fully. We may also need to come back and refine this further at a later stage.

Labelled a must do issue because people are missing important information due to the number of emails.

This was broken down into smaller sub-issues:

- #395 
- #597
- #605

**Comment by aislinnpearson** [comment]
> Then there are two options:
Immediate updates when a change is made
A daily summary of changes for that experiment (or for multiple experiments if a trial manager?)

Following discussion with Paul we agreed that we would implement this as a global option first (easier to code), then move to the experiment by experiment options if this is requested at a later date.

Also, the above two options should also be applied to Proposals (not experiments/ designs/ plans)

**Comment by aislinnpearson** [comment]
Duplicate issue for #395 - please close this too once this issue is resolved.

**Comment by paul121** [comment]
Moving this to 2.20 milestone

**Comment by paul121** [comment]
I think we can close this now - lets open new issues for future (inevitable) changes!
