### ISSUE TITLE
Bug: Experiment Programs visualised multiple times

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#536]
I came across a visualisation bug yesterday where the research programs seem to be repeated multiple times (see below) - possibly something to do with the number or experiment or proposal entities they are referenced by? From what I can tell it is only the Research Programs that has this problem

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d9c1c006-fa2b-4d0f-affe-3bbcf1899aff)

**Comment by paul121** [comment]
Good catch! This happened when I added the experiment category filter and thus added a relation join to the database query. I've fixed this so results are aggregated and grouped together rather than split to multiple rows.
