### ISSUE TITLE
Experiment Module: Improve Visualisation of Related Entities to Experiment Boundaries

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#539]
Following on from issue https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/524 it would be good to include this same sort of visualisation for experiment boundaries described in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/524#issuecomment-1678185881 to the plot attributes. This would allow a user to click on a plot and quickly get back to the plan/ design/ experiment associated with that boundary.

Ideally we would also be able to go back to all the plots associated with the boundary.

Once https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/277 and https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/377 are resolved, we should also think about how plots from previous years can be accessed/ visualised (see issue #540 ).

Sorry @paul121 - the experiment boundary aspect of this only occurred to me after our call last night. Let me know if there are any complexities here that I have missed...

**Comment by aislinnpearson** [comment]
This also looks awesome @paul121, although I noticed there is no link to the plots. I think we discussed this and I can't remember the reason why but can you remind me so I can let the other users know?

**Comment by paul121** [comment]
> I think we discussed this and I can't remember the reason why but can you remind me so I can let the other users know?

Yes this is partially because there could be many 100s of plots. Instead, we could include the link to a Plan's Plots page. But this already exists as a tab (next to Related) on the Plan's page. So I guess it is a question if we want that in the Related page, too.
