### ISSUE TITLE
Design Entity: Remove plot data fields

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#549]
Following a meeting with the statistics team, I have been asked if we can please remove the following data fields from the Design entity:

Number of blocks 
Number of main plots per block
Number of main plots
Number of subplots per main plot
Number of subplots
Number of sub-subplots per subplot
Number of sub-subplots
Horizontal row spacing
Vertical row spacing
Plot length
Plot width
Plot area
Number of rows
Number of columns

Where these fields currently contain data, please can we the information which into the Notes field on the Statistical Design tab.

The thinking behind this is that this is fully described and annotated in the plot attributes/ csv and GeoJSON uploads, and this is not only duplication but often a poor description of more complicated experiment designs.

**Comment by paul121** [comment]
In the next release we will migrate + hide these data fields with an update hook. In the subsequent release we will remove these data fields in another update hook. Lets move this issue to 2.18 once we release 2.17
