### ISSUE TITLE
Design Entity: change required fields

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#553]
Although in our initial design phase the Farm thought it would be great to have required fields for each stage of development (planning, in field, etc), the testing phase has shown that having so many required fields add complexity when trying to set up a new experiment and that ideally these would only be functional. 

For this reason, on the Design entity, please can we amend the required fields so that following fields which are currently required should please be changed to optional:

- Rotation as Treatment (default value is no)
- Varying plot sizes (default value is no)
- Additional Blocking Constraints (default value is none)
- Hypotheses
- Crop Management Restrictions (default value is no)
- Genetically Edited (GE) Material (default value is no)
- Genetically Modified (GM) Material (default value is no)
- Off-label Products (default value is no)
- Licence and Permissions (default value is no)
- Physical Obstructions (default value is no)

The one exception to this is the revision log message, which we would like to make a required field so this will be quoted in email alerts.

**Comment by paul121** [comment]
The only field I actually made non-required was Hypothesis. All others I was able to set a default value of "No". Earlier I thought this wouldn't be quite so easy... well, silly thing, turns out I needed to set the default value in the code to `0` not `FALSE`! Great improvement
