### ISSUE TITLE
Rothamsted module: restrict users from changing their username and email

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#568]
As discussed in the meeting on Tuesday, we noticed that people can updated their own usernames and email address. We would prefer to suppress this so we can restrict users to their Rothamsted user names and email. 

Speaking to @paul121 it seems this is easy enough to do for the usernames as there is built in Drupal functionality and it can be addressed through issue #373 

Emails is more complicated and we agreed this would be manually removed from the user interface to hide the functionality.

**Comment by paul121** [comment]
@aislinnpearson is it OK if

**Comment by paul121** [comment]
Done!
