### ISSUE TITLE
Change the factor exposed filters to be checkboxes

### ISSUE THREAD

**Issue by paul121** [Rothamsted-Ecoinformatics/farm_rothamsted#58]
See description and screenshot in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/26#issuecomment-972100483

Not sure the best way to go about this. Likely changing the existing views filter to render checkboxes instead of a select list for each factor type? I don't remember seeing any views exposed filters that use checkboxes so this might require some additional themeing to make sure they work OK in the exposed filters area. It would also be nice to minimize the amount of space the checkboxes take up.

**Comment by aislinnpearson** [comment]
This was resolved by @paul121 in https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/200
