### ISSUE TITLE
Rothamsted Core Permissions: Remove previous user types

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#581]
Following on from issue #373 a reminder to delete the old user types once everyone on the system has been updated to the new user types.

**Comment by paul121** [comment]
Specifically we only need to remove the farmOS core roles (Manager, Worker and Viewer), which can be done by uninstalling the core `farm_role_roles` module. @aislinnpearson after the deploy is complete and you have updated user roles, assign this issue to @mstenta for him to do make the change

**Comment by mstenta** [comment]
Done!
