### ISSUE TITLE
Quick Forms; Specification error on Fertiliser Quick Form

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#588]
Talking with Had today, she ahs found a specification error on the Fertiliser quick form where 'Total Volume Applied' on the Fertiliser tab of the Fertiliser, Compost and Manure quick form is a volume where it should be a weight.

Please can we:
1. Change the name of the data field to 'Total Applied'
2. Change the type of quantity from a weight to a volume.
3. Change the units available so we remove litres and ml, but add tonnes (t)
4. I'm sorry to ask @paul121 but I think we will also need an update hook to update the database. For this list point I've asked @hadewy to join us next Tuesday, because she is translating all the North Wyke records and having to correct this error there so has the most insight into what is involved. 

After the call we might want to split this into two or more separate issues.

**Comment by aislinnpearson** [comment]
Aislinn to find date of field creating/ first edit so we know how far back to push the changes

**Comment by paul121** [comment]
Hey @aislinnpearson, looking closer at this I have two questions. First, the units for this quantity are coming from the `Volume` taxonomy hierarchy that is configured on each instance. Would you like to create a new `Weight` hierarchy? Or maybe just hard-code the weight options you want in the quick form? (I think g, kg, and t?)

![volume-units](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/671c363c-b34b-4451-8961-f41e3a152b96)

Second, what exactly would we like to do in the update hook? I can update all of these to have a `Total applied` label, but if some quantities actually used a ml or l unit, it maybe isn't correct to change their measure to be `weight`?

Fwiw, here is a [quantity query](https://rothamstedfarm.farmos.net/quantities?log_name=&label=Total+volume+applied&value_min=&value_max=&units=All&measure=All&type=All&log_timestamp_start=&log_timestamp_end=&log_status=All&log_type=All&asset_target_id=&items_per_page=50) you can use to see what has been submitted in the past... it looks like `0 ml` has generally been used to represent "nothing applied", maybe?

**Comment by aislinnpearson** [comment]
Update hook to come later. See issue #594

**Comment by paul121** [comment]
We also decided to use a new Weight taxonomy hierarchy
