### ISSUE TITLE
Zeros not displaying in plot attributes

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#590]
Hi @paul121 

We found a small (possible?) bug today where column levels with the name '0' _don't_ upload to the plots tab (instead it's just a blank cell) but _do_ upload to the variables tab.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/0e637e08-d65a-4631-ae03-59e3820de9a3)_
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/9e85f7f2-0a02-4b83-986c-caf28b719070)

The reason I am not sure if it's a FarmOS bug is because excel. I wasn't sure opening the csv in excel was removing the zeros from the document before we uploaded it (although I would have expected to get an error if this happens, and it uploaded fine). Double checking by opening the file in QGIS also suggests the zeros are still there but maybe not displaying in farmOS?

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/955562ae-b902-4a83-911b-5d969c1eb627)

The files can be accessed here: https://rothamstedfarm.farmos.net/plan/111

**Comment by paul121** [comment]
Good catch! These values are being uploaded correctly, there was just a bug that was not displaying the 0 values. This can be a common bug because the number `0` or string `"0"` can be equated to an `empty` or `null` value in PHP. Easy fix.
