### ISSUE TITLE
User permissions: enable people listed as statisticians and data stewards to edit

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#591]
HI @paul121,

We found a specification error/ oversight in the user permissions today, whree people who are (1) research editors (or research leads) and (2) are _only_ listed as data stewards or statisticians on proposals and experiments _can't_ edit the proposals or experiments (they need to added as contacts on proposals or researchers on proposals _in addition_ to being listed as data stewards and statisticans).

Could we please update this so the logic is:

Proposals: Research Editors and Research Leads listed as contacts, statisticians or data stewards can edit associated with
Experiments: Research Editors and Research Leads listed as researchers, statisticians or data stewards on the experiment _or_ Statisticians on the Design can edit associated with.

Ideally we'd update this as part of 2.17.1 as we are going through the process of adding Spring crop proposals now, but we can chat about it on Tuesday to see what's possible.

**Comment by paul121** [comment]
> Proposals: Research Editors and Research Leads listed as contacts, statisticians or data stewards can edit associated

I added this in 2.18.0.

> Experiments: Research Editors and Research Leads listed as researchers, statisticians or data stewards on the experiment or Statisticians on the Design can edit associated with.

@aislinnpearson sorry I missed this - but Experiments only have a single "researcher" reference. We can do the "statistician" on the design, but I wanted to double check how that might overlap with experiment permissions.

**Comment by paul121** [comment]
>  or Statisticians on the Design can edit associated with.

I've added this for 2.19. But @aislinnpearson can confirm that the Experiment permissions are working as expected, they only have a single `researcher` reference field?

**Comment by aislinnpearson** [comment]
@aislinnpearson to add this to the documented permissions and specify follow on issue of how Research Leads/ Research Editors are presented on Proposals, Experiments and Designs (see issue #610).

Happy for you to close this @paul121 if the new issue I have created answers your question (although it will need some additional specification work as mentioned in the issue).
