### ISSUE TITLE
E-mail Alerts: Alerts for NEW Research Entities, Assets and Logs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#597]
@paul121 - as promised the specifications for e-mail alerts created with new Research Module Entitles

**Email alerts for New Research Module Entities**

1. These are sent by default at the time that the entity is created (at the point where the user has pressed save, and thereby created a new entity). 
2. Emails are sent by default to anyone who is named on a Research Entity unless that person created that entity themselves (in which case it is only sent to other named Researchers). 
3. These e-mails have security and authenticity implications. They cannot be switched off/ you cannot opt out.

Content of the e-mails in the attached

~~[E-mail Alerts - Alerts for new Research Entities.docx](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/13755240/E-mail.Alerts.-.Alerts.for.new.Research.Entities.docx)~~

Version 2 of the e-mail content, which includes Logs and updated logic for each type of entity (following the smae form at issue #605):

~~[E-mail Alerts - Alerts for NEW Research Entities.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/13888708/E-mail.Alerts.-.Alerts.for.NEW.Research.Entities.pdf)~~

Version 3 of the e-mail content following [comment](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/597#issuecomment-1961498213) below.

[E-mail Alerts - Alerts for NEW Research Entities (1).pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/14387733/E-mail.Alerts.-.Alerts.for.NEW.Research.Entities.1.pdf)

**Comment by aislinnpearson** [comment]
@paul121 - updated file as promised (see issue description above), which now includes the farm name and logs as discussed yesterday

**Comment by paul121** [comment]
Okay, I believe I have implemented everything here, with just a few exceptions:

- For log notifications it is complicated to include the "Asset name" that it references because it is very possible the log will reference many assets.
- Though not requested, I considered adding the Experiment name instead of the Asset. But this is challenging as well. It is hard to add the experiment/plan that is relevant to the user because we are generating a generic notification email for many users, potentially a log referencing an asset relevant to multiple experiments, instead of an email that is unique to each user.
- I've removed the `[hyperlink list]` placeholder that would reference the data administrators. This was included in each email. I'm not sure if there is a good way to embed a list of links for this in each email. Another option would be to make a more specific help/data administrator contact page, which we could then simply link to. This would be an easy add in a followup.

**Comment by paul121** [comment]
Also to note: I did not implement the`[period]` part of the email update in this pass because we have not yet implemented the ability to change the period for notification updates. This was specified on proposals and experiments.

**Comment by aislinnpearson** [comment]
Outcome of testing for EXPERIMENT ASSETS

**Testing functionality if you are _not_ the person logged in:**

Testing method:
Signed in as Harpenden Trimble (user type: Farm Manager) and set up a new user using the Brooms Barn Trimble email address (user type: Research Lead). I then checked the associated e-mail account, compared the text in the e-mail to the document, and clicked the hyperlinks in the e-mail to make sure they were correct. Each log/ entity created was as complex as possible (all questions answered, added multiple fields where this was an option, uploaded files). For the experiment designs I also tested it by adding a Statistician _not_ named on the experiment.

Excluded from testing:
I didn't log in as different user types and test the e-mail functionality for different user types. I also didn't test a simpler version of the form. I can do this if we are concerned about the functionality (and it may be worth doing a more complex test as people won't know if they didn't receive an e-mail). I also added Harpenden Trimble (the logged in user) to the proposal and experiment I created during this testing, and again didn't get any alerts.

- **Set up a new user:** received login e-mail. Sent to junk but otherwise perfect.
- **Created a Researcher for the new user:** received e-mail. Sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)
- **Created a new Research Program with the new user named:** received e-mail. Sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)
- **Created a new Proposal with the new user named:** received e-mail. Sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)
- **Created a new Experiment with the new user named:** received e-mail. Sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)
- **Created a new Experiment with the new user named in the experiment and design, and then tested again with a user named in the design only:** received e-mail if named on the experiment, but not if named as the statistician on the design. Again, sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)
-  **Created a new Plan with the new user named:** received e-mail. Sent to junk but otherwise perfect (although see above comment from Paul about linking to a Data Steward)

**Testing functionality if you are _not_ the person logged in:**
This was checked with the FarmOS version 3 testing (see issue #606). This was all done with the Harpenden Trimble setting up assets in its own name with a variety of user profile types. NO e-mails were received (which is the correct functionality: e-mails are only sent if someone other than you adds you to an entity or creates a log associated with an entity you are named on. Basically we assume the user knows what they did, and that their account is secure.)

**Not sending to specified users:** The only e-mail that doesn't send is to the Statistician associated with the Design. This relates to an issue we raised in the call yesterday where, if a Statistician is named on the Design, they aren't also named on teh experiment by default. @aislinnpearson to discuss with @paul121 if worth discussing both these issues simultaneously. **Must Fix**
**Wording:** There are a couple of places where my wording could be better. **Should do** but can be in next release.
**Visualisation:** The long links look a bit untidy. This is fine for now, but a 'nice to have' issue would be to tidy them up a bit, add bold in places, etc. I don't know if this is possible though (default e-mails as rich text?). **Nice to have**
**Visualisation:** Suppress the entity number, which is currently published next to the entity name. A few people have asked me what this is, and get a bit confused by it when it appears in the software. I suspect this will also become a problem with the e-mails. **Nice to have**
**Statistician:** Not related to this issue, but I realised today that not every experiment is designed by a statistician, and this field on the experiment design can be a bit restrictive. We might want to remove this restriction, depending on internal processes. **Won't fix/ Monitor**

**Comment by paul121** [comment]
> I didn't log in as different user types and test the e-mail functionality for different user types. I also didn't test a simpler version of the form. I can do this if we are concerned about the functionality (and it may be worth doing a more complex test as people won't know if they didn't receive an e-mail).

Never hurts to test! But will say that the logic here should be mostly agnostic of the user's role. If a researcher is listed on any of these research entities as specified they should get an email.

>  received e-mail if named on the experiment, but not if named as the statistician on the design.

I will take a look at this :eyes: 

> Visualisation: The long links look a bit untidy. This is fine for now, but a 'nice to have' issue would be to tidy them up a bit, add bold in places, etc. I don't know if this is possible though (default e-mails as rich text?). 

There might be two parts to this. When we review this on the call it looked like Outlook was drastically increasing the size of the links you were receiving, I think they do this to make them "secure", and am not sure how to work around that. By default all of these links will just be the farmOS URL + a path to the asset/log/research entity.

Separately, rich text emails/HTML emails would be a nice improvement. That could allow for emails with proper in-line links embedded in sentences and open the door to other visual improvements. I don't have experience doing this in Drupal but only imagine there is a way. @mstenta do you have insight or ideas about how complex this might be?

**Comment by mstenta** [comment]
> Separately, rich text emails/HTML emails would be a nice improvement. That could allow for emails with proper in-line links embedded in sentences and open the door to other visual improvements. I don't have experience doing this in Drupal but only imagine there is a way. @mstenta do you have insight or ideas about how complex this might be?

I haven't done this since Drupal 6/7, and recall it being a pain back then, but maybe things have improved. It looks like the modules that I used in the past (https://www.drupal.org/project/mimemail / https://www.drupal.org/project/htmlmail) do not have stable D10 versions... but this new one looks promising: https://www.drupal.org/project/symfony_mailer

If it were me I would probably just keep things simple and stick to plain text emails. Depends on how much value it adds and if that's worth the complexity. :shrug:

**Comment by aislinnpearson** [comment]
Hi Both,

> If it were me I would probably just keep things simple and stick to plain text emails. Depends on how much value it adds and if that's worth the complexity

I'm slightly torn on this. From a development perspective, I agree. It's a lot of work for small gain. But the more we are pushing our scientists into using farmOS the more I get the frustrated e-mails saying 'I can't find anything!'. I think so far we've built a great system but because it's the first version we have been focusing on making it work, rather than being user friendly. I don't know how much this will play into that ongoing issue. My suggestion is that we add it as an issue for tracking, and see what the feedback is once the software goes live. If I get a lot of push back we can add it to the next phase of work, which will focus on making everything more user friendly. But I agree. Definitely something to take lightly given the complexity.

> I will take a look at this 👀

Amazing. Thanks Paul.

> There might be two parts to this. When we review this on the call it looked like Outlook was drastically increasing the size of the links you were receiving, I think they do this to make them "secure", and am not sure how to work around that. By default all of these links will just be the farmOS URL + a path to the asset/log/research entity.

Ah. Okay. I'll ask our IT department if we can do something about this, and make sure the actual live instances are on our safe senders list (which I think they are, but can't hurt to check!)

**Comment by mstenta** [comment]
> I'm slightly torn on this.

Don't let me dissuade! It sounds like the value is worth the complexity! And to be clear it isn't an immense amount of complexity. So go for it if it will help! I am not opposed! :smile:

**Comment by aislinnpearson** [comment]
E-mail testing for logs:

Process: I created an experiment, design and plan that had three named users (myself, Harpenden Trimble and Brooms Barn Trimble). For the first round of testing I used my own account (Aislinn) to test all the quick forms (including group and movement) to reference the experiment boundary. All users had the 'log alerts' option switch on. For the second round of testing I referenced plot assets and again submitted logs via the Quick Forms. In this round of testing I switched off log alerts for Brooms Barn but no one else.

Outcome:
- **Emails all sent as intended:** The e-mails were all sent as intended. For the first round of testing, all users got an e-mail alert except the person submitting the form. For the second round of testing the e-mails again only went to the users who had log alerts switched on. The person submitting the form, and the person who had switched the alerts off, didn't get alerts.
- **Format:** The e-mails needed some slightly clearer formatting. See attached. This can be done either in this issue or in a subsequent one. I've attached an updated specification to the[ issue description](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/597#issue-2054338786). **Must Do**
- **Format:** It occurred to me that it would be quite nice to reference the Quick Form Name rather than the Log Name if that's possible, although I don't know how this would work if someone submits a log without a quick form (e.g. an observation). **Nice to have**
- **Follow up issue:** The e-mail alerts for the logs include the line 'If you notice anything that needs to be amended, please comment on the log and mark it as 'Needs Review' but this functionality hasn't been released yet. I don't know if we should take it out, and create a follow up issue to make sure it is added back in once this feature is live?
- **Spelling/ Grammar:** I hadn't thought about this until I'd seen it but there is a line in the e-mails that reads _'[Name] has added a [Log Type] '_ This works if the log type starts with a consonant (harvest, drilling), but not a vowel (activity, input, observation). A small thing for which I don't know if there is an easy fix (ideally the fix would mention the 'a, e, i, o, u' element so we don't have to worry about this if we create new logs or refer to quick form names instead?).
- **Harvest logs:** I can see how people will get confused receiving multiple different types of harvest logs for the same experiment. This is a known issue, which I hope we will get to address this year, but for now I suggest we leave things as they are.

**Comment by aislinnpearson** [comment]
Follow on issues:
- #624 
- #525
- #578 
- #574 
- #625
- #626
- #627
- #628
- #629 
- #630

**Comment by paul121** [comment]
Thank you so much for the diligent testing & documentation in these new issues @aislinnpearson !

> Version 3 of the e-mail content following https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/597#issuecomment-1961498213 below.

I've just pushed a change to simplify the log emails as we discussed. I'll close this issue and do follow ups in separate issues.
