### ISSUE TITLE
Experiment Module: Comment on Assets

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#604]
See parent issue https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/574 but essentially extend commenting functionality to Assets. 

This issue may need additional consideration as some assets are more heavily involved in experiments (.g. plant assets, land assets, sensor assets) than others (building assets, equipment assets, etc). For this reason the functionality is perhaps more relevant to some assets than others.

**Comment by paul121** [comment]
> For this reason the functionality is perhaps more relevant to some assets than others.

@aislinnpearson by default farmOS core lets you comment on *all* asset types. Will this be OK? Do we need to restrict functionality in any way for each asset type?
