### ISSUE TITLE
E-mail Alerts: Alerts for Edited Research Entities, Assets and Logs

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#605]
**Email alerts that capture edits on Research Entities, Assets and Logs**

These e-mails do not have security and authenticity implications. They can be switched off/ you cannot opt out.
Specifications and content of the e-mails in the attached.

~~[E-mail Alerts - Alerts for edited Research Entities, Assets and Logs.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/13876204/E-mail.Alerts.-.Alerts.for.edited.Research.Entities.Assets.and.Logs.pdf)~~

Updated specifications, which includes logs and Farm Name

[E-mail Alerts - Alerts for EDITED Research Entities, Assets and Logs.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/13888752/E-mail.Alerts.-.Alerts.for.EDITED.Research.Entities.Assets.and.Logs.pdf)

**Comment by aislinnpearson** [comment]
@paul121 - updated specifications added here as well (see description above)

**Comment by aislinnpearson** [comment]
Following our call today we agreed @paul121 would start with what is possible, I'll test it in a test instance and we can go from there.

**Comment by paul121** [comment]
Yes - in this first pass I've modified the existing `updated` emails to be similar to the `new` email alerts as recently changed in #627 . Aside small differences like "new/updated" the main difference is that the updated emails will include a list of the field names that were updated (but not include the field values).

**Comment by aislinnpearson** [comment]
This looks great. I found a few typos and word changes, which I will add to go out in this release.

**Comment by aislinnpearson** [comment]
**LOGS**

A few minor changes (marked in red):
- Please can we shorted/ amend the e-mail title to _'[Farm Name]: Edited [Log Type]'_
- Please can we edit _'changed values'_ to read _'The following data fields have been changed'_
- Please can we include the revision message (or _'None'_ if there isn't one - see associated issue #565) 
- Please can we edit _'please check the details are correct'_ so it reads _'please check the **changes** are correct'_

Visualised changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/9b115654-e747-46cc-ab40-c791e48af3a3)

Currently renders like this:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d12ac051-713b-46d1-ac12-a0846815b145)

**Comment by aislinnpearson** [comment]
**RESEARCHERS**

A few minor changes (marked in red):

- Please can we edit 'changed values' to read 'The following data fields have been changed'
- Please can we include the revision message (or 'None' if there isn't one - see associated issue https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/565)
- Please can we edit _'You will continue to receive updates about this Research Profile if it is edited by a Farm Manager or Farm Data Administrator'_ so it reads _'You will continue to receive **e-mail** updates about this Research Profile.'_

Visualised changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/fee2e82e-45bb-46f0-8a60-76b2f3c0c54a)

Currently renders like this:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/ef2d99a2-26d0-499d-a775-8ca871263420)

**Comment by aislinnpearson** [comment]
**RESEARCH PROGRAMS**

A few minor changes, all the same changes as requested for _Researchers_ above.

Visualised changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/78fe3db4-448c-4475-9157-837aa362be19)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/b678d800-2d57-4c28-897b-17fe127c074d)

**Comment by aislinnpearson** [comment]
**PROPOSALS**

A few minor changes, all the same as for Researchers above with one slight variation on point 3:
- Please can we edit 'You will continue to receive updates about this Proposal' (already shorter than in the Researcher and Research Programs) so it reads 'You will continue to receive **e-mail** updates about this Research Profile.'

Visualised changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/c977b27d-7f1d-4293-9f0e-cc805469d179)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/da1259d5-af9c-4f69-b61f-c96bd6531699)

**Comment by aislinnpearson** [comment]
**EXPERIMENTS**

A few minor changes: 
In addition to the changes described for Experiments above, please can we:
- edit the title, changing it from _'[Farm Name]: Update to your Research Experiment in farmOS'_ so it reads _'[Farm Name]: Update to your Experiment in **F**armOS'_
- edit _'[Name] has edited an Research Experiment you are associated with in FarmOS'_ so it reads _'[Name] has edited an Experiment you are associated with in FarmOS. '_. 
- edit _'To view the Research Experiment please click the link below **:**'_ so it reads _'To view the Experiment please click the link below **.**'_ (includes replacing the colon with a full stop).

Visualised changes:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/97ae9d4d-ef2a-45d7-ad54-3087537aacfe)

Currently rendering as:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/3b38edb3-6ec1-4703-ade5-42cbcdbc4050)

**Comment by aislinnpearson** [comment]
**DESIGNS**

In addition to the changes described for Experiments above, please can we make the following changes (note these are the same for the Experiments, but for Designs):

- edit the title, changing it from _'[Farm Name]: Update to your Research Design in FarmOS'_ so it reads _'[Farm Name]: Update to your Experiment in FarmOS'_ (note the _F_ in _FarmOS_ is already capitalised here).
- edit _'[Name] has edited an Research Design you are associated with in FarmOS'_ so it reads _'[Name] has edited an **Experiment** Design you are associated with in FarmOS. '_.
- edit _'To view the Research Design please click the link below **:**'_ so it reads _'To view the Experiment Design please click the link below **.**'_ (includes replacing the colon with a full stop).

Visualised changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d402ce4d-459c-4993-a8e1-44e24417fe2d)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/a03de498-2b3b-42fe-9ef5-cbcce2d51952)

**Comment by aislinnpearson** [comment]
**PLANS**

Similarly for the changes described for Experiments and Designs above, please can we make the following changes:

- edit the title, changing it from _'[Farm Name]: Update to your Research Plan in FarmOS'_ so it reads _'[Farm Name]: Update to your Experiment Plan in FarmOS'_ (note the F in FarmOS is already capitalised here).
- edit _'[Name] has edited an Research Plan you are associated with in FarmOS'_ so it reads _'[Name] has edited an Experiment Plan you are associated with in FarmOS. '_.
- edit _'To view the Research Plan please click the link below :'_ so it reads _'To view the Experiment Plan please click the link below .'_ (includes replacing the colon with a full stop).

Visualised Changes:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/10cec91c-2ffc-4f6b-be13-c3710317f1a6)

Currently rendering as:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/233869d5-cd62-41fd-ad38-3b698c3f3ad8)

**Comment by aislinnpearson** [comment]
Hi @paul121,

All the minor comments as promised... although I just noticed I haven't always capitalised the entity name. Would you mind checking for that as well? Sorry - it would take me ages to check the screen grabs, although I have done it in the document attached below.

As an aside, I noticed that when you add an experiment boundary, you only get a notification to say that a location has been added. Similarly, when you upload your variables or geoJSON you only get a notification to say that you have added files. Is there a nice way we can change the alert so that these specific actions generate a more specific message in the e-mail somewhere? Happy to chat this through if needed.

Here is the actual word document as a PDF:
[E-mail Alerts - Alerts for EDITED Research Entities, Assets and Logs.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/14851311/E-mail.Alerts.-.Alerts.for.EDITED.Research.Entities.Assets.and.Logs.pdf)

**Comment by paul121** [comment]
> although I just noticed I haven't always capitalised the entity name. Would you mind checking for that as well?

Done! I found a few, hopefully all of them.

>  Is there a nice way we can change the alert so that these specific actions generate a more specific message in the e-mail somewhere? Happy to chat this through if needed.

There are some ways we could do this, but lets open a new issue to track it. It wouldn't be very complicated to just add additional text into this existing email when that is the case.
