### ISSUE TITLE
Plan assets hidden from plan view

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#613]
When trying to add an experiment boundary to the plans you get the below error. See here for the actual asset I created (I created two actually with two different KMLs and it happened both times): 

https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/asset/41
https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/asset/230

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/e8f05f39-1bd6-4620-b30e-c74ba7f57101)

The error appeared when navigating to the plot geometry tab: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/plan/3/update-plot-geometry

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/a01b6eb8-5115-4c71-996a-e2078d42a60d)

But I had no actual problems with uploading the plot geoms:
https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/plan/3/plots

The error is also on the page with the experiment variables: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/plan/3/variables

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/5b6aae20-6039-4b84-89b7-1eb1389401c4)

But again the actual variables uploaded just fine: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/plan/3/plots

Finally, the experiment boundary gets added as an asset but does not display:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/1d8016ff-cdda-4c6a-ae17-3e7b6e1a02b5)

When trying to replace the KML file on the experiment boundary asset itself I get this error when trying to add a new KML file:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/77b4694c-05e6-4952-bb49-e83b802d14e0)

**Comment by paul121** [comment]
> The error appeared when navigating to the plot geometry tab

@aislinnpearson thanks, you found another small bug in one of our dependencies! I believe this is just a warning and not a major issue, but good to know. In the demo environment I have warning messages turned on because it helps to catch small bugs like this but normally these are turned off in production.

> Finally, the experiment boundary gets added as an asset but does not display:

Yes... it seems like none of the Plan assets are being displayed. I think I know why.

**Comment by paul121** [comment]
Yes, I found the fix. The experiment boundary was being created just fine, you just couldn't see it being referenced on the plan. Fixed, although I may not get the demo updated right away.

**Comment by aislinnpearson** [comment]
> Fixed, although I may not get the demo updated right away.

No worries @paul121 - if you've fixed and it isn't appearing your end then it I don't think we need to update the demo site. :)
