### ISSUE TITLE
FarmOS 3.0: Confusion in moving locations

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#614]
I was a bit confused about how the movement location quick form works, and if the below was an error or a misinterpretation on my part. 

I created this asset here, which appears under All Locations: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/asset/232

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/79652436-3745-4a73-b073-5b1749b5d155)

When I want to move it via Toggle drag and drop it initial lets me move it:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d014f4cc-130a-4be7-b135-9801c215bea1)

But when I press save I get this error:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/4e23b721-5093-4a54-ad6d-9851cb61f0f0)

I then tried moving the asset with the movement quick form (@paul121 has since told me this doesn't work if an asset is fixed, which this is, but I include it for completeness in terms of how I thought about the problem):

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/8a12fb95-b1b6-4f88-af92-213365d0d915)

The movement quick form submitted successfully, and the log exists with the new location: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/log/35

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/3a31dc91-7f6c-4f72-aa31-f18f13d4f00f)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/d89b74ba-9160-4b81-990e-8d6c7028235f)

But the location hasn't actually changed. For this I had to change the _parent_ (which I guess is different from the location?)

I then tried to use the Movement quick form to move a plant asset and again the quick form submitted:
https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/log/36

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/0e271bed-ba63-4945-8e25-73a2c3885b99)

But the location of the asset itself hasn't changed:
https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/asset/39

![Uploading image.png…]()

I have full admin rights, so I don't think that was the limitation...

**Comment by paul121** [comment]
Hey thanks for documenting this @aislinnpearson , you found a bug in the location hierarchy form! We'll get this fixed soon.

Otherwise, the movement quick form and movement logs are working as designed. Fixed assets will always use their intrinsic geometry as the defined location. Typically fixed assets will be have a `parent` location (also fixed) that is used to build a hierarchy of locations. Otherwise, the movement logs can be used to update "movable" (non-fixed) assets. You may be interested in this documentation of this [Location Logic](https://farmos.org/model/logic/location/#logic)

**Comment by aislinnpearson** [comment]
This sounds good to me @paul121. I wonder if that should be a warning or error that appears if you attempt to submit a movement quick form for a fixed location asset? That was what really confused me - that the form would submit (or if it doesn't want to submit it would be nice to know why?)
