### ISSUE TITLE
FarmOS 3.0: Error when creating a new proposal

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#615]
When trying to create a new proposal on the platform.sh site I get the below error. 

> Fatal error: Declaration of Drupal\farm_rothamsted_experiment_research\Plugin\Validation\Constraint\RothamstedStatusConstraint::__isset($option) must be compatible with Symfony\Component\Validator\Constraint::__isset(string $option): bool in /app/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment_research/src/Plugin/Validation/Constraint/RothamstedStatusConstraint.php on line 57

I am not sure if this is related but I also got the below error every time I tried to 'add multiple' to a question (e.g. add more than one researcher)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/fa7f8239-3d75-400f-84ee-6a6d1ea9060e)

So I tried to submit the form _without_ any of the add multiple fields (required data fields only) but got the same issue, so may be two separate problems? 

> Fatal error: Declaration of Drupal\farm_rothamsted_experiment_research\Plugin\Validation\Constraint\RothamstedStatusConstraint::__isset($option) must be compatible with Symfony\Component\Validator\Constraint::__isset(string $option): bool in /app/web/modules/farm_rothamsted/modules/farm_rothamsted_experiment_research/src/Plugin/Validation/Constraint/RothamstedStatusConstraint.php on line 57

**Comment by paul121** [comment]
This was a simple fix, both cases (creating a proposal and adding multiple values) should be fixed.
