### ISSUE TITLE
FarmOS 3.0: Trouble selecting Statistical Design

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#617]
When trying to submit a Design Entity form there is an error with the Statistical Design. If Blocking Structure = completely randomised design then Statistical Design defaults to completely randomised design by default (it is the only option). I then selected T-Latinization but when I tried to submit got the below error:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/a9e92beb-4d09-48e0-97c9-9e22632f525f)

and the Statistical Design comes up blank:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/94bb1fde-7fe4-4eae-8932-efe1d1449356)

However, what I can do is select a different design (e.g. Resolvable block design) which allows me to submit the form, and then go back and edit the form so that it contains 'Completely randomised design'. See for example the revisions here:

Initial submission: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/rothamsted/design/5/revisions/9/view
Edited submission: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/rothamsted/design/5

**Comment by paul121** [comment]
@aislinnpearson I believe this issue is related to file uploads during the same form submission via #616

Can you test again and see if this has been fixed?

**Comment by aislinnpearson** [comment]
Yup. Tested and works perfectly. Can be closed.
