### ISSUE TITLE
FarmOS 3.0: Moving plant assets

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#619]
@mstenta I think I found a bug where you can't move a plant asset from the edit page (the move button from the asset page _does_ work, see this log and its revision history: https://pr-12-qcotibq-2mu45anerqtvq.uk-1.platformsh.site/asset/239).

At first I thought it was because I hadn't initially specified a location when creating the plant asset, but I had the same problem when the asset had a location.

Images of the error messages below.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/f98b321f-a045-4a5a-a04d-218dd64cfa02)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/be99acff-35a2-4f0b-9412-edb7d73e29f0)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/e448bd14-136d-463e-9426-d0829e6b7c28)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/1d21bb3c-2038-4848-8f47-126e28f20cc7)

**Comment by aislinnpearson** [comment]
Spoke to @mstenta about this and is Rothamsted specific.

**Comment by paul121** [comment]
This feature needed to be updated to use the new movement quick form actions. A simple fix, also made a change so that this appears in the "Location" tab for the asset.
