### ISSUE TITLE
FarmOS 3.0: Design Management tabs not visualising properly

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#620]
@paul121 and I have discussed this but I don't think I submitted an issue, but the management tab on the Design entity isn't rendering properly in 3.0.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/5b895531-d231-442b-a54a-b00544f19215)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/ea97962f-642a-42c4-a1ab-53766ae0fb70)

**Comment by paul121** [comment]
Unfortunately I don't think we'll be able to do these nested vertical tabs in Drupal 10. I believe this functionality may have been originally provided via the Field Group module but we needed to remove this module as it was conflicting with how the new vertical tabs in the Asset/log forms (see #612).

Reading these Drupal [user interface standards for vertical tabs](https://www.drupal.org/docs/develop/user-interface-standards/vertical-tabs) too, it says to not use nested vertical tabs nor multiple sets of vertical tabs on the same page. I think there is good reason for this.

A simple change would be to use a collapsible fieldset for each sub-management category. What do you think of this idea @aislinnpearson ? I will make the change and push to the demo site now so you can review.

![Screenshot from 2024-02-20 14-39-58](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/a108b50a-307b-4a9f-9ca5-129cf8a89004)

**Comment by aislinnpearson** [comment]
I'm very happy with this. It looks good. Thank you Paul
