### ISSUE TITLE
E-mail alerts: Include description on how to flag and comment on logs.

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#625]
Follow up issue from #597: 

The original specification for the e-mail log alerts includes the line 'If you notice anything that needs to be amended, please comment on the log and mark it as 'Needs Review' but this functionality hasn't been released yet. This is a follow up issue to make sure it is added back in once those features are live.

- #578 
- #574

**Comment by paul121** [comment]
The log emails include this language :+1:
