### ISSUE TITLE
E-mail alerts: review wording of alerts for experiment assets

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#627]
Following my [comment here](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/597#issuecomment-1957428633), there are a couple of places where my wording in the e-mail alerts for the experiment assets could be better. This is just a reminder to review them in the next push.

**Comment by aislinnpearson** [comment]
Hi @paul121,

Here are the minor edits I'd suggest. I have also copied and pasted an example of how the e-mails are rendering internally for each to give you an idea of what people are seeing. They should look tidier still when we address issue #639. Please feel free to check my spelling and grammar - or simplify what I have written further if you can see obvious improvements! I'm also going to leave one comment here for each entity, because otherwise it gets a bit confusing.

I've attached the actual updated document here, but also included screenshots to make it nice and easy to see the changes:
[E-mail Alerts - Alerts for NEW Research Entities.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/14696023/E-mail.Alerts.-.Alerts.for.NEW.Research.Entities.pdf)

**Researcher:**
No changes. Currently rendering as below

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/e5847dd3-9f86-40a1-879b-06c8256b59ec)

**Comment by aislinnpearson** [comment]
**Research Program:**

The name of the Programs can be pretty long which makes it look untidy when it renders, so I was thinking maybe we could remove the link and have a generic title. I also found a few typos.

Currently rendering as: 
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/7cca44aa-24e3-4164-bc1c-3ce3eb861e11)

Suggested changes:
![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/2004ef32-cc78-497c-a251-7e16792d2581)

**Comment by aislinnpearson** [comment]
**Research Proposals:**

No changes. Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/3226c459-9f48-40b4-9d97-a7c6e6a32d80)

**Comment by aislinnpearson** [comment]
**Experiments:**

No changes. Currently rendering as: 

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/c7801269-eaea-4885-b204-118ce9f2c89d)

**Comment by aislinnpearson** [comment]
**Designs:**

Again the name of the Designs can be pretty long which makes it look untidy when it renders, so I was thinking maybe we could remove the link and have a generic title. The way the name of the experiment renders next to the design link is also a bit confusing, and I don't the experiment name needs to be mentioned twice. I was wondering if something like this might improve things:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/92c3e751-1d85-423e-a33b-5a18cd65a69b)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/e3294000-8b26-4e72-90dd-debcd2ad7ae6)

**Comment by aislinnpearson** [comment]
**Plans:**

All the same issues as mentioned for the Design entity above, so I edited to be in keeping with those changes:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/f1c46de1-f992-41f0-8c97-3d0e726c6147)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/5d208417-20eb-4cd3-9007-1028a3bd4561)

**Comment by aislinnpearson** [comment]
Logs:

The log name is a bit strange in the way it renders in the email title, and then I thought it might be good to follow a similar convention to that for the experiments, designs and plans?

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/9b3f8de4-1eb8-42f5-85d6-93277ef440f6)

Currently rendering as:

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/dcd2a1ef-9f4f-474e-be40-1cfed10b6b8b)

**Comment by paul121** [comment]
> The log name is a bit strange in the way it renders in the email title, and then I thought it might be good to follow a similar convention to that for the experiments, designs and plans?

This makes sense but its actually challenging to load the associated experiment (there could be multiple!) when building the email for logs. I'll make the change for the subject line but keep the body text the same for now.

**Comment by aislinnpearson** [comment]
> This makes sense but its actually challenging to load the associated experiment (there could be multiple!) when building the email for logs. I'll make the change for the subject line but keep the body text the same for now.

No worries Paul. I'm happy with this

**Comment by aislinnpearson** [comment]
I found a very small issue here with colons... do we think it is worth fixing in this release @paul121? Other than that, I am happy to sign this off.

 ![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/aaaa3399-ca1e-44ba-a011-9709a5a17896)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/5d8556b9-aff1-4cd5-aa42-e66d657a1a38)

**Comment by aislinnpearson** [comment]
We agreed that this would look best in rich text (see #626) but this is a visualisation issue.

In the mean time we correct these two grammatical errors by:

1. replacing the highlighted colon on the Design with a full stop
2. Putting the experiment design name on the plan in quotation marks

This can go in the 2.20.0 release

**Comment by paul121** [comment]
> 1. replacing the highlighted colon on the Design with a full stop

Oh sorry @aislinnpearson , I think I misunderstood what you meant by this. I'm quite happy to change this but just wanted to mention that I'm using this pattern (ending with colon, not a full stop) for most of the entity types in both the new + updated emails.

The general format is:

> A {entity type} as been added {to relevant entity type} by {author}:
or
> {Author} has edited a {entity type} you are associated with:

You can see it in the other "Added a Plan" email example you shared:

> A Plan has been added to the above Experiment Design by Aislinn:

The rationale for this is that the actual entity + a link for the entity will follow this sentence. I think this would all make more sense if we had a rich-text hyperlink to the entity in question immediately following the colon... but in the meantime I'm happy to change all of these to a full stop if you would prefer! What do you think @aislinnpearson ?

**Comment by paul121** [comment]
> 2. Putting the experiment design name on the plan in quotation marks

I have made this change

**Comment by aislinnpearson** [comment]
Hey @paul121 

> The rationale for this is that the actual entity + a link for the entity will follow this sentence. I think this would all make more sense if we had a rich-text hyperlink to the entity in question immediately following the colon... but in the meantime I'm happy to change all of these to a full stop if you would prefer! 

I am happy with this. Better to be consistent right? I am kicking myself though because I saw this _after_ making the changes to #605 

I can amend the specifications... but will leave the comments if that is okay?

**Comment by paul121** [comment]
> I can amend the specifications... but will leave the comments if that is okay?

Thank you for the detailed comments! This is done.
