### ISSUE TITLE
Experiment Module: Hide plot_number in plots view

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#634]
Following issues #633 and #632 we were wondering if there is a way to hide the database number/ plot number by default but with the option to make it visible if needed.

Again, this is to help reduce the likelihood of people adding records to the wrong plots _however_ occasionally when working with developers and data stewards like Had, cross-checking plot numbers with plot id's is useful so we would like to be able to have an option to make them visible if needed?

**Comment by aislinnpearson** [comment]
Following our chat on 15 March @paul121 mentioned this is hard to make 'optionally' hidden, so we decided to hide it completely (similarly to the level id's, which also aren't visible)

**Comment by paul121** [comment]
This is done, let me know if you experience any issues @aislinnpearson 

![Screenshot from 2024-03-29 15-40-14](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/24ae0533-e23b-4076-ad13-93c8b712b7bd)

**Comment by aislinnpearson** [comment]
This looks good to me, Thanks!
