### ISSUE TITLE
API: Script to extract quantities for experiments

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#637]
Please could you knock us up a short bit of script to extract the following from any experiment:

- Quantities associated with an land asset (which we can use for land assets)
- Quantities associated with the plots

Ideally it would export to a .csv

**Comment by paul121** [comment]
@aislinnpearson here is a code example for how I accomplished this - it ended up being a nice complex exercise! https://gist.github.com/paul121/9b1ab39c9045ed81817bc05350282cd2

**Comment by aislinnpearson** [comment]
Perfect, thank you
