### ISSUE TITLE
E-mail alerts: Extend notification dashboard

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#643]
An initial version of the notifications dashboard was created when we pushed the initial version of the e-mail alerts (issue #597), but it currently has limited options (see screen shot below). We discussed extending this so there was a general tab, one for experiments and one for proposals. The idea was essentially that you can choose which experiments or proposals you follow, which in future could also be extended to other assets or even taxonomy terms.

I've attached a PDF here with a draft following our initial conversations, but this will probably have to be discussed again once we implement #605 in milestone 2.20.0

[E-mail Alerts - Example Notifications Dashboard.pdf](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/14762339/E-mail.Alerts.-.Example.Notifications.Dashboard.pdf)

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/ca62483b-bcd3-479c-8339-538309640fc3)

**Comment by paul121** [comment]
Okay - I've simplified some of this notification dashboard to only include the changes for the "General" tab. Specifically adding configuration for Researcher updates + Research Program updates. @aislinnpearson here is a screenshot with some updated descriptions as well:

![user-notifications](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/654fa5b4-ca85-446d-99e8-9321b05f0588)

The other changes add the ability to un/subscribe to individual Proposal + Experiment entities individually, and notably, "receive a single alert for experiments that includes ... changes to all designs, plans, etc associated with this". So this aspect will be more related to a "Reporting dashboard" where we have discussed displaying changes in the past X Days/Weeks/Months as a separate feature, less specific to email notifications even. Does this sound OK @aislinnpearson ?

**Comment by paul121** [comment]
Updated descriptions, this is done!

**Comment by aislinnpearson** [comment]
Hey @paul121,

So I wasn't going to bother mentioning this yesterday, but as @mstenta found an issue with the push I thought I'd see if it is also worth making this small change.

Basically I was going to ask if we could edit the text for the Research Program updates to it reads 'makes changes to **a** or **any** Research Program you are named on'. Most scientists have more than one, and to be fair this could be my error. It looks like the kind of spelling mistake I make.

The other one I am not sure about is the 'Email notifications' one. I feel like we could be a bit clearer there. Maybe one to discuss this evening.

**Comment by aislinnpearson** [comment]
Following on from the call please can we also edit Email Notifications so it says 'Switch off all e-mail notifications'. Ideally if we can link it with the UI features of switching off all the other buttons that would be amazing.

**Comment by paul121** [comment]
Done!

![Screenshot from 2024-06-04 09-52-48](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/940da5f4-8105-42de-95a1-cc1601aa7b39)

**Comment by aislinnpearson** [comment]
Just tried this on our live instance. Looks great @paul121
