### ISSUE TITLE
Experiment module: rename 'Experiment Name' on Plans as 'Plan Name' (or ideally 'Study Name')

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#652]
I've noticed that in some places on the experiment module, the naming conventions for things are a bit confusing. For example, here we have 'Experiment Name' where it should be 'Plan name' or, ideally, 'Study Name'. I think these crept in from the time when we only had plans and no other entitles. As part of this issue, we should probably do a wider sense check.

![image](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/16349781/6969d98b-6dd7-4623-a68b-da0fab6b1c6d)

**Comment by aislinnpearson** [comment]
@paul121 I had a comment from one of our scientists (Stephen Pearce) today which went to show this is confusing on all the entities, so I wonder if we could expand this issue to cover all the Research Entities? He also pointed out that the place we need to change it is also on the 'Filter' button where he was searching for his own name under 'Name' rather than the Proposal name.

Something to chat about today which he also asked for: can we have an 'all fields' search, where you can type anything you want in the search box and searches all the fields to find that reference?

**Comment by paul121** [comment]
Chatting today we decided on "Experiment Plan" for the plan bundle label. There are also various filter titles that can be improvied.

**Comment by paul121** [comment]
> Something to chat about today which he also asked for: can we have an 'all fields' search, where you can type anything you want in the search box and searches all the fields to find that reference?

That should be possible but would be a medium-large task. Let's open a new issue if we'd like to track this

**Comment by aislinnpearson** [comment]
> That should be possible but would be a medium-large task. Let's open a new issue if we'd like to track this

See issue #676
