### ISSUE TITLE
Permissions: If you clone a log, you should be able to edit it

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#654]
One of the things I overlooked with the permissions is cloning logs. Currently, if you are anything less than an admin or a farm manager, you can clone a log but you can't the edit the log that you have cloned. 

I'm not sure where the error is - perhaps somewhere around the name of the person who created the log (changing ownership doesn't seem to affect the ownership rights).

**Comment by aislinnpearson** [comment]
Currently the error only occurs on the Rothamsted instance for Operators, who can can create and edit their own logs but not the logs others created. We agreed this was a bug, where the ownership should be transferred in the cloned log.

**Comment by paul121** [comment]
Fixes opened for farmOS assets and logs: https://www.drupal.org/project/log/issues/3457116

**Comment by mstenta** [comment]
Deployed farmOS 3.2.3 to all Rothamsted instances. This issue should be fixed for both assets and logs now.
