### ISSUE TITLE
Experiment Module: Duplicate Proposals

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#659]
Please can we add functionality to duplicate proposals. All fields should be copied except:

1. **Name** (should appear blank)
2. **Experiment, Plan and Design** (should appear blank)
3. **Status**: This should please revert back to Draft
4. **Status notes**: should please include a comment such as 'This Proposal was created by duplicating [Proposal Name]: [Proposal Link]. Please refer to that proposal for previous versions and a revision history.
5. **Revision message:** Copy of [Proposal Name]: [Proposal Link] (ideally the user would not be able to delete this revision message)

**Comment by paul121** [comment]
Done!

**Comment by paul121** [comment]
- Keep experiment relationship
- Copy status notes message to revision log message

**Comment by aislinnpearson** [comment]
Hey @paul121,

A quick question here (which is basically due to a specification error on my part): did we set permissions for who could and couldn't duplicate proposals? Ideally it would be the same as for creating proposals... but I can specify that as a new issue if we need to.

**Comment by aislinnpearson** [comment]
Agreed that @aislinnpearson needs to test this before closing this issue.

**Comment by aislinnpearson** [comment]
Tested this issue on the live site and the permissions work as expected: only Research Leads, Farm Manager and Farm Admins can duplicate proposals (equivalent to the permissions of people who can create Proposals)
