### ISSUE TITLE
E-mail alerts: Add e-mail notification setting for experiments

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#667]
Agreed on the call that we would only give people the option to choose which experiments to follow (you are automatically subscribed if your name is on an experiment). You will get notifications for any plan or design associated with this experiment.

If you opt out of following an experiment, you also opt out of notifications whenever any designs or plans associated with that experiment are edited or amended. 

You do _not_ opt out of getting logs. For that you need to switch off the log notifications. This functionality stays as it was in Milestone 2.21.0 (#643)

**Comment by aislinnpearson** [comment]
Hey @paul121,

I was thinking about this after we hung up last night, and I wonder if we implement an even simpler version to start with and then add in complexity. 

Given no one has complained, I wonder if we just create a 'general' notification for experiments people are named on (and then do the same for proposals). Then we can wait for user feedback, and design a more complicated system if we need to. That I think also gives us a bit more opportunity to think about the user interface/ experience. For example, I was thinking we should change the way people are 'named' on experiments we could name them as a viewer or an editor. If you wanted to follow an experiment, you'd have to ask one of the editors to add you as a viewer. This to me seems a much simpler solution (the only thing it doesn't contain is the ability to receive specific notifications for certain experiments but, like I say, no one really seems to be requesting that at the moment).

**Comment by paul121** [comment]
Oops apologies @aislinnpearson, I missed your comment here, but yes I agree this is much simpler. It makes sense to start with this if that's OK with you all.

>  That I think also gives us a bit more opportunity to think about the user interface/ experience. For example, I was thinking we should change the way people are 'named' on experiments we could name them as a viewer or an editor. If you wanted to follow an experiment, you'd have to ask one of the editors to add you as a viewer. 

I agree, this makes sense. The concept and features around "naming" people on experiments has somewhat changed with time... it would be good to have that more solid.

**Comment by paul121** [comment]
I've made these changes - adding Proposal notifications and Experiment notifications. @aislinnpearson let me know what you think?

![Screenshot from 2024-06-24 15-25-15](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/assets/3116995/7a501ebc-0db2-4b28-9d21-696f94404adc)

**Comment by aislinnpearson** [comment]
This looks really good to me @paul121 - I definitely think this is the place to start.
