### ISSUE TITLE
Harvest quick form: increase number of trailer loads

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#706]
We had a message from our farm team at North Wyke asking if we could please increase the number of trailer loads to 25. They have started harvesting silage and have quite a lot more than 10 silage trailers coming off a large field. They would also like to keep the logs as one.

![image](https://github.com/user-attachments/assets/a535dbd9-f3d2-42ae-b777-2a986135b445)

**Comment by paul121** [comment]
Simple change, done

**Comment by aislinnpearson** [comment]
Tested this with 25 loads (including with errors such as the units for the trailer weight and gross weight not matching) and all worked perfectly.
