### ISSUE TITLE
Bug: notes text truncated in export

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#733]
When exporting logs from our Harpenden instance, Leo found that for log 9221 there are some missing information on ‘Notes’ column in the csv extract:
[Harvest (Combine) | Rothamsted Research (farmos.net)](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frothamstedfarm.farmos.net%2Flog%2F9221&data=05%7C02%7Caislinn.pearson%40rothamsted.ac.uk%7C4f6b5b73ad194820318508dcb6164622%7Cb688362589414342b0e37b8cc8392f64%7C0%7C0%7C638585453991797894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1KZmtELWsz%2B%2Bj2aetvyvSZehczt%2B8OVYmVDZjlAXxr8%3D&reserved=0)

![image](https://github.com/user-attachments/assets/bde33200-e79b-4d18-b307-96da73dfd95e)

![image](https://github.com/user-attachments/assets/fc319157-44dc-46a3-966c-1dc00c1b689c)

**Comment by paul121** [comment]
@mstenta did we get a core issue created for this?

**Comment by mstenta** [comment]
Not yet. Please feel free to!

**Comment by paul121** [comment]
Okay... got sniped, made some progress :sweat_smile:

**Comment by paul121** [comment]
A fix for this will be included in the next release of farmOS!
