### ISSUE TITLE
Data extraction: Collaboration notebook for extracting quantites

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#747]
Until the issues around exporting quantities from the experiment module are resolved, @paul121 has offered to make a collaboration notebook with the code needed for Leo and I to run these queries ourselves in python.

To be addressed asap so Tony can compile yield books.

**Comment by paul121** [comment]
@aislinnpearson I have this ready! It was an easy add. Can show you how it works tomorrow?

**Comment by aislinnpearson** [comment]
Absolutely! I'll see if I can ask Leo to join us.

**Comment by aislinnpearson** [comment]
Link to the Google Colab document with instructions here: https://colab.research.google.com/drive/16fGRkV8A6MwqykFBzfvYUcuMb_7b1VkI
