### ISSUE TITLE
FarmOS dashboard: remove/ review widgets (upcoming tasks, late tasks, metrics, active plans)

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#748]
A follow on issue from #679 (see comment here: https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/679#issuecomment-2288727126). 

The issue is marked as medium for removal of the following widgets: upcoming tasks, late tasks, metrics, active plans

To add new widgets would make this a larger issue (each widget possibly it's own issue). Ideas for alternatives include: 
- Farm calendar
- Logs for review
- Restriction zones
- Calendar view of management plan tasks

We agreed to see what requests we get/ ideas emerge before adding any new widgets

**Comment by mstenta** [comment]
@paul121 opened a core pull request to enable this, which will be merged and released with farmOS v3.3.0: https://github.com/farmOS/farmOS/pull/868
