### ISSUE TITLE
Warning: Undefined array key "column_name" in ExperimentVariableForm->validateFilePlotAttributes() 

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#754]
Just saw an error in logs on this path: /plan/%/variables/update

`Warning: Undefined array key \u0022column_name\u0022 in Drupal\\farm_rothamsted_experiment\\Form\\ExperimentVariableForm-\u003EvalidateFilePlotAttributes() (line 384 of \/opt\/drupal\/web\/modules\/farm_rothamsted\/modules\/farm_rothamsted_experiment\/src\/Form\/ExperimentVariableForm.php) #0 \/opt\/drupal\/web\/core\/includes\/bootstrap.inc(164): _drupal_error_handler_real()\n#1 \/opt\/drupal\/web\/modules\/farm_rothamsted\/modules\/farm_rothamsted_experiment\/src\/Form\/ExperimentVariableForm.php(384): _drupal_error_handler()\n#2 \/opt\/drupal\/web\/modules\/farm_rothamsted\/modules\/farm_rothamsted_experiment\/src\/Form\/ExperimentVariableForm.php(215): Drupal\\farm_rothamsted_experiment\\Form\\ExperimentVariableForm-\u003EvalidateFilePlotAttributes()\n#3 [internal function]: Drupal\\farm_rothamsted_experiment\\Form\\ExperimentVariableForm-\u003EvalidateForm()\n#4 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Form\/FormValidator.php(82): call_user_func_array()\n#5 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Form\/FormValidator.php(275): Drupal\\Core\\Form\\FormValidator-\u003EexecuteValidateHandlers()\n#6 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Form\/FormValidator.php(118): Drupal\\Core\\Form\\FormValidator-\u003EdoValidateForm()\n#7 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Form\/FormBuilder.php(593): Drupal\\Core\\Form\\FormValidator-\u003EvalidateForm()\n#8 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Form\/FormBuilder.php(325): Drupal\\Core\\Form\\FormBuilder-\u003EprocessForm()\n#9 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Controller\/FormController.php(73): Drupal\\Core\\Form\\FormBuilder-\u003EbuildForm()\n#10 [internal function]: Drupal\\Core\\Controller\\FormController-\u003EgetContentResult()\n#11 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/EventSubscriber\/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()\n#12 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/Render\/Renderer.php(627): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber-\u003EDrupal\\Core\\EventSubscriber\\{closure}()\n#13 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/EventSubscriber\/EarlyRenderingControllerWrapperSubscriber.php(121): Drupal\\Core\\Render\\Renderer-\u003EexecuteInRenderContext()\n#14 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/EventSubscriber\/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber-\u003EwrapControllerExecutionInRenderContext()\n#15 \/opt\/drupal\/vendor\/symfony\/http-kernel\/HttpKernel.php(181): Drupal\\Core\\EventSubscriber\\EarlyRenderingControllerWrapperSubscriber-\u003EDrupal\\Core\\EventSubscriber\\{closure}()\n#16 \/opt\/drupal\/vendor\/symfony\/http-kernel\/HttpKernel.php(76): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw()\n#17 \/opt\/drupal\/web\/modules\/simple_oauth\/src\/HttpMiddleware\/BasicAuthSwap.php(54): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle()\n#18 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/Session.php(58): Drupal\\simple_oauth\\HttpMiddleware\\BasicAuthSwap-\u003Ehandle()\n#19 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/KernelPreHandle.php(48): Drupal\\Core\\StackMiddleware\\Session-\u003Ehandle()\n#20 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/ContentLength.php(28): Drupal\\Core\\StackMiddleware\\KernelPreHandle-\u003Ehandle()\n#21 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/ReverseProxyMiddleware.php(48): Drupal\\Core\\StackMiddleware\\ContentLength-\u003Ehandle()\n#22 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/NegotiationMiddleware.php(51): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware-\u003Ehandle()\n#23 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/AjaxPageState.php(36): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware-\u003Ehandle()\n#24 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/StackMiddleware\/StackedHttpKernel.php(51): Drupal\\Core\\StackMiddleware\\AjaxPageState-\u003Ehandle()\n#25 \/opt\/drupal\/web\/core\/lib\/Drupal\/Core\/DrupalKernel.php(704): Drupal\\Core\\StackMiddleware\\StackedHttpKernel-\u003Ehandle()\n#26 \/opt\/drupal\/web\/index.php(19): Drupal\\Core\\DrupalKernel-\u003Ehandle()\n#27 {main}.`

**Comment by paul121** [comment]
Hmm this is interesting. This error was thrown when preparing to validate the Plot attributes file:

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/89ac01f0386c9df1cf46502901b3ba6823bfa3ae/modules/farm_rothamsted_experiment/src/Form/ExperimentVariableForm.php#L379-L386

We do this preparation so that later on it is easier to validate that each Plot attribute name is a valid `column_name` and has a valid `column_level`. The error we're seeing says that an uploaded "column levels" file didn't have a `column_name` column... I think this means the CSV didn't have a `column_name` header. Which is interesting, because when validating the "column levels" file, we explicitly say that `column_name` is optional... :thinking: :

https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/blob/89ac01f0386c9df1cf46502901b3ba6823bfa3ae/modules/farm_rothamsted_experiment/src/Form/ExperimentVariableForm.php#L312-L315

@aislinnpearson I feel like awhile back we made a change from using the `column_id` to using the `column_name` for ease of use. With this change perhaps I forgot to make sure the `column_name` would be required? Does thing right any bells for you?

**Comment by paul121** [comment]
Maybe #275 is related?

**Comment by aislinnpearson** [comment]
Marking as 'Closed (not planned)' as assume it was an error with the file. Re-open if it occurs again.
